sprite $10GE_FCoE [55x112/16z] {
tTS9TYEj3eRXJqWW1FlVxor4MQSuZTt1zv_V7Z4y5faJ85i_J05eFy-GUszMzI1hhQjUIX8TnDfwjzuodSKsc74wJ0UhnwnCzgQKUDzamji8z8cPR4i0Y6KJ
wygOUL40IUob9AzMnW0elUIyfCmIZRsLPPaHl2HUJkDS3aG0hsmc1FOJn7aqsFquACdOphF9Ifxvuy8q1awMhnXpBO2ix6wSAwL80aZcCXQnErgP0596Oo2F
SqN6Q3-T2Losp0zwVZg1cEQe63QhphJSnJDgIV3Yh2261OiOoEeL9af4gTnB0XLzvQnfzDYjTkrOVJvVP3UBCe5rrFgTGm54txCuC41hxNQ5aFHH2nOnA6jp
rQTJJQ2og2VZhAC46iDS-D-LGVVMmBNroUfKaDUh9K_HfjLumOZAL9DTAGCq0qf_LXyxfAw25G8YNHaUvHxCQhMQ2KaycdkH0YmZ9aWBrisiccKgDYe4MHc1
grrLSXLibfqf8Ud2B0DYetAhO96__iqUgfa9K2p8ZWdyhksfh3AezW-i0DcyK5u2VvYc1BQxB5Sw9ZT_jUJtZ44QjnqblOVak6QmzhXYCQyoG202QVTQ0g_C
QrUMmDQijQO9L0Hf_9lZhQSBYnGqLyMdPAJU1E3ve23j6KFy4G6ITMVNtw-B6a5tp0XrZeAq_c9TqprG83kcIFvIpNUkO7vH4ki5l6CLn0HGRdrXSo2bjBA8
CP_MioeWjHVq9zGjQrgqnPK9LnARLahj6nQ52nLzPE527R3OEjxxnp3zZkNlXk4RPm2osc4PVtdPlhcazVCKsdipFQXQypTRgq8doUMiTsCwIvnfEgr-nzGP
_o2Yn57zEGF2iJgJVUz_cAX734W_OeaYp8X_ptB2Bz4OQCxoctOC93axgmVCrSrAb5dA8qaHJSIvN0MR2K7AFfwlo5A2MMmHFZ7Yugqi4wv4tx6KoyhqoaVv
FQAYZvPbiDqhJVHDmOHmmjhD2czOVgVgpQuomIEAydircSUxc-rLi1YOQsnhz5pRKCxgdV9WiQhFX4eTsK3EMesAR-uIaAYh3JDTPrYrwhzD051f_S4ighPK
DHeCbDlAzWbH12_fJnX-YQHzmv3icCMmpqpBI4SSBzg6LT4LjjPd-VcATDRjLI6KdPaiwVQdXoe0Yl_u4E31ObGmJnEkjE_Js5XO4yA8SsJzVVOSjQQ_PKeu
PLwXO-OPmqiSsUzP3DJZRvMDJraCF6Gny915_oMcNx6CRvm2K3j4be7_0G
}

