sprite $6500_VSS [55x79/16z] {
xT1f5Yef38PXoF25XFtljqqAhN9eR-Fzsy_nCCdhK4qyjacJ-8LuE8ItwCXoKD-4ofXARwNJczwUtpeouKHj-PBnOMM5_voH72fpQ9979lf4-97fmOwiA2z4
97WG8k95S1WhUo54_BewMLNXzWvCZ1mKzcouH_7n2QZtZl4gct_F8CIeuPgiPd4VzReRODPnNQLuTR-y20lymNAxZ7WtUZjelklrAWvg1_wMiRpwchK5unL_
osZnU0KwQ7pWIxnxVyVZ9_9RrSHZbqkxeLqjaMAFPgS-TxasdJF2DqJ4TF8P3juWvZ6HNzct46Bwd4QRs7_Bh3BUz6is_YQJ6-wzimXJx_J7xSgOPSlAY6IB
LwRC-jyHwzzaGxUGuCYmXVUpfJB7bU8J_PI9uA4ptd7Nzyn4x0uazau8vnfspS1gDpKYJv0hPTHeZpNfFTEwskcHQHCpxc8ckJ9KHXt7XJYo0vWDt4cWf32G
v6KbDQ7EC6POPNvcXQctcrx_18pwUjmFsGeyNZ9jXsvcGzd8KbP9BOs8bGrW3Bkzg2roF8RwLcaBvHMFCnCPO8NsjdGYwfroelDGeMpFcNHcRjyn2scepPbP
kAeF6sxK5bPLPYN9kIqq8Zn27fcPb_EHk3jaSCxd8uaPSrwoEwmRXDomLGQwVzOiy9SC3ANM6M2u6uEh0hWtWh55PZLKDaPMJ9OZtDr8t3a7eTfBpEcSOpeV
oRhgBbOZ3GURZpoCwJflbFmzy-59u6kpvlo68Jb6v6X-pHRhugUybxJxlBi_oHbcuNTgTJ_D1qUyPqlSpQzMjijZPTjMPlPJ1cmK4JzbEgu_CjoFFtiplstP
AblVQoBYjwMAO7xRYl_DatprVuQVCYMV-z0QOR-YzWy
}

