sprite $ACE [73x55/16z] {
xTC7TkGW381X2GaLkFzzDxAriJsOD6Rx_kayyJrb2gBrzGp3QUjr2yVTRILtRtrpQi6L2eVq0bLSZNU8S3NQ8AEo6jaEBVUxGiwq6liEBRS4KLJeWBhNBpcm
jKFL-mPzgH8ESeqIaZfFAbF4LQhKupCXadqgeNcL4FQGgfnYt0xpx6qenv6Y-8LFVlnPWELZ4CVuwIwTV8eZEKFDtt3exay2A5MoyqOwWJ1NpxH2733ccgSq
eVi8IAynOF0am-nRa03AQBCowv2r2PINxd3LMsU4f5JTGXWMoiDXrdkxWI0V0y3RDMMSJQUxgJwy6KbKeEWOGnrcjRr29l0GgG2f3J7KOPQzxpKphLmp0W1a
DOMYPjVFWEHnLZoCX4u9xAieejeGWLncZtL6Y6Iuamswa6t0TyZj9XUWuQnUppo9L-WsGn2_fWZg8kQHkVViRSW5KAyq0GT6-t7h0pI9eEZLAUOk22W3yoPa
j5t9b793Om3o_d4ehuYQcme1a9xDrbqUrl9vSHyG4U1OhlNU99PYq06Qfqo8M5WibJqZG02QFF-pp3oLerRX9UrZhRq5jaIE0igLvhLWz_far15ofSMQkwcA
zj-o__tFdkMWFSd1b9QTRm
}

