sprite $ACS [73x55/16z] {
xTU7akCW381XL40IVl_tFH2QO5s6lU9CkV9lmS7hBsAd1a2kvma0sDMVTzcOfvkPFidC-kKEuxDuIWDYU1el29_daEBpr272fr50ZtFe-XJKZPvd3Z5z4KBn
0EaS1tICiDn2uaC_WgXy5tqDrSDTZ3bea8HVINL2bzKLKqsXC-ntnk_bvh-P-zwQgAtDKYZYU5t06GoGNX951HRSraHjn5XsE3VSMHU8KB36NgpHt1_PDJ8P
L_KEqTYOhxdv1Vbj2fqov6yc0SqQ0t1KHUfynFUXjB5mmRaC7feqYYOhimqv9Jlo9qQjm5xSPtb5LRm4vT07SW5z1SpxkJC4ySwj5cYZkSIaBkQqdw1MIcdh
A3jS6t1mZf2CE47xHiwk_WCe9cAzG_3kh4n5L58g2z85wOK1wVlHT3e-KLTLqPJ_iwjgG2GnaIhxSY_cSSYJ_Jt2KkW5OGiezaSIJxYJeHpF8pYqG_KZDzsP
NIU8guvidetKMeQKucJCoGd8nevI18L4pKSgpOHlDH-mcWeMm1aHwHqoKoaxQ6D7S1xEKit7ocDAciYVUqKoT-eYHxf-vZnk-xG5LWcQIKGunt0vq4YeZ5fS
aqKzGplHxNZ4Cc8iCKzqUJbB9IU7agPuw-YGLBmnxSX4HqVDL1WH08bbAwVwqObK3xCSlDxVdQZt4tBEmh7kNRzRGBI59r8upwLm7jV3-UlxdtpA0Vk8O_2n
JzdV
}

