sprite $ASA_5500 [73x55/16z] {
xTPdmYCX281X10J1-zzt6MEwJFgl_PxfxKqlmDu_vmmSyyz5AIPpQv-mAFGOt8GmLmRSGMhkFKA29GKd9OSwGiQOAN2XO8fdY19bN4u1nofbsAv2V3qIdgwT
gT7asp7K6LgZhJFMS5jIb8ZNgaUeM-MJcmU6vxL3E0r5noz2TFr4bzFgk3C8m6ioGYvrXG1uhYAKRPKZLvT6gDiwX53gnBDOTaFkieI0SgC0of9w3wwFGlKK
efsGkouH5D4WN5Y7BQGhftkqn01RgEBvxJFMpaHFza82mADt-NQYIrLrQeTGqoKyF3OXu9r7zZZKAW1gYw5AKsqH1cb9g1z22GOWdUkZKwGb-j0IIW25TQno
0SXBDZfkBSFp2mdBjfANl0_MKe8maSWegQMTRZkQCY4HQpFJMRhJar0YBVKqj5_Yf9E4qbBUKNu10l62zb3XS-CVH9Er0bKUqQbviBQ6HTi-E_iePDy9cTs5
B0tjPHQXjGWrI_qgvE-5V1lTxMBOAoKXd-nYz5T3VXAhkTsGFrPvhG0_JJmWV8uzgBo0WML1_LKLgYV-vz1VIFqbYia52khVe02Wt-dy0m
}

