sprite $ASR9000 [55x55/16z] {
ZTPdWgqW38PXI4ZXo_xtUwLuScMSyauzocD1Vr1UecOEH0JWrgZy9LAVOhIiA_sA317efjAOkObQ7nkCVaDmPQgrb5h6hqgiZX-XZjr2zOp44D1tH1vmeVV4
4KulgY6WJD_5Ya1xKrrgvU-JFjsfN6eftpgg93xTgMWzwZCcgkMAs-a8qKMuB2TNRNvBavo6yRa7A9a7T0nQJaI8PDVAhigL8loZD60ogyln6fJRvjQH8JGl
qHzZngzaL6OiC_zSfWNqRhYPw8wF3GZRimZNBwwbUZ87Q9_CT9VZMFDJbLggxWnXU_AJMLjg3hDRcLQoUyHw21fm-oGvlMQsrFXFnUvyJgO7BDF6zSFQLaS8
BuJDCbMvh9X9gYS3jK2tHpw_Pt8fjxEEQ7OnVsIUoQNyx6BcoNujcUETcTXF3E_CgF2-uFxA8YvtTgbokQwLcWxw2B72YvhCogYIg1rg1jn0hrz-g-wrxFI3
iCG3Qj5RzH5j9KyKGEmmf9GYSsZhCqarJ0xs-8J09AcwbXavXidS8ZBK--XOUTcknoDh4LalCyR_n-7fy63jyTdAAY-1YqA-E53noAISJdLkFfoNef7nGfKq
fobUd3u-eLv2p15dqqbUu-D6aEB5CHvJq8wXNKJws2cYOvUAwELIWVB-CothXiTEh6TG5ycJlJmJ5s6o22DIH6SIqSZoLT8uqog0DC2guDnNxZpEEjVrA2oE
V9lpChkgTdIUp05JjPTBF6TJvrbedut6C4hL4ZsTCxDXluaTNPZbKAVBjCuLLsu-rAlhJ0uHz4Psg3FoV4kg89IgZhFo_ToSockAUqeatvA-fmJwyoAqYqnl
-omgedzPY7ufqQzhvUptjVBVL-R_
}

