sprite $ASR_1000 [55x48/16z] {
dTQ9ajiW40HGe9ch__-38pD8XMn8glBs71VjtXsVPQKyqt9IWt52eXmeJKxiM0U6r1F4gSvfhPuqfPUTpkXjgvPI6vnzlmz3sogNrfHHT_lmZgtFuGfWjvNA
KEoDTLqqYCto_rBMSEc_TM1e_m7qZl4dZl6tpccoYPKsof2Z6Frx-IeYim8oeGorIz9W_rg-2chD3J-nNjwp6AE-bg-gAAcAJZFMkjwSkkx3zDBcg3Sf4tIo
89OoMwwyGczrriaJS-fIDeowF6P3nY1gfdc1sRCLfrkISeFUCOYzEFrUljrQgNFh5MFE-6hMrSYoMGSpQLbeUpvk1CsoAS_sUiNK3e9QGFh2vWzKc9-GS8Rl
MAPKDkcWP-p4McdgWxrY28R7IS_TH8GsVprdAcFBx8wLsZrG96xZZXAxd4jj8umHR2ZbgSj7GUSkL4gBGLj9Jntx6FqhbpVRS-sUutC1FKVmbPDvgdfCXgME
dDFNLhJDcCKDIntry0BbyXMpvRyZw_fo60ifmnD3RGr0xnRCibsTZPUA9UOUiIx_qSdtNQE7DeiVP2yh9rzbldIiAIyl8DUr2IFoynyluBg-8sZ1Zt4mfltR
XHeSebs3ySC060Ne1a22kOzjdLynPAfPA1pgRd27BcKBdxdUiamwIIZ4t3FsbAqwf-3GXMHNGDGR8BdyRTrAGGOCJZg2kVmDy2NmgOgCyOAofryvKnNwAChb
xzNWoMRv__F6y0y
}

