sprite $Bed_without_Patient_top_view_ [74x37/16z] {
xTRL4GGn38DX-nADn-w_tsFctJ3y1Nolajc68iHgUybBSFuaYRrFS4xjL_9T0fsJfPAU2fKKVCv9aAHCjn0YWUvYMIyfqts89ha2qfIcDAKfJGarR8kferie
kS7Xlo3-Ludtdw9-kdW_SmS
}

