sprite $Bed_without_Patient_side_view [66x34/16z] {
xTG30iH0343HJ0RH_SzRsrsZVrczkYb0KH9L5Ku1uMGXgK0HQvDmF8UmLO8JxPDuWu0w2iyBOGI8ks4RM0Vn3Ni1Bh5eMxf5AC8GcQKit28qEInh_lE1N2NC
vwqC5DrDi1RG9dsnS0cGniMp0iw2mqB0Gh1PYaS5DTFYnREE2ynYYy-JiqVoMGAa_QBhXLjxk709bv03
}

