sprite $Bed_with_Patient_side_view_ [66x42/16z] {
xT5jZeCm38JXyJXV3lU_xrfKLeb4nBhzs_S03uo39L6F-3mgIJVmQQ8YGls2KC4BKCbyLww2a9ezXGt0qywNe6bXsWdCmmWbzKF1WUEOIesG54x0YHe0SVuD
-JyX0Ay5a5apZGv4dHx0p9ffKgw4m0k0cJj4Ha12E3dKqLijIjaBuBWG2YmZP4pFpCRetQMW5W7ItyGiu7M4semigFTFrU72MJlUlOWOqUPzJXMW7o7WUiyc
N4Rigei0jUkJy6R4Wx3USmXt8_R2UazJneY4iDnpneYCiDwpn8Y4iDnpIen82CizUun82t5FZH4P8MhBY6T145tlsPOHMq5SEEocXn6HcSsDO1tF8xnJCCfD
U1xXDU5m0TjYHFuj8XdV2cmFQGZVj0e_uIVy0G
}

