sprite $Bed_with_Patient_top_view_ [74x37/16z] {
tTO50a9128JXXM43lFzvxMuTpFy0dxwUS2q9YK_2rJgThQGUvnjrtOXRzUjIBUlQevAlOYMlq5LebEGekuoHQjclFoyv3YGZ93sG4FFSaYGtJP8gE4b4Lb87
9IaMwLnoeoI5wfAow60aXQmaM3HAWcmaZCf8ecKhTVitgUZUUI8b9QuTSJyHzpZxtF7l0gzPKWpBaiBnqVSu_stXltVyDpX_5-HlbRpzbBhfydRc3
}

