sprite $Blade_Server_subdued_ [55x51/16z] {
xTO5bW9138HXAlRc_XT6Keqr8vbUbty5yiY76n3JtW9033IbSjDwvWaZ38SzmSvg2gUg1xymmzxiFTXXguu91902a_nfJ5Y5iIlJdF8KOimUGZHtoPHT65Hp
ZrC_Yx8LfbMcgqp7cJuoVtycDIObvicC9JFZMaxzhCRccCmngp5hJ6jCRyp8EEFEKf6rbbcRjQcEbQwaHy-skY2FE_FysMP4ZR5aM7szcSSyKtTSjZZriyNx
CgkpM6RtEKQOn6uc8onYYLtoy6XCaaM5aTxNmBL_Td-30z_pktc9RVI-31iAtZEwhQ9ZnRwCnLWOa5DWyDlh2G
}

