sprite $Blade_Server_color [55x51/16z] {
pT87OiCW38LXDaBS_xwL_BmtTELl4xE-R6E8QrjCHbJbrYeDYb9Bf4vmThObbyHL9gW6HygoQoqTcR-vR9blhPFbWOKn_rX01sQDiN9nSd7-C0yR5j6McHqp
oYAQ67faSSseaoNqWYL4O6E_nTAQbKwMqGk6Wvqib-ynz8P1jR5PAUESwJqZGM14cIHbJl8IBlkv7kCL8x2dCXMkPynPw-RBOPv1k88L_HkOmNknSbMrcvVA
gsShS6-O7DSR67h567yhHiziKi9g2qDujZzbbT4pumtJL3UnEGxpCNVFq97PZsPs_iNhwStyZjrtpdmVY-6-27PmJzN_YliOzIb3NSeOujP4VG4
}

