sprite $BP_Cuff [63x81/16z] {
rTO54hGu40NWjj3oxd_UbHH5c4Lg0llR6vSlJGIXVIIgWcawGrV5KnxLOm-BT_ouVAirycRRA-qLh_P4yrRTtrT_t_Vt8_z-tkTNtKzSy-_tk147Z9udNd0s
1r2kZxGLqfV52o5FkXssRiI3kMjOHYy2EgSLFZHnJYxSJDvQgeMqVAwuxKUGoOidUDl-lG2fH3RL-yYX-whbiXaU_OKTSABEspJd01PwmFj8QQ9iZEK4DoXf
3KqBP89pEMcbZiynkMQDb6aKrzbpXD9EEyr5iXQY7dOuqwntvAAgjXGQFOWcUbpeKQJhP7h5wJpSCybPr9f7PDQ_oSnmRoRo1HVpmdagtVW_t3rHRNnS_zZh
cQcgcLbpZ-gjLkF3uezD5r1kClxosIKl80xRNxorXCRtPqJWiEzikreRnK_hjy21Kq8ttbFXRJz8ecRkMG1EkCC6Bwo9KJMnfSvus_4U0B2j-2fxZhmTUUrN
iXIgvvmR_8oZ7VXCTPHynHrsok5VyOIUyv8lkA7uX8_oVC75FBB650sEDNB9sH8zrUYInnNN1CfDHPYkEVIS6v0su2NFKsw03tp3OITS-vBwYkUHSyBfIrvy
u8RaMpvomZbXz9mhYbzmXzCBdh0t791NlFYFvFDzHqJYWnTqWlTyj0URuEx-oGrnmGt0LTz7p-kcyprd7EX9fUjLI-A5VLQ-9btxEGzALs4nZmzEWShmfkCo
e8Jk4cYYQcOclKN-h10elUD-CJd38qmkebRtdBWLxX9Czv6MOrtjKvLXD_fl
}

