sprite $Camera [64x37/16z] {
xTL7WeD034HHzw20IlU_xpYxd2dO-kyVeUEEIhGMSX0tDCGwRtnK8oObBpHxnD3o1-z_MlRe9or_yA7x7EpD9XFQ-ouRx5tnWTwNu-mxNElaksoJtvVZw3EK
FAw-KLNOUotQC40tvXMUK_sypIVwmQTKDUvzANf-ubspKB7KFRgntXTRtPFcKCiYJYCFygAsq_x10ln2vrwJ5p3V8NlVmButb32LHlV7DJpKRzj3ycBR_S_V
MkD1tg3xt55MqAeS_m
}

