sprite $Cell_Phone [32x60/16z] {
pPK5ZW1120IxCmIMOV__tPFcN3YNYbLIwpl2g85G7eZw9SvyI3t7-83y-Fbd_KyE6pYg0WF-dhvC46nPm6fHPvPmU4jYLRFKzwdlv_2Mt-_Ng5-ZBkaE3x6m
MXoCXke3tzBP0BTsB-f72OEt1BWb-_NtF__m--udtpUsC5XBW2b9geC2puJVz7sNuBtScZhpoVSzmFr_n-_px-if3DRYO4WEgW_yHkT0LDKUgATareIHCMGz
QtoX4-3q164M7ze0Wp7dIm
}

