sprite $Cisco_Unified_Presence_Server [77x55/16z] {
hTW7LlGw38RXJyLos_z-h-HaJ8fp0dV-bsAJyXpHOI2bzMzh1ICflNrVtxImYgLlikgQm7CsCtsN51y8NczLw1Wy-cCwiSA725iq3wpYIr8d9Zo3jqytxLKN
JW_OZ00wRXZ4gmWinrOO0xohDBOCMKVqXEdFOFJPxFj7x6cogdi2iBAeKAmWKO7eCc8zbkwO0Y8W3Ija_Hv3M1FJNs7sWoNT2mOObZBe3rZxmJvztaVVnfJ-
cZGj8qd73fYbj3thc2fEZi7YWAmZcJVP1PifmeY908stwIcnOqlC11u1OKNfAJkLMwjtp18FZfD5YPxI2zPjnxATIfhc5hgEv3fP3461dJERsqHsE6nvnf9F
jOJeWfam4QlTC6FYvAlQ2bDuTC4KMvIk60i9MrQwOwQ4aMCjpsJxqX02D7isCMD_4bDWmpH_6bSlC0qZCWPiOFaJ9pDMd31BoY4jCO9aKqTpPiWPCnPcUA8U
aJ0T7KuxLlAe950sG0NiAnsno1HFiTKoiDxAda9A9dWIKrefZfLP9YmZoRNtAoQE5GFWHEOx9YievTgwjvnCu6cvJHR9_2q74j5a0OtQ3RFjOoQyhNd3hjeu
mbgydMh-DB7wyq7HeZ6TRUzopHUig6CrLAsRDPlO9mMib5h7JLPhOFLKKSIHm6eDunah0eXjNxDQ5rXeuuXeZFM8JMr4gKOPieuiW0TiPa94hFapnxgKoZiM
bLpcFiiovtw55LEHb3yOtMUoYF83rW-MCKQIDuphgTRwbZnWKVE61P2e2a1vmye5UiLc6T0QRcPmcPErg1zhxrWJw7vJPQHnXQoZLwo0ghzMgp4aD-VjgVg6
6TGF4i9fXEe3wbElM48AqIkz2qh8oPPHViTqms8e7fZFk4nUiGmPduKOi8Ru3LO9EPOQKmRyZF4R5WBLpv33RIAsIhY-Oar0sMUf2T3jYEcgLFihrgi0n0mW
zPUMsENxn48YoVr_OQLVggMq_lS4deJsVGNHFttqu3y
}

