sprite $Cisco_Services_Ready_Engine [55x55/16z] {
rT07ZiGm28LX5zd0-FxtNOQ0ercsG6Rh7pNhwKkh5LSsh7TroyQE5H5a8cB72dlDr94TCrLn9mnQDZ1MuxNMfh9QubLZlJS-1Q_IUbUM3PvZgL-Y3CTe9LuR
mrXlclmebmnDwvkTrTA7omtu4PCxMyMpUSPiQhrmGmz31YlCfcSqpzfb1bC2n-0LWxCxquHDFJ0RiACeWozWU6VhaGs4e-6PgILFmvqmxM0sr3smChRpJ1Ec
wdC6Zh4IjZAC62IO3YJ8c5so4XwdW-aa0wbIjjDLChQ7AI-eARC-OB1Mcf5djm2xvPbyap8Zdp2qlvTxcY9ZNXgR-Z5hiceVirqly-5MAyZS6dp9GJvzUtlz
tIpnvjECCgrV2deyEDaeySR92EBH-ZVXDLNnaghgake5
}

