sprite $Cisco_15800 [55x55/16z] {
hTP7ak0W38LXaHNkVzy1D5qsE63K_HVRhvxD2l0ekw7lYlTg3YkYiXDLsBOmk9q2ja6cbOBPKMF5l-O0d1yhbKbPAV1JkRFmd8UM3sChvi3276XXgdGMRzCF
L1R7YZmodNfXc6xoS2gaiISM7PoBtrW0U6LuopnyOPI73ZNa07p-tyGq1m-vNpBwnhmMHbQ6RbWgGpFJFCpbCcPaR658eWpFtJ4yQahNi5LjJhsRAz5KTwDC
y_2UHqHYuODHFMlMrKzKmtRMZEH8KRNBVsCvnJHqCrge9ptUOyVK1bEqoHJjCX8J2ocsyXOxj4mniu4DSO0vfyNLys4AcOc9MLxZz7oJYq43qq43qq43qq43
qy5TfeC6feC6feFA38CM9fnP_YgqAOycPNoP_mC
}

