sprite $Clinic [41x41/16z] {
tTC5cWCn241X20mV4Ev_teMwqQpRgtV-yMJ-oQ9w1NCJ4VCbLOAATE4OZh4_SriAP6RCpwrdeVjDkJDa6gsaAqYjSmIiC_Owy_pUdNeOmF1Z0y0wg3TGFxZ5
_J6E8QbaZ3h6_Z9UdVNMkZ0iQ6O5qQANYWco-j3vh9BLoirm8KGaMO-pcEu-YwsBlp7t-lbeLLrotgSftB8RvmHGeo04zab2kh-HuTZ0sx7sav29Y6_WHbap
Ag_WkNyEfstxRDxq0W
}

