sprite $Clock [55x55/16z] {
dTO7SYiW38JXHID0xDx_lA-GKOe1O-TBB_y0IZ7OC8-W_cE46rvXBQWftqIxbXwK-9F4yAShXIIk9CLvnSRlpOZnlMGxByLlAYg_EIpekLHoE7yG_L9bTkjS
uYNBRbdhaYsTKRnbsHcGGhnbIO7Kn8rkdHjgcotUYRPkiOzx5-lihSGrapykfb7GdnNpLImdKmSgjKt4qRrKpTCrYLzFP0LyY0zF8gCQ01-K6X3wYGvOw4ik
at_5b096FHW5A5rASvd9WffehaK0G9r_fhdCZ3gLFBJg0500c26LIds9NKP7Xic7lWjgWsMER7X6ozpol-X4vP7XNyjQyEVtP5RneUSmWP7lbCuyy5IbrCk7
p0A5kTjOloSnRLORo_SSvTdaC6hZ47Va9Bjs6DfX1L1o0Ai8xNK3O5rxuJhWY44Tk57leo7qlW2QtjS0us_s2CHlzWYutkN0UJaEFbdiUBgAUZpPrDxA6bAy
aGMGZ2zdD7nnlfQjZ_cNRAcoksHPtRfk_Lu15dekx7Z3EsF3uhvWsEtskcBuwtTbtU_AwysSadYycVy5
}

