sprite $Communications_Manager [73x55/16z] {
vTTRUlCg38LXG4BI4lEVxpOWRoSrpldkVzsxmFUidjkShNtFSk_uzvgD3c3V07gfTxZaRnJkfIt4-LkC7aB9WQgyfVA-oNh8Ic2OlWTQXWXH6GYStfGXysg4
fcevlQl6vRkGM7eRtOR0duTuXXWHsXx-R176rJqqVHZgxaFwTQX6o5NUPJDK8pG9RjabtDBQHKZge8w3QxqWk14h94AJMZwOYc55nUauLkFoVGWbxOehL5PS
8McNTHKIG7WIc88gdv50NUELQgwha2XsAWhYVCQ2csCMdGZftf533r4w6Q4pTMzRILViChGwt4F-VSZyHw4jyukGOG-PwdYJgcfFGtuaggYfeKVQncrGpcIc
jWFLKkZliuNiVvGvEh6eav8IsG78j93lGYaLxLFc99zpnl19HgZm0lMGy33lI6z4gC-vLNheuYkxX-vFapNVGpMlGfHELg6iRNAOwNWjbucUX3YEvHYqlslO
M7-7oGAwgn1W7RnnV8Y2Oz2I2E59gEltEH7so162CRyScZCavWJ7sdN8ZnaN8NqXT5n7kmmH6O9VXWAOsX--mL1IbgUB9is9sWa0wyhukdXX4VfNIq4uGfId
ULXyqnw5D4vEnLlmnTVyTIWwX-pBHT5vSr50wCiOxMceWSVVDA6TK9yJFlYi7OYEEaYOwvz7UcXovdO9xU1vIHUddp1TQVyW-rKdsuywF_il-py
}

