sprite $Contact_Center_Express [73x55/16z] {
pTM9hjmW38LX6o_OyFxlMmZE34eh4ecqlNzxT-RJcHtHwdw6tIdxLUkEUzQTihlNxXZXNcHUQeCORmAyYG_8A65Q1G1f6P85HCjZ081BY4veMO9UeaNF88GU
Fe2SRmRTJs8Vq2A2C-95zr1VsnKYleU4ryMSHHBGkWwnBFknaCegFQ2RCm6jamDQzXoIDo1bPjs5hgsXhBlbW3vfdb99Y4WwVY14J1m7hgUzDAXE4CjqZ029
4c3_dI0a8WIQ9E4SMQcNHMawoUDx0TIi239ipf4of8zJheiI04eSH1mcDOC3KC3JGJWXy_9PnFEh8O_XyJMhQ4Q8eI8nTtxLbEwqt3B2N9zY368v_YbWV1i_
NyvxFHQLto4p8r0xojQWbErRrWHpoSUYOYP4tF_7LRDMNnGNonan81twvwgnjBJFwP2RZVz6ZHz7NO3ERyHIp9l4133UgRimd0QT505dz_wpPqJrLaSQnkOj
1He7tJC3UPtgYyvCncMz9yTjrSytDHrNMB6XdxBEo0HT4mHC2DGtPW9CgT7-xGjS5rtBGiHgOwmoaNGpYajV5grJ3Ut2NBg5CWBa1VCSWWujbUWX5CoYKfQZ
BA0BiWB_B1e2MDqf5ZW2UDtgJQXyRkooEITzNtJsqe2qxiRGetTkQq2l-sbSiVqOgBwIazTtAlL1Lj_9q5vo4EqTvnS
}

