sprite $Content_Switch [56x75/16z] {
lTS9ikCe381X8T3g-zztY435KB5JZMVvkzzcypasP0LewjTHhWqwItKYMp1tEyZz0xL_aue7LUam69QZK7oSBDu7WFUruUgZAtXR_UcWzzErUbU1J_MkziCX
HFZ3KOjgRQiAixLnZQ3D8HJ478RfC0rY0TpTg49Ki17HeEKpgDT9X1Jjhi6-4zUlDK_wpb59zkKIjirn3dnoUIw5HhmvhjjvydBSSi_kPWI0uogu5uwZO0XG
UJITf2lrOtD_3PViiuju9Ck59UQ4ecezLLc78fhZqct5C3AV6KEloTPoEspcAqxsw19EbhLacGwdCcAP9SjKPZpPtnrXKydjUpQtKw4uQhgUL82c8_Ciqn41
89kdCrN2cEj8_Tjnr1qK3XPE6i2gVJi6M5LBr-34GKsdTEAQfJEJkBw7wSo5i0z7yMkvk4cosPSR6oy1e33JHOBfz8R594gyCgpRcwbblgUvOg5c2LVITiPn
Sfva_R8pBb-FXu0JhTnj_dCpbm80dD1D4HRSyfc9-M3ahXRfTMbiwUDquTqZ9RjwL4gxUWcboBqpW3g6H0HGhmLR0Rft3BrawHRizDvHijqjY7x7l3uxWSXk
NNawpsGW3zFImyO-rkRZt3rSmvA7_4gmaPXV4UVx2SerLcvuwzotjOIHtOvuJl9YJwDyAZaepxJOTPxaMPv6rLyvJ_PFytpfEqm1y8LpAY3dJ92K_9XPbUjL
_W-8ds6gbjSeVqYyZVVeqd6ywwO_XMPM2tlyGd0qevQ3tVwtUokZleE2vF86UaNGDz00wYkN7m7-GVgIDJys-K7y5GDeweTfPty1
}

