sprite $CSR1000v [55x55/16z] {
ZTM9OlGg20LWHLc4zt_V6n8T78Vq_gUxpISdfaj90br4pQCY7Sg_1EWXwdaemVyYDpgOiBVMEX8FTGb_etlp3b1N0Fez_Wz8Qie8lq5MKteV9O4EA2y3ks_O
u2sDXcdFrC0AxJsOkEu5gp-oDAqzHG_NzL9UFN4kQYcbzTE1DyHUxy_nAowUT4Jl2S741k7kMk35xXKQ9Xz5_hZkJDVscNLZ_W0fAWgXXwOhfIv4E5irmYia
dvfYoZI3gphIJFjUOA-vpfxeTFrGTJ8ICuXXAznMfolyA40eG3Ei9lFmEOBhXjdpg8i3yChp4CXC3kMfnCnzAcOYNX4rUZf62Djym1JgY9f4nzCYCvugMdRx
PIAVoa2ohIzcNIucHrXMa9BrYr76thEOQCuO-I-cbZA6qcQjySPqdBbKkTmW02IdNt5ZZvFrEcIgqcLmkL9l6vUuclcCOOTJhS-SqjUe4rAbfOPdCLneAWtj
juYbqgO6VgdjMh4jUfDGWpx_K7p_YAGCnupKwOPzXRfj6SzLRT-djiHrs8VpF3UsbLROC5pi9XR1SZeYirydfP15sgC0ziN4KIcW-sm0P5ahXyElavDW8LHu
v-wQHiShOBzXkBz3c-kn2HIFv9sYLoI6nTtjTxo2md4InuyI9UkHIlccPqqkH-IdOb9Ju6J0BrLwEAgxE8uc-PyVkoNXKAaRDMUXSfTEWn7g2CWp3c4RMFtp
scITLHPw1kfWc8ZryoTEAICnS8siW2DxB3dy7Ebcz40Pf2d3K88osI-gBYxIK_CV
}

