sprite $CUBE [73x55/16z] {
xSw7ggL048JXgWuJt_zzLzjuTjoB5sL9voD9K_CZMVfpXKkdFJINobJ9fazOdbAbzvQ8PvXQdpfL-9JKkLHU29N-RkYnjqCgJ-aICdtA8bHV2DKbzDX_2IdL
Bb1_6o9uytg4_F85m3lNu6jef2H8lN4DHsXaj1lNEo7OpUiHIkvg_YaPRBhVk9fEzoqaqFGfdWokhWhnt2Ba0iYPseyXKpa3fFHPSm32W0a9qFyPSW7MOH20
QoWxOUiEvYcvWWBB8uCIEayC-vleH2WdYLU9z1oSk0mvS4oOegsrRw59t1H-Ud4TEayqprfVjP8NYP9t0hyCdITCEPVMZz3AOMLdy38O9pKIGyZFJyRGEAdz
HYYLKOAT9xbVXZAqx1IvZ39F4qFz3DMo4gJrkwOzMikP7fDCxN-5DWcIQyXpSvAjr4Mn78UO14Nfd-hEGI-r5YVyI1_bOnA7FeHsJb2403GOm3G72RW601Gb
cFiOEXGNdXW0Z_y0J1XaPgdr7qA379sbb6jehRSZSZl4j7_bEWP6RL97fTHLgxN_JeleMN_kw-khlDLXUQb3bdSwVm
}

