sprite $Database_Relational [55x55/16z] {
rTQB4gmW281X40J4zt_VWzMiZcqvTUx_x5pfK_SUWDMd6RnHuKAv5trISQ-nbnlZaqYzHYNKCrSQq_GqVSTaOtGkzUZKmMQ1YD13nDdgnhX7XvWBIlnfOcat
RVdKJtkiXEax8zm9dwE48nnPQWDYpfmdb3-Bfe5PReL2pdSnDfUZ3nC2I5bkcRIbIJvC8WJCiWm19RA1iQnZm3mnadNKTtjmo8m3ApiBjrOZKzLW4ObU9mGH
jalAm2WafYpVJTx6D355oCB79sYY8fos2Odip4UcAjm_oyGjwfza3X1CrKeTcQcPxYjFOGfZ0O8TAfYPRInSoA3IjjaZPf40raORy-eZ4vjIjRbW9SJ4vdu7
Suk2bHKgRYChfMpiDYl5wrTcvUxXSUdZtG8zOHqTpDUieyVCErgncSoiomJY8-ZYceLBe7NHUwOJgmnSrp7Gj3q2-m9vFj_5203PhJ82a3gd2C3g5yQD0R2h
Nea19DPodcXECUDoSOpX9yzAorJoyNF7LYzpFVzoJMUuaaLb_tsCKYAMYInug_xNsJi5zagzl3F_0G
}

