sprite $Decoder_1 [73x55/16z] {
pTO7OXmX38LXFKQ09Ev_tqG3SiQTalPlRv-V-mBIpXEuO-SrSKUrbfEggZNV8nVEkaIjDLF6QNn3al2cj7YE91qQWP3s6j3r0krAru1w812khJga7502fIs7
jKDt5u4JWRTwGg2B-GpA7SAj9Tue3yXBXFuJm7anVy430e78JvoNUq9COCSJfJC8iOIm3nM7ulM9k2mxPK2b-0qlhYqMq6a1rMEd1lJpS1zBtJjKwr1KKgvR
wLk8m3kEs3k827dBSSWUa4kyvJWaSKzsg8_o--REH2qMoIWWIbNcC_iCGbvole3AFAClpXi8Bl6g4uiqxivSaq-gEiU44vCq4jLoJzA9WdakUYHzqeOJYwBi
a_8Sq_pOdNUBLE2JHBzkJ7393x5eTPB51nzCYqNl9wKlbTOgxbXYL2nwDwbyhlYBAd6jXO7gm93CcvXaBpbKnhjYxKORcNiXChbqlOcZCY2lK0uWpX-t5VHL
wG4fhiUWT_4qPF1RdwRuJP2L_4Mr_OA4k1qL45Fz7P0LIdOAZJUAsiwIv76rTffvxVzEVfS3-KqEGZfrVW
}

