sprite $Decoder_2 [73x55/16z] {
tSzPbkmu24LHG601clzy2mkxb7scHNoz4ttZlQuGTTHJF1slD_HqpFfHgPlv2CULi1PfICEDust9GPwGKZqjGG0lW-0zr3QT1RK9MTkA82nicKs8jo04QW1j
nXUqKmDa9Y2U9IGSoJD7mf3K8hcWZHY08e0cKG4YkA8YXC3Ni1h4GFUojg1ZvsGiPqUAnmKzxxmuopSBAfPGBplzXlfMnthh2UqnJFtE2f0G_0-fxqCC0BIS
2VdMd0YNav1kp5cGse8UTk0DQMI-3Mbl2t8lGCetP5w2EfuCGZT_1va-omGYwMA-6Y7PmvJ28PtCUBVeOJd8BcRaBVAjGPR0TTjQT40aOo7l5lMP_IKA1yz1
yxuazvnxHcA_rdFGxQp7c12YY312inzpTyv1iwJME7T3iXmcFoe-30FYY_cS8_cPtk0NjRZ57IBx32meZzdcdmn-hFdukWKD0VqTql4QYFnto6aUpOyV4Xk_
Gmhaer92hWHz525ep0HmZ5hUw4nibFDe_5lfgnpK5pcOKjtv3m
}

