sprite $Doctor [46x53/16z] {
ZTDfUkD028HXgg0NcllVT_H8s25oovdlLsA_HcYJZq1LCrL2dghMCjM_FFL097WTWD_n8L2Fmk-OEEM6Rt7fAuUQ4dUkU1vzxtcucdB3TOjXUsrukdgRjgje
RmzQMs-tyHRXjkDsw1N-cy-bj8U85grYh2dFMh36Rpq4Jne2dtSjkiSgMyszvbv3jwDndLPjEaJuC5eONMejJBQRgnprKBbTGfnyXtakKiiRmCyrH4ReJMCk
pLVYdI87TRd7jVXwUyy8EREOa8zqEIK3v9KjXsooYuDNGFbmorVhtTtNaRltpXPFMD1MnAf5E1uiIPqHrSPG4djB20uURnj3m0s7aW14MfIMYk3JWuc5Q_tW
2H5KNZ6kD_GersaYbLUSsefcwXFiiF17Jtbfa9eySMgPyT9DAkTxTDKMSUfOJ5rtKPwzDJskflpMcgDrkFUt7wdjPPb19EztH2UHgvpb5M7f_E_wsZKrl2vI
EQg6I5d5vAfg7kavREJeNCKfdyELH-QnohFPpny_ONA6aKpELHRXfd7gz2F6wvq1TraCPkWnu36UCTMZlm_Za16MTfkj6APKc-46KSSZpiiIxXu79W43lwPz
-lBPbV-Pwb_q7m
}

