sprite $Dual_Mode_Access_Point [73x55/16z] {
xPT7WjuW34PH1PdxtpTgVqjFy7A-XULdqBEOFW1hdsT1UAxpxEKUywoJc6VxF6Q2S18KiskxIE0qKYA4qs2A5fvdfOZmDDIYuzmiCgRJi9NeF2KIzWZt5G6G
do4dwcK9nk8ErhA4Q9j4IY04mmFiE80OHmGbX43oPF9LP8944kc9FEJTqJeYTG_UqOYDJ-uTZTGY5M5tXCq3bCMHiuSWYuZWYu4RAH2qHSemI3snnbb0z545
6YKyLKYVbTz5v3jQXBr5l49rS8ku7jUkDdXeS8kwitQIbW4BtoPHwCv-3i-tIugszI6eJj_2GGmjm43aBEHSsoWmDwFsH5EdmCW0v-S6iD5lNK-DWueVYBa4
ghD5Rj8qWIiH07iA42K0O5KgZpPpUJGsayuvwsWpei8icdSQ5oPaRKfchjLQ9YJfpPvrxPheCCjsJNIQyhJetBDj_UK1VaxBt76LwEyoVqvMcX8TnBQdN7Rk
EPx8dfxwGlflJxHtKlI_sVkdehNCCuL8Lc3mKYAUjPmNPMBrcnh7b9q-HPCHlKLXU70k0l0hZuY444bjKRCYW5u6GJ3VHIv07E0bu_V403GgGlcpchdPqHyn
5i5wYUR0wTV-KHP56tbI3M4rNZ7QtfgEGDgLR57pI0nQ9P2zmmjMiULYykebJjFL2ryFaTOESpjRZJBBe87nvaVTEGfxSSGhwtf-aDR8JiqZrJkvSBQNwpLm
bG5iRohVPeTdsDT4O7XfuH0Df1HuMBF8tiaqfJ_CCvuzOpWoD0681d4Xoa26eJegwYmu50e5WNspxRTOjh9j4qInAn5jJqIQUolq5yoau0MfzIv4lVPdRCvt
zL9zPrjp5LwrMTJnxdpbA-ik3woRFBVzb_qD
}

