sprite $Encoder_2 [73x55/16z] {
xTK7hXin38HXZgX2IlU_RyJDh1lWXIqP_VtP3k33f0CszZE4q_SR5evxgpirzpx2CSLUQbEQKCPkUa2cQIN4mTJM8OW817Y2LWe4c5YAjmqe2UZT85-44fV5
dRzhEv36f4ne9PN4Et8cLDOWlKE5q4eJuXsb_09AejiG1-LTAF5FKo4ql2uuLIL2oiVR_qLr9O9y8xGTeRRjj1DgAyVZ2w6bQjR6mfcjGIL9QinwNrwK8OAx
C_hQeffa1Ze-2DbyuRVFhZ67qDq9wCigX52y-OX2wlPjJU-G4vd7zv3b4_9-xbbRX6205iwTwcuFEG_UNXyZBp8hhVXuAA37Z0Tlhu-HfHXaCOUTYxwBWrxc
B42cCSZ7DbIFGUC2QityWzuCcfsJ8UK3fu63taBb-Asuhe-HtmoAUlTPIbdgfJAPuJ4eZulQLA3dRypRaiJmAqZXnnavv2gzSXmvLfLFeCj1HIm0T4AhWpea
pI3jU8l_IXz-F1z-_KkjHw9ZBuNVxnkP52xZmsfLEQHh7Y_zPRzoO3zoG6dR-GS
}

