sprite $Encoder_1 [73x55/16z] {
tT5TpjmW38LX6uEnOV_xRJYXHVrGcGJcgk_yvExHaSDizJpZvfJpgi7nh2TblwJccF1POfTqGSAdYJV8mZ4K392440WnXwsaGoAX8TmesMb00W7UFkG3ah09
EQ0u866IZMA7OhoWY2ueRdH3wMyelNTIXrAAn0arw7q3IXqIF7SX1NGoI3kacl3M0b-URWIe0c9giUXMOv7sYNe25Jsl0Ch7JkxGdpHlTKDrG2gRajSV497i
E5PcY5Ztd0d2gBVENR6Cp1eqHjd7BpvmoWtT0K8Xs-FWe1bABvqPIeHUEDwT2M9SUyC1v7Rdch9S46T_pm3wdRdZJD4VDPm13IjWqajcXlgaz9c1iuACsoHx
oo2V9-aJnhsi84mA3yOuawuWJvYqL90IoSyh8IzZ4icCG1aLbaXMvm0YJ99_fXLboaQnhdAcLLAHSAc1or9A3o2ZrCwawqaFe4ZUjeUwJDEYV9-QmXMHrREK
154ySmfpmHFdFYZtA-FS9wcKFarI_U-pRpbiNt9uI6VEBm
}

