sprite $Fabric_Interconnect [55x55/16z] {
dTO7kgKW38PX8ScVjl_z3YhYmrmyxJkzlFQsRPRVPjkkujlI3kNwJTxShepADv4sb-5DVUTyPre_gjIHVi6sRK0SZ3vgQvLAUs_PDBO3teoPwU6-pNMedJrM
Leux4vuI7kqBej_7oBWpUOw5-vtBYQHrC9CfhYIh6giiicRxPArPxMWmNCav9GIvkd-2t6zji85QfTJhnbWqCUbewWLpd57vXId09wmywZyjcOuWjJ7MEGXq
oWSRDIWw9riLBDWSy8Tj3UfTTBO8Cg9h2pwpo4TcijpqkseitHQjs5PXPZk9R7J9K4Ub8z5JnVzCRHKEXFr7ZspDJ9cU6C7sFCzsV31lg0tI_AzoDEHZL8Ev
ku6EAL4R-QY_xoe6wwXLHdIxWQR2biSrUqPzRBeui5LRevkwkye12nIwtnLwcuRMh6LIsoZy_sAWDMiGjRuW8VWZprmzph_FmXYHKIdIXJq_JLX8Kv0WC3vc
okaitF8Wdtx9iDJ8TQmPKWeo8NddoWfMXgsPawS2baQHTweMRc66zOfD9KLBgScySj5KRtTdNJ0fJ4NGui9Sa5VcKT3kkLAfOgZOawhAbZs7faUxkrWk4uG2
6Y9v5-WJ-SJ0cKRa6QIP7qva1dbJfPAdK-ILC_f4yj810JA14gOjKm5J681S9KmIAPAnlyjHc9YAYyQIkNgUctBw_1VFyFIrwhdddUKlsMO_gH-lpFy1
}

