sprite $Fibre_Channel_Director_MDS_9000 [55x80/16z] {
tT69Skig381XBI2qlF_xNbd47DCcCoMptpyxvaEU5a0ypd8100i_BGGabUcGFp_KBfTO6Kzgvc7XbkhK9HlqDWH0UfzUJEXjaE5dveFVbAeSlsjdz6HO2kcn
HEyOpSCRtzNF_HnwC6rN37HTGcwlBjRk2309lXOsLky8jBFdAjqi5cl0hottmCKeKOMlJolMAwJwcBlooyLg0P5xrO1xzMGChSyOiIt6GF_M-yQsSLcZTCbo
WMh237bZCclGv5NEu68vL-u8kyms9aIoQeZrtywT-wcBsPg1xUa0WULVIFAU2MENLSyUYb5-i74dH3BgyIX_PXtRMEqi7VByVBOkV6Agrw6QQcSwY1vAlPXc
qlCjNKD9jgVAkNersiXtNqomwOnHVh6MQZBad9KLImMy_Q6t-kCYS8geQPTwrcMFu5dpSBUKsk20eOQ79LNb_4Kpnb-CWNXUusJY4Sd2rT8rdGtY8Nkvf5Vc
JY099ZDBrwpIQyiFPGERMQ9mdiejt6lxcAgHcktZSa5Gp6DkZ-mrRTNnuhghMhTuv3iRs6tEtfLxOr_cvpIbPjKQE59vtHxrZzCQgQs4YDKyKQMe3_TaWkEX
403OOYNa6qjO6NMRkRjW0o2cVywvR-pDSTvpC43pHXftIlg66UbIJ1eNYn2KTLZdZVrSL6AFOlE7RGVlp4dN3NQFczNeSP_SVZ4bdvzSVh5CiDbZpyQarSzM
etOMnYI-xcXZlOLR9zQ8dLM3IEmTCsAcjb0nZfKFfdpupZ8RQh4I9W1aVYoPQgcTxJd3bSJUHxPSIpNYbALBTSx2DJupZozoa_Wc0VjA0OYTbkhxw3J8nFmq
4n2FOnOX5YwDZ-ffmfLE4uzaV5enQwUDOlqqBIQdNIpEcILp7pgoFx-hUJ4zoSmZMReZut4pC_t3myfa7fNR7tA_ZK_fL_RHUXKVgvEsmZ_l_3_dtodvoWcK
ErR_0G
}

