sprite $Fibre_Channel_Fabric_Switch [55x80/16z] {
vTBfWhCg381XI4BM-x_VGt0gEiKpfN-_rrrukbeAU-pbNBeAtoo2XpALprFha3rSiUv4sasuKTsBp3jJ-AWAPngToMUib1FAOFX9dIN4J3kB_sCmAwDwCYL2
GgJ5WhNS6v1UxB6o2FvcTJRVRB96OpVMyonti-60ieErMmJO5YK3QgF9hgDBrY3HcYMQRDbaV9HeL6V4g-p24hr5pynukXqcFxqWqXdBgZjB29sHt6ljYSqQ
l34gq1xPX2otb4gvGVN1L2xBI5HvFbnOiaeoHb8TR5KhjoRiofyPbVU0X-ezCeQpEj6XF9dh7xL4E91vP3ScY0-iecYMwCOIbG9BnYGwt-h664iFH9-poAwC
eHpLCyo9ryNZ5rl_s6gN9fhCbEgAhT5aPje6h7AcpsYoX50AsEpPJ9OfmvsvNusJN5dcFNCtFUVVX11x6BG89RB9VcmyHAsX1Aat5DHVZDeJ4mh5beiR-cGk
6bh1GiKNp572gO944CTaLi3ptQpM5Gj5Ss7MO8eBSm8EucX02sGvNRWddT--cmBMYcYnY2fYRSamp-Haua6bn-7wpfILWJC2rUOlHWMf9gk4fSLxJcB2h4vy
-MwAef2Cb54NhBK80V9mrCboJybQB5Fq40Ga2wKB2sseY0AiAzR4YOnKK9nqCg_Led5eXHKZGeuW2ID2cSoWXIE54_g2cNg4LHgdlvvVgp39gcxFdEELQ7mS
b-bsL2dikwNwEjWj4Vj-unVPLk7iOKou4pMBBXLsa-WfxdOmskrWRJTDPhpRmMGh5h5TbgbvCjUj4cM-QxQOcRd7pEs3_2JJ-GPOvRcCyknVpRzJ_9qgxD-e
_m
}

