sprite $Firewall [73x55/16z] {
xTS5SiD038NXHJr9zpzmhLPXPRBkXfC_OFu6p2b3vqE-YYCcGOMPCHCpYqALkPSyKw45MgAIPglTe9RcgmPHoM4fvT4A3E9Qmb8gerM-4jGSYbkWEfX3xHnK
hmFbzL2OGMsi7HGs3hN-1_LpKBixH0w56TJ7QYG6zJ9_PDFYIBdQITjML59fGJ18Q4KrLGeIWtWUmhKW_eK4in1a0m4WUBGP14D2IyrNt_u8uj1kDTgD14C2
33hMmJjeC8TskJCFkUCGrHNbbEjnhLQwwdsDAIwdJfU2nmO9Xw5ay8LacqDX5o6Hgq0YLu540aZEGZBeE1ItG2m3lI0a_u1q2D9uIksh5hNfEssxxdqDLxWT
GTT6YJJgmw4lX7KGAZGC6QfFydRipWy
}

