sprite $H [73x59/16z] {
xTW74fqw38LXa6JPqZdxN-ypBudJp1sKtdx0dlgDRY_7uOclBVsO3hv5_iZX4obnbLyJhXApZ5SD4-tngWImdFjitf4oubNF83bc3qPwDD4vlW7KvJWzIb3k
Yn6vxmPAWAM0t440qRrGWCZFeGI7YkYdsLqg3k9p24nHQxly9l4zv69cAhBIwxZ99jGKoCyXc9h9kPBpW-J_uyDqIXfRIDLK7dVQAqWAwIyErU-ZVr0XMr3Y
Ao1hlY1y1MJk2yeDL1XdGOaDzAp9B6WvHMWnQo8Ke0sp81IW3RCW0dMeJUOnr5xa_XmgA4LeAKMenDGdybQ6p9fjHwf3ts8Yq-90Bhc3w69MkhlDy6cP2SBa
ckanPHBSVY4dN2fP4Fk8ZESbYDjO2KyYrp9xkwwjK2Q11C7iFK4C3n3X0pN9d81r4gecWIOcdJxNXYf4w8I60kefmQxGpY6raQnbXame0o430ReYaCsA4vqY
SdI27291ObmixFGYr83KJW98Cy2busfC5VNx2703NT4qoTHWogX2c91xY3NfUPgt3XCtmnvAR8lajKGWt0VGPm5CEMySV_NCdgrbRPNVw_Ny-6R_HFm7
}

