sprite $Handheld [55x73/16z] {
xTT5iaCn34JHbgfSWjx_UZypkbyuyPqVuqX0KYq155kDXMJhyGyL7h-xtvd31IRifhOxgvc-i1fkC_ce3omCircyiJJCP_dA1fJ61RF5UArtuqENmIWoNWwZ
p7ZStKxE5bjiiSK2Il7AsWNbpTVAvrNnlOxXCureNaDTJRrqyzJtyjS_aYe3O7M4tOIxYI-Pt5AYg5VOE7VV0m
}

