sprite $HDTV [72x55/16z] {
xTO5ZiKm38JXAed7WVkVTvbSSENiB3pu2y9-AYU3Kn-lrS_Qyt9M_rYDqsKt2CvItpaF0jawESsLOPqqM-uS9v6S_1VEtSdNufH_ximcmpXbJYcY34S0WbE0
xpkb2FQSQ08G73aSBoA80FEELNp7tOj1t76mUFld7MKyfOpBZF4zC4z0W8WxW33cBRxYEpR2-HXanh6IKCv7mkTp2SyBdEVrND0PLP-MRUrpXdyqoVzq67Nr
6YRrMfoIETkUbhciqmaEztpkvvFKvhvg3giZa9f37m4
}

