sprite $Home_Office [66x69/16z] {
tTH7ckCW54LXlOnW__jjem97n3NjZdKOaVwF4Tie2je-Yj8E20piwuJ44NLWdR1Sswa34m895PWGMAX0BmMj2vBodJ0Wa93t_20afrKXFmc0W08Yi808B202
2uZ0mWf1QIPK0WDJ8Hb100YL000ImWW0KAZ41812H2Smi4vOpU-pONf9jlC8jVL-ey1QOtgkhsD1eoRqdBJrloye4GAu2VoSVWdyhg0V2E8rORRxvBgEXPvu
t2NSMn7SUlwpWigHHjhzckau7WbovBbaN2b1JP0sj0cQYpDEzXA7mDAw2du1z2LxJZcN9lIw4Ba2F4_DnQS2ezJL1e9sGHXcOw7s_mZosmKLc0y5k_IcO6U2
cYKiY9gV2BM0WfhxJ4XLc6NcPq9u3GXMknT8hjbNCHFCdeHHLWMR10Mz2FOjX5kcdmcc7x_19eAV2az_zOcWl9y9b8inJbA9xIJD9U-mN8AsiqZjeT8Akqyx
WAFS1Dv0lq4WZQFIYgCLHykeJEyBKOOj29n7G6pNVW
}

