sprite $Hospital [66x67/16z] {
xPI5OWGX34IBXypy__Ssd57lXihfEvcilJN8qniwDX6V9fiC3mCv_rSCX9GKOsdWce5Q3gkJSCL0dJi6eTz0P5iHHMINdNv36okogjPH5BWDun92s1b2i5Bf
DD1s2o8wsDs8U0tGO0OzO8RcDV3dXd4NLOP35ky2vTMxYF0Rv9MX4Xx3l8XOQyqZuJFCGNaWTYxDBDImNrsKYxERsaefjOC_w32S3UP3Gtp3rYutmM_pu06r
v9mhY9eD9MMaSBkX7rjG74KdPqVv5ExuWO5I3E6wOUxoMuPmC2JBu3SOOdJBBWP87QaU0mTlat0O_B0tenFhS8TZtvaB1ZLcyNhr5gWnX9105Cien82imQZS
P9Y3nH2-UXVNOi0lN4EACMOG9HhzQ6ZHQCJFMHzHe85BWvhJZjxtcPNu2BPaD7xSi0SYXwBJqndyXeS1tG3M3I1e_CGm-Nr3U6q8RWDa3qx5HiCp
}

