sprite $Imaging_Device_1 [78x74/16z] {
rTZHUWGP40LW1QNKUV_ttHL9ekVefMUkzjn6VYZqPy8-4hEQOyHDiuHt8r4RNk9MubjM6PJFGOyz7g6e_qa4jYAFndMr66pv68j65dicPrXXYmFuoV2aihNc
e7lCPipgI-pYLTbWRSPQfBzVEPCjDaNBIxGvSPjfdWUezrebRC_f7LO8E-7I6ek4dGGkwqMxnT2pMRgpUU8xB5grsxcAOssvQKun5RMhLoL8_MhJX3G5LfOL
cQ-yoUixEurM-MHeGCl2LzMaHUV1yQhnEUGDNlf_hNU9j0LM_lkEqQ8-0WkN982nunC3o4iDjaU69yizhoVQU6NN5QEfYiZleMhDgchfoV4lDoNZuoMfPoo5
QKcn9tqbvpAI96ng1iI1ZVyrzwOfZioK_fkkyU1uuII9Z95OAr54I2jBJMYg_UZ7-ADfZNAk1NlLMjzcygiLUQ8fbU6gvKTQfeNhCtrtR96qQnLg_5IRTqWh
yLEjSps6P_ij9DP6HEIxfrPBdWv3DtlAGYjq6EGl3lVVWrfLjQGvh5NQRnVwDJv7m_QW6goSnMtx8OSYXREORIUAZFok5a5QV7ziHdTl4sW-IxFTrn8QHYsv
g5nNfNdorIiY1fMlnCKZo9Fyv88vd2SwQgE_LUALRJ5macFzjPorY4KZq7jAbDiv82zQCC2vcIMPhTm0fw26Lwqksm5DeqYN96d3kb6yrTY3DpERNwkyQgoj
kG4IHTzvrk3F0-ImqgeHT_oQOKt5yHnhSgFHRRyFF8OxZS_p-Rk8DURs5RZNdd6uOAprP1nww6ksqq9iUuxVpQnDBm9iBQY4lTQJwNYJrKOnjnh_ZCIM5mbx
xTN3zaUflJOYsJ0oGO3NHDPU6s1jcEAcJDrh796OY_QK54bwed7-jveOQloEeSfdMCCb9XzfZalQ9ze_
}

