sprite $Imaging_Device_2 [57x77/16z] {
jPU93YCX34Cd4K4X_l_ltPizna0jf7LlgYVYYKdLPwf1KNj8WVeiT0RxVmKh6SnID1WS9SdUd9KclmIv7uvBi14ezYDkmKH96XVjfos9qqZcT3A8qrhYnG8m
N_Vn6I2iihdPO-QHnL_dkb1KsDzXZCAgM6Fpzivnd-JeOtQJipQjBmBPltTWRfcWAhQapqk9V5zIn0gRhVO_rZpm3pUUdGR-AhKG2IvqNsn6pevGzhUYfcsZ
Vpvua2uDdmJeO9p0VhjZ2Xw5GNqQl6FHnpxUwfHfv28vXRVgUMoyTd0QACvUu3IMdFeQGI0l8layeWZaDRJ5oC421C_prPOatf0wUm0v9tuiYnTHJh-D6jWu
-5mfho8e-HA8lZvis83O7TbM440inhKdjfNETQGlPqFX2A9sayLwOGkYkZrR-M57VmwoYwd26Q9WgoEGPiFT24IA5bbsOP5DiiKhata4yz8YoaIBkidu08Pc
KJTfXJkJZZeBVc6HJ9B52vFr4Ip5ecwo2M0J4gxdV0XWtLbaasnHDtd_Ttv8u62B9O5mjgYfJU0h
}

