sprite $Immersive_Telepresence_Endpoint [111x55/16z] {
xPW7OkmW30MfGXBtl-_71csUxR1E9RzD6aic7XUopRd8TGqSNQlLTSIzfihqtR3grkDManpyTnEojDvMq-HNa5LhGqjO0sCkVkzdeunSNCCFvT8Q-4Tol3YN
rx0u9p-Hgor7T-hd1Skf454ERax8No4GvD2z4edYvuJmoDKjvstUsmZ7_Yi4alh8kKvYLGfcg78wRIqseO0WRnJS8wSlkTGd_ExstwPnAZmA0OHyo4K5WRjW
EJqTdHyJ-osgreQjoHk5uXfv2E6OqrAw76j7NKDh9zhHcM09gPq4kO027uGYvrm2sIl8uPcG8HVh8FJz0K6rJevE7CWHSlETB-L6aAgr1vMvRytZfScMXfpZ
gw3UScSXeT1JbiDrnVvbNMdikOA2z1l5zXro0GK2GQk-v8Ri0gdaCVPPx7ym70Iw2hw0e2Qu9fG8Y_wSywGStI29vh4D52I1G6xas19dmLzpKiOasz7RjQ5J
xYAKyOUMAxOMxUBn9IUMetuR5rawv38A2lSgp06508ayoVKv4mXN9hEVt-rWJYPBzvXZRmTl2N-uLxaHB3Uvsvdao2O2t3zao17SQGGRqoQCNBR9YC8vf-nj
7TZ-P9GjXqAoSTcFJlPSiSaC0a-EJa4cb2qd8EIAPrOa70G2GO-vglte_AiviHmA18BwJT0zDnKmXwldAcyvrPkSrjiS4ZSvfi6s4cmS-ufCdnOGzcvEa1l1
Dq6U2boF23r8lK4Fz2JaLmLz8aYTmtQ7DqFk13NX3crGbxNnGQ7iGZHX2lc6w_X6kHFetG8It95q5kATa4v2V9RB9_cwy-yLSds6C2BV8Fof_8VNrkBIN7Hn
QMtnE-s_
}

