sprite $IP_IP_Gateway [73x55/16z] {
hTG7ahCu48RXhuCweF_-vrsG444i4yhpEBlX9PKDHFrSOEiidwknTJBTFk6PIzqw8VGPYRMqXeG-9IqKl2CG_ygvGbn30FYN05n3ChuyGtBUX9-tOQmZUqY4
2LSi1sPvO5mHona2ta94xw5X3wNsqKi8tuPOD7jerOUy4sqU8UtaUev8L4Ue4G2YTy9Cu2a_dAkCKD6E7o725Jr3h4tPGuDekL7U0RpHSgTIkXQgQUM5JcTS
omlhUsHl7Y5xyLseJA7ouv1A-KL8z3q4qf-6bF1L260xJLVDBWHuXDmBTuGLgVb-8roHkUq3xKjofzullxlYHimR4mRnGSp7zxZHh2yXxspwyO_Gl7of8sJN
dpMRVnTowqjA5skdXmO3eExVX_fE5Tz4rYx3FVhDmDRUDV48XNTjMKO9ZzRfUxJ4mTJZuXcwScsVimvBl34cW0viyPHr3dayEDC6U0rbBlUGAvFO8oGDZylZ
CJ5XiRo4dB4flmkbOICvGXcAXZpZSiivD8s3q9GpHEWqRvwXgsheE4V8iPCVXIApdMJ5Bh_V8sx0pGYrpAgWewnT9gEpp0pBzXoPJhWYtxzVgc_h1ZgfHyZE
8pEcs4B4biv3_plnTARs7yRijLP14sUebpZwzUjh0cfoQAV9TVpazp-XLl9wM9OHSiQ9pn3tq6sQjPyIgwSaR6HPKa6-CeA6Jw5S2iXZnT0yBblMW-ByodNP
Tb9zxK-7bhL6czPjMXETrc4XT5Pldg4Rcoz_3Una2Z4D82AUGe9Tp6dmCeLmDOMMOsgF4EKzrCyoxsIQ4dQbxWg6_mqDSmY3JXTj3ltxSUZpFNe_j7_J7WdB
QPhI8vGnrBkygtSnv14_r6uQV3jjsVet0l577I3-flCV
}

