sprite $IP_Phone [64x56/16z] {
hT69jh8w38PXaYz3f-sv_xizOkcYObbM-DyzgZo4jijd5FEXKl8nMKwJV2p5VCpdVKbCiLptET4IVlQbAyR-vPGlEVYuL4uyqUvB5cR6i5W6dYGz4shUM0Gr
4KXBpKG6yv7-MtiagZuhX4T13QaSFJrvBL7pu64O-PNN7dB1qzzAQ-c2nsFtV_Il_3YPzO9XUi-hJVjHQhUysbNVzBpNOsPtlDaDRut_jdxT-z6NbvVHV4MU
y94XBNqBblDNdqiG31FBPSAl5uqhPMB-jyxzOy4--ppflNI-q0Bvtd8wNoSqGAS-U2sSvMk6pil01-DXQFV7qg9mnHirZ_ZZyzUaUHtuYMpZvDUyS_KuzK94
uWuYDZScWlVXtEyNe6wK1bqVTUJbr9k8sEkFkhkkB_gaUhswVgtUF8ozWLdMESomzhBBclUo-_p-VBnTfkrbxwaUdvlluwrVFl1QE23xoovUjbiYDk_Yys7r
M2TmUDJftCtVvhNvRW3imqjTAYm6uqNVjvUihN-x7CS3t8I-rl9sUyCsLxQv2a0_3h0HKpN_BMk-TSc7UnwY5nCyzN8hH1TSJZp6VAiezxpy3m
}

