sprite $IP_Telephone_Router [55x55/16z] {
dTO7SYiX381X8THr__jcMA8DsBXClbU3-Itlk047I6gHGvWImZTGPXB3J0K_HZeskWfJxqGiwgDL_1I52I6sWaXYyJQKp536PwoHAN24bc6CPsoHTXf8aQ64
htI937gkCftxE-oPz5mP4tPw2P5jT8SAshM17dJ41e3qs66aCoF0w5hZ5OraG6Rs38IRPGWpjT4rs3EkVPsP9TAWI8OopsuWtdIuyA1nFt-OQNBXsP5ivhZ6
CbWcpampTClmKDMYHkhliAXXwuxIhnM0BfD5OWsR6EUq9dgxXf4ISAtCSPZfMeG9iQsPIWDILRxNvfCW6QOROTb_r8r5olMSROjdkeWqmDWoutwaI-WPIDUb
sUzlKpWZgpqZIz9CDzFxDvnr_zlZaMePRgMoXelAoiWi3bbJNz1OeZsBp5nNN9bPtRMOcp2BxTaG_aHQGNyogdCd_4kw7QjpA0nJ9pj59UAhBAgAKnXtXaiM
yRVPjf4HbUtJAYccMPPsdLR5HYbFbccU1uJnDiDZ5WYMk_0hQnEHkqK-C039s_MaSDDC8Hw86KC0aTNNLW0mRyIP3D0i5KiFhOSRosC4qEKdvldzc54olSrE
ioZ0FQvk7zKciAgoB-YngkycteOjumG6oaS2UuSmITrhtRnJQ8n_DmWKgsiuFaf7JKC0ZFcSbRdWxUa9gcxiHlJrpkyB2hKgJjphIhRkewh-qT7f5FH9qFdC
zPuX74c-8-_EasUV3wB_YDQpSZcVbVzvCly1
}

