sprite $IPS_IDS [73x55/16z] {
xTT7ckGW341X1K08t_--Wx3mkFb4JR2NzJhXmDzYMOZrU5v5SzhpZcgEgjP7gNR9d4pu8A9aKeSoFYsV43sl6bHVWvYUnWuzxcqeiPTkl-UI404GQTu9Nqm3
qhID4AwGqpxz2B4p0HL3UUE0DGv5X1-bx50O-zRpoiVZ7EPGoK7ft7TxHWQdq2aE1MKR8Fa5qrZPZ5J2zX2xCozukRc34Y_PCNX6TcL2N-0MEbHAeIKxsFtA
3vKs8yavaOYK-vV1vqQ_vZ6GlTP9bY2VQ6riI7B5m6MkWFu90e1okxpM2G03fvgpWT0sXmz2f-qX-Nj8XzDQV3Ivuho5tEcGILMMhoe8K7oP45AT9G2I-hC-
ZqzKbpf0SEwMqbT0UKP-SQk8ATODMl-pYJsacQa_Oqwj6pj8022FHKORpkEEIhsdhGqaWDOjaYwem4Hd9s8ZEHIEHEBh-HUNWVHqPaqZAGz9RQdJiLitHe_P
XABiS82bNjVP79FKQqS0rVNR9Q0iut3969TYng0uEvs5FL-uv4m4nGd3xp29d1Bh4QVx914EXRBOfKjj3-shqglpWZv9hUbVrVfsNQIGsuFD46jAgA4Hgzwn
P1BAyK9AM8zNKdVUxzkt-fQ3zINdjK_Plm
}

