sprite $Ironport [73x55/16z] {
xT85bYGX381XaX23-zzt8T12sKZrssVpjqk-CW2iti-WE-L-rRhZxdOdToyr74Qu4tAN6iHmDnuGmjqm8CFxMK24TwC9tUx3a6UwM_O9vTFU_ttUXFWCGLZ3
CumxL9sFoZX6MtF7vXTybDSJA1_F19P_0170KBxxqu1a_sTY5ZvAvgzhCg5D32HN4R2idK0Pv3h8nv3A6dq9aQpfX3PHodeL9TAr4oWde2i7Kluc11cGzJX6
oB25h2nGvWUa4ijbh_IlHHyGqzDP84pqW5GburZSCXhB6hEeFY1Ag97NCY69C2NeUy6WaSJiB5GTOOSOKaBfcTV8ZHEqsuZK65LDMsO359boAo0sfTI3_W1z
GMznXsoazXxtgQuZhoDIes8CKV1i3R9Dsdj2rY0Jw0G0jlG1pIWEx0WY0CWh50U7vgMtXVhkF23jsGmRGGlKOo2lRnMtaOn13uZQ59eDZhPGZBXgNQ6r3haF
IA4b7f1BGEuTSZVtkbRSpY3Nr3g6lDJeSe_y4lA0Qhq7MK2b7kMR16o1T0Tf_HPam4y8zb1HzEz1Bi1ksdBNbhdsuYihLK7hSUL08lLzjMM4MgyhnP-aPK1-
iqePMnG2zlhzofX1Ob6Rj4f68F7wyroP21yHiNhzVSL7fVw7_lhBFkM0VSW1iCyu_m
}

