sprite $ISE [55x55/16z] {
xSvNUkiu40NXEXq1Ol_x7O6Ii_rTKSzJpE4d6yQwsc2husetjzNiAysRssguhkHzS-kOhclvtApjQlqQgvFvrLva_Iip2MJ_Ol4b5u_ayNk_C0VpVTpSdcKE
lesPkGdvdspaHmwHxsDAO94_-ivYAtkCQG8NYdyomzDGP9YaazWlRjnPFKgKXcqEcu6dGzIdikvirgsJEkvR2SjR4I4KdrpMsGSxCqBQoYjTWBc3VNAVMJyg
oObsl09aRY0tCCZ-rFpEZ4gi74NkGdYO1SflRBspbh1sCh0DmB8CZyZ0wazcO2KhgHovEwhQd7ByWnrVMO0b4NkrC4NW7RjA8z_L-i96WfmqfHGWNER8J13I
uwsREjbur2qGAGlIoJQa39FCimBlSMkJSnll1UO44PIJ8u7UdnkT2gF6c7l2KtrYZIM15rQe6wWzJ1lAmhTwwyxcNgTl97KGYL8GMUMS0nfzllyOSdxKI0gy
RRjT2B2QxLta5hjlR0OGJhIH1RfVZDaYItP3MnxVsH2GHhJ8n3RhEGAb8-Pwz8tD0fH-kZ0ddMx3qiYEFzaCxDrPagus8b2jtLzi62xIo1PnCaduN7-pNKiX
KXeDj5c2-bZ_OBDHof8y0bfkaEkNZdlpcFFOIs7TGx4cQWmqrpCrDW_vEcG546izwth_JH40lPvsMAyc3R1ZFUr4hIG1QZtVDBnxEkXO5peIOXvbkQur0xpd
kjmCCTOB7UDOp_H_upN5U4d1U4Nz1m
}

