sprite $Joystick_Keyboard [90x46/16z] {
jPTNsgim44F1ROgq__LUnpYvmz_XSyv3UWw346sxGwgjfcqzIV50rfih2O0ewsSsa8I-8OyceYBo1hF1pO6ytgnyy0wp49rtcEiTSyg_ame6EUL8-aahZZzW
6HncnGd_jYqD9F4hzEI7sOW0IRGlnGhYBn1PWpb2w5TYugyK2UOpb2-YUC8EW0-FGS9QW_aZzOEuW3WWp1o0dnuD37CLJFD707uiep4kj8orsesszvZ6ZojU
KFCqG-M44U0vwXfJx4wmZSNfsEEy-qimMt8UvhoNG2fJyFN8jDOKT6a2eZyweQt5NtYsmymQLuMQ_EFGAHQEdTTZU1F8EirI41QEf0JeUmpZ4gm579DhmWpi
ONckGhdQvHX7QQqKq9FPlkrApxsuCuxOQISkggNMvYIoqjr1Z4S_uh2NE0FW3G2KHfY8aovYgFLSwKR0zG8W3jZAs62LZt0JD840Q-WS9VsTR0mxZQUdEMF6
eQ5pDnaxZQc1T3KdIeszgpTYnW6Hb7Gp9_5ur8mH___EsJNyT4HDOxfwn66XTqvwJfTeyOWw3ojZ4wAq_xtBwFWry8II0HsrCn4Rxn_asJdU86p2o8oZpix1
BuC3-bxRYQszUcUafCieSL3B1mHFin1kb_7_nVlCA4VQ2cxd_3rbIpg2Nii8GxizWul5dhS2jLvpvrfnwK6eFiBE2Yu3cdiMr7JSVXNHHKZkEWLIVw2LRId5
21ttZOJLdFObf5mDXAPjg442leJX6kAf1hW8O8gdMx4CdTv_
}

