sprite $Key [71x32/16z] {
fPO7pWGX28KXQC2WlFkVzYyOjvSft_RYK_hGBQKD0CE4Ji0Mc0mzeUAuqfWEqW2Wcre70ADZL02ZCX6n1X3bi4bHQQ806Xr1SBlIWS57RIflFkr0S__RirKg
hIaHMxCj9-EYfWq8eKL96GKy9KFeA-MIB_NsR90b4rjaoi32B-VhGESzCf8g8r97AU46m4KCw28LY2fVc2jOfcLDYFBzNaOU_r9HuTu3Xx3brMribpblLFUE
P8pq-toEyGea-NQvk66wc8apaKPXpaXn1QBm2oGtjFb-v1cU0wxqDM_yPaqDB9ptfP_d8jMIQTo_50FUozncFnThwYzAKyoomatvlSnmry-DuWlBDvlRrdOP
0M0xcwYlW5EoWXFbvZ1EssHY37iQCAceySwczv5QyCg2DUwsoxHpmrVAHEWMRjTB0QOJ5C-YRa9x-GK
}

