sprite $Laptop_Video_Client [65x68/16z] {
lTPNkjmW38PXjTzWQV_xJPZ2u3P1JdBUUtqFk4BV21gXkyJQ_BBetNayt2zO3-3k1kH98VS2qlUYzm8mmyEjYs3okGQBWBBOyGd0t2Z9eafVW9Oeb5GZodiJ
YWXFxo1QGTkubFZDiZjelC2iU3I5KjWE9YQIQ5GyqgeDyn4Eoq2DS1ukMM6MBrHqInZ3XIsnijW960uMB8qnmZy1i9cfJ593AxXp3uYOYV0qnG9Ujm6L35l0
zSy1RkIC7WDdyzJmP41Fvnk-6w2tcm7k0VwXmDuGq8EPm70DzC0c0lfb0LWc0dq9kcTOfW8cP_FMnay3jgVyse6DW6Ksq9_4m_Xfu43ehRVHJ0UeupwU2GXz
Q9_-4i3n2dG2v0CquAd0bj78aW43b4Ow7-ZNC1qO70EI3_0F1DOX04u7b7q8ECjSe8qVVwuMKOLPHji0orx_lVS3Ha7A6k5C7JoolFB-a8LvXuj4ZEePnMZ3
FC8JzYTFzZQUB82snxnqmQcpDb-GuBuvVzSMy3NX4QZqWWZF6fV0tW9hqh244X6Eh3NUIx0uvsjzyxXGNrVm59ZUvB9WxGfU4FgeSQ4GNyOBT-PnmQt49U_Y
sk7wPBdLlnglzWi
}

