sprite $Laptop [65x54/16z] {
tTQ7hiCW38LXZ770Fk__lDsj4n6kujlThqEJFrPsEcD5MALq8m2qXTYyG809RPOFY1iWFe0nSLadwp8rQBgegAVrF5PEdtaqCq2t0ETI-3HQtkIO85q6E4SS
0-sU0FU1_Fq1_h90UKOWeiXz0P6x0aNYWNvv7zX8vAw0o5q1aNi2uWO12Ua3yeE1SlguBJknt_Kb472BzUN_0Ub620R-tWdB9zD4PPqCCGEqU3h7Pc1gq6k0
1-y7-VJNy_U3vHjA3MW67-1_xqWgbEQ89O2PA2rmLGlejY-0HVWUyCCG14XozRXU0tm47w39TjCnu2EGmg9y1D-3GJu20J1jGSU0NlSWpEeKf3ZWonvSPVEj
zGoN4KYnRaetR1ZWb6Gq02VNC50JOQJIZHX6k6B8RZ1MSIzHt4Dv3m
}

