sprite $Layer_3_Switch [55x55/16z] {
dTK7TcCX38LX8O4Q-z_lXCjpmKSfR_uqEFPdIXgHpxivBPLtcmuLfd_FuiijPTBAg9M9VRcPyPsYxrmiPbm6ncMwc78PhNvW9bKDh4dLzunfnxynPfPNz4ZG
-Gm3wuYnAHPP4tbUoPuAfiGTlR4Xj6lIqPfBty5W_iO6whIJiPDpZFf0O3vsxL2Zusc7QwDWrqEzODSkkMATtbzItraxz-zWkXj4dU4UKzeZAEvjJT5Yyycu
gxuSLdkfeOFVMOQ-TxcrBjQubAAQlLoZH-rKADOcmuxWpbZjlOAjFbrJEtjdEhvZR5Tw-NonqRhj1dqsRDVn7Cy7SnMYxhRUh3YRuI7lwvZ-XS3SSCcY2EEF
XY9POzrgvfhUI1mieEuuiBH-IusSOE7u5eiXBSwchpjcWmABjU08LEoPFRxAgTTIkTbAUJ4FZ-Bx5hxKLBQ9DaDkiNCk5iC2-tCU39MiUSwZYdbnjlYLGJ6_
Y7pZCcF9nBctib3yxsYYcK-Ndn05wwLyJOs8S75m4jCbPr4GALGyfeJHTgoDl696I6AU30vfnSPMET_PuKR5v7n5i7CdKgXaGbOml_ubPtaZIB8y6_BoHfeC
2wXu_Wy8kB0XNDv9GBpj675EjAtFNxABsRpNkAxyPibxYtSpRF5-0rkyNVQSt-RpVtBo_r84Trlz0m
}

