sprite $Layer_3_Nexus_5k_Switch [55x55/16z] {
bTO7agiu481XEgVxttSbmEsdigXP_abo-4OcSnnUR_DZgdnR-Qd2tXJ3JUK4Ro8VhZ88taKncU7_2h2pD-negCq8D_KBTBBZXCteEVmsr0c9w4y6nz8DxMJy
MBF5DNiCllLap2Tp_ZVP3aTm8cB-C5aY9DarsEUL3zFxMmSw3jBxYIL4_Zpd9zFkMWMakqIxPercy8qNkMDyeoLwPh5CzfPPJuZSVLuoLRl7pQnJni7OrbJK
bg9P9_Z3v41vP9tg3viVt3hF7VCB2mlB_1OwPj0mwsHkxcxdzpqQoR5qGnzDKrNXcvejJYzrpxPBiOCBeTYfRfR-HteYzL5a_J0ZtAdG3_AegubF5WF1WHux
HkhHKpMB2B_sI33lehl7jsew41vNqE7NDLgPqsvb-mDg5iRmmz2VKBC8lo2eTS-eLyc4WcEAwBQcQpQW8guY_pKf-YElmcAKaRaAPyrAfAmGZXzR3maBMecM
efBM6kiJCwuW8MQEfAWkBSe1ei9ovyWg1K2hLEfR0EQSBG2sB33ALRsSbhL4g9CfydPLbv7fo738zVyH067K9W4Y41tn76bziYm-Hbhflyp55NKcQCvUTtpG
lNCnWTGcrZHLIv7wPgY6av4f-aOfLpbHL9Ajk-Rz8MkxirCC1KXHiQpAK3GaHOlQf5fABkge9LfT0iHymW5tZ8aaYxLoZBIwGAuagIJC3GkBgiJvsheRvRsd
r4Or7hRp7fczkLjkz_eUkzwh_m
}

