sprite $Layer_3_Switch_with_Dual_Supervisor [55x104/16z] {
dTMBSkGe38LXtH08l__xhdrGkOU6P6F_ktEXyDV4J4eXZVuu9-rlykZXfeygxP9D-645J0Kn8PObfdahsOYoNvYE7CpGpVX79ZOQpCkLqRrPfanlLaR9Hfg9
YFbTKH7Dp4UuoV3lz8Psck9VjG2hPrvHTfsXG3PjN8iBWRLMF__ZrvaBCnUiyN_-1fHihPfgSHNpbe4CaoteVhuMLLz45gXvXaSZQsvgZggtljQOHjPYtd39
7VsDgNrL_iHyINzZmaZMDt0UMT-vh2z5xaI_Y_wgbxE4_8rY8j6d2QxrUKJllaXntE-ZOenNasTf7TyU8yvaZRFDd1JAHB_xcfFYOFPkl9Pvl8fEHdyShrwy
kDsRyuWhzc5uCCThUEvdc8tJT2sPh-DrdQz0--aALjS0ShfEDI2mjik5HKfjSq3PGZ0VIyrvkP8zSnFrz8Rv6f5aBg97qpjlaVNUNE_yru6NwAx-RRmk_OLn
ZU_i5nQcoDQtz-NTtlL-lBvoIkhnEAKpUHZZmaiyh9PJrQC_xQW45K-wN3bL59LTBBlKenznz33UHiJxlFUJrP_lwuVpucA-PmIshO7fBiuvl0kiwYQXaVml
cvv8DHqdeiW6CoJNGoogTgOiUILZgSBN6WkRcDA8xREsKRxelOu3R9Hxkh3x8tdFKgtC17loBsjb9Fc9kGGhe_n8pUN4b2PdWwL2DZ4V6J7UdKikYSRVe4In
WS32HqNCYmoNp3xANSKN1kS-d1It_7SpBr3ONrcMZeKearHeopAGAVKTgtFED2TUvv8XzpfQZjEQbNoaVvYnvQRHTvuxAcKSThBZOgv4rYhQl5koww7QJeBJ
MYtyUV722-D_BalgSGsxKxhIWxZa5wdqh9Blzl2q3jQZuNtCHp--6pvUsp6kf4VWG0lKP64Qg1kEki9fLyx9mXRcGCTXsWxKmL2joHglXq4T-0s1pJLPMJ_c
LjRMUpMeXIrA-2OYirjPkrLh9cEKUu_RzOdTFuNLKvs-Xv-guP5qRZFB6h4hRY2NnFtuE6Si5rO9GM49bWx5ZfL9vMcJyntJt9fOvjYp3Uk2BMuRLXbxkc71
XBGdMz-D-y9m1MeUs0eCStPtB7jp_6oCbGN4VFHzTjg9xN92lEnFR4rpR3namVWIdp2KtvDF658gnmiMrd_UgyURYiGBLPcalb7_0G
}

