sprite $Layer_2_Modular [55x79/16z] {
nTK7OkCW48NXOJhH_U-xGeF5Ma0ij2LVgillvsxWhtKSrR9IATCIyL8wfaLwP8G7gB2J82GCDJlSoIX49bpGF8CAEKIcKd0xKTum9GWemI8x25M8o7fYHAIA
DNXaLun8r_yQswl2Uaf8Mdw9sZlVe-0ZYf1GlHF995D6qkDNbymp9PBsNmGphXKJ7_ULnqMMWvMFCgZaUcKK8T1t6V7LhKpzYhxBiEflWMAGhn_2pohWHzKE
Lq61h6kuT9otLPc1zz-hjenvhvGMiEsTxMEIbg3kKzlcU4l25peonLkWTLOomni8smDCaT4TsDxDoPUo0bl6KmGT9ER5B9149bCC0_WaIoIHkSnHyvhQvSXk
EQPOfXbECv8GcMeZ120w882YLPS9mYnZqRSiQsLA07tMYymgQK-W5xMHtpDbwCd7ZE1HfgDEnzNujfrea7dUMXQecnXMaNaZEFXS5FMcL5tcndr6ISueRrqM
5EsQ0P2rgIuBvdq6IM9gccNFHwmdX88iYZCR8hXAkfm5oeyo_fnn5w7Tk99kmRqEIzvccL_ZhP3BL6Hdw2oN94XCTLam1Db6f4rrMHQ0IUPvwx8s5TazkKtj
4ftiSsO87VcOPOGdsPPfFJjOQXz3mJza8VE3Up86rxCONCw2sKAsxdbcZpB69ti6WEjxYl0B
}

