sprite $Layer_3_Modular [55x79/16z] {
dTG7MWGX343XD089zx-lGyWMTh3Wiqtx-TYe2sn-cfLKfnLpK-6ZIdCpRuI75VUBCKMGqIs46T8iMVGNnZCTp2HYoF1RHZARh4G26KbP4dwoCgl1D2gS4P7e
Cs4YpaHdBxOaHFmwAhfMcmUhzmgFnvb8j7xKp9FjKWB4KjlE1FDshmgnwlXMspDBaym-QiearQvgOIvnb6J3NhDZRVQe2ejcTM6pXZ2Jvakc13FUCSXOFliJ
q_eP_y2CC2BppnHdic5kcT-xtKbs7FzB5M2pKsGb_sVFmXYhjhEKBwNzF1tAJ-kTxL97xwzIBzTwzuBR001taNgtxess1QDTR1VhkcSmectjUuO_i3fOvKq4
C-9DxOtHyWHakAoriDU_C0uR9uY14EEKUUwQ97fd_5p_TVuuH9ZndGdCI5vCCe88PSCmrOO9BVTii5PcZrjb5gpCSaakiuKnB4wIlHJ8mdGc07DSvN4AyoWK
qiLqjh22h3BTmafUOzHtPfh9ynbLuJZWeeKUAvKDoz8HFA9GckrPkgMxKWzMrnHlggwzCzK78rZZcgdUM26fCu7FjCwOucYOP0pmO7HZ_620CfGdKuB1D89l
Hn93hVtgOlw-BOJVGlLWnd1M2UPAHqfiCclnfyWQ5RY5szTcPfN6Ab7RJD8Y5m3n_iQi5KncScCQg7UX6YXPL6koYh16RQhUlAyis--IpRrdExPN-OAsR5M8
y8Xmk9zO6rySGwv24watUZXVMFVH4DMdQkDS0Q368D9LMLdM03NKl5O1SAY7guY-OnKYyhwoS97jM5bKiiNfZZ6CQbzOfZ2I3VESNUkpziOgmeWtp636VcD6
4A7VM6oAH5lSCgqottlYr9iA8O3TMGkH6S8orxGBswN9Mj-rPw-vbdx837EBPwnhRl6GTSuj7Z8J__vUw_z9qVfv3G7RVzGN
}

