sprite $Layer_2_Switch_with_Dual_Supervisor [55x104/16z] {
fTK9sgCm283XX2L0Ul_xZeAbDjfVuxopQxw7hamXwxECefhlh5l3ERmqlIlKITmNYk3A1Wvg2HN2beKR6ORc6RdCAepo3ZcKDJDscG7n5y9Q0d38pBiDm5U8
0FZ6GJsJ5cJxuIUvBPZYRtbh9MgH7Iqbil_MPB14pjJ_5J_Z3r5jK6fbqRYIbwE9x4XeczRqmyoZx5PgIHc1PBqWZCXghe_CQMky_cH6R6flWaYjYTD-f6L3
QdtF64h0lpAaqQsCPOH_PL0TM1zn3THFsERt7Ul9-XD6ZxBsQ7ErMah5MRKia6OjNMrzdgwLwHnREkk6K5UmgGUmUPyJdpWSXuFiJ_RaPxtYQDoJaH6wYpqv
hbTZMd_WzJIWE2gHEQgPyHU4y_Nggw3jjZ0WSNDhj5ksSRBbdcp-CxptgqYBxIh9Zwdro7xiLrpRWKQKUrBqYp0iUBYQJMR7xQhQVB_Qi5op-wODaSISVlPh
Fs7T524WjjtoC27S0F-vy6mWzzRhGRsJgOtmZyoO75iV2GNf_qiVLORsg2grwQo6PL5dUKGsYvRANlEiB5MtoUNwUj5Q4TJxWAs_R9b8TGvx9d37RbsZtS-W
P0Rg6Tu1kwqyaM7i-PiPfEBWaz5FM0ug4irc3YupAgVZRCsKVw9wCelvAkFnyLPapkmEyb7ClpAgn6TAYHkPjHs6KhYTu0fvtJDhRzByDM0vowX92nAPl36M
ujdVXengSJK1NsODoz5rXkLkfZsoV8m7xRpQPQejlnn9zBJoJ8FeDh3fX-Z0gorBiWuSZtBJP5vbbgWUCYma-ogohby4Zrc15bL4nypCLDVvmt_TbTHYL6Ps
HZX1MO5uS95X6LNkqvb3cyzyt6L6DPK0UkEvxLvQob4_ChKlFKxICCgpLUzhgqXvFef0Fch8ajH2hpEKeuwPFmC-pQmVBtr6BUXra-MeLOKabvcF6l5bPb3c
iuNHeomV9d3Iwom7yjmh6GEdCzTfFdCY4zcyvzcpZkgJpchnRhhw1m
}

