sprite $Layer_2_Switch [55x55/16z] {
pTPBqYeX38RX118IOF_xFQGf3FqtYZWwh_VBKv_5I02ffma0Q2sdLGLfAij9kJbJ6l6agCtLaaqTkMnCmbSXXf6SC7YvTCJCJIn-YCOr8fYBbboCtdTVko0H
RHd2t736wX4ps9c-HRnY62zMbDz6w44l4BFKbh5zX7sAM-ficx70l6Q92IdvovaXySpI50S0IeiO0u_dVvWaGW3azgHVvpfobcLaKt1VarKpwrCMUhnZDlLi
pVB42C-PnVWTKrFEL6A7WLwjLMSwweF8-Y5JWpaa14nwZrdqLMcY3EOnmbz648RB9dpjDYWF1iZ-0vsjodQv8cW5iQcfak_rRmk_2c0XT-LCytpjaE0HvJjR
vSn3_OKXvorZzBeAucRDBBrgJmhxr9h9NPPIhMHJwi1bCIk1nlU7wCmFVr52eFK7FlNeEheron-dZ1MlxiiHhZ2CaBV8fXxHVYl0CRCAupcpj0-6D6BT6X-a
Ufo6G-Q3nivJgVzdyfi2_K4f_FZF_1y
}

