sprite $LDAP [65x57/16z] {
fPIBpkmW28GhA0Bp_kzxjCSjCN_l_PgR9Cn-OP9TBf3b6ndvqpuPx5E009yKo65mUX-WC3R8XmjwJkM3Wg8IaK8_211JSUIt5LRkLDZB2Yrp9nlokmg5UIWu
lHGOdq7UN53o3tcXeD2yKGpwGg04yhXAWvO6fqHS6WfxUi4kGEk3dYkGexOj7azU5PoU2OYKD9wfjDUJAiczze1jq0Fg0mM5oPy0CUZz2gjqw6SadNhtZcHT
e4NKyXEeqZ-3tHOObBIUSBnkAf13wm-XXMLxtQjIO3NWXMjmfyeS0Wrj0LeVAIXCWnQGLGE3NbzGJmBqyeu6Emqms6s12BYlG0wx230OdLKu2rHkGwwp0UIk
W5NwFwuMCyT9bGgRu37FCN8qzFY2qxvkVoWQ-sj2FgnmGaCj0jO4koKG1gJR_Y0VND3sRy2nFp3QhT1ceYuP-u6S2SG-SreIKqkOz_UgLC0RyxwQgffoIt37
XFwvO8Ilz7tpyN5h4i7U7Gs1Ez0QO8_9ck2JXHqA21ENRJyIIfkBxolGz6ETUH-mCSxxLGesoXYL64rpsQkIVAud34xdKQNkd2RD0PPsvlhtWl0qMvtFSrGO
i_a6vtET12PNCk36F8VJN1WRWfEvqTPBuAQ6u7mkItPymSdm3Vq7
}

