sprite $Lock [49x57/16z] {
xP05aiCm34LZqhVamFrlkwDrkNAQChvX-zEeEoOai8WmakyM48Xb3LCu9NSgtu6JczLx_Aj0AIQ2AF1p-bntkDfMry7FvsDtTjG4D5THpJlAe8O-MccwaeDz
89XVWRMYLP3CeNQ5VcHldQ9HuNAhckn3wTROsig-zMmHH2IOXknCWzVkhpFy364DYN0C5X70zeSs0A3NuWTANt2Elf-cgJ_3KIQ5ppMKEnhut4bKpYfG-ZFr
L7w61O11hyoFFm
}

