sprite $Lock_and_Key [66x57/16z] {
xPQ9hYiX28OH2wX3uFtVzWPxF9DcQkEOvMxdwzxQJ-2VBh00ajIW4C8EoFL4CjmbKNs5qyq2lkfd8kBol8-t1ELPUXeDtLKaYJVa5-Kz1VVbLwd08da8Bee7
h15hh-bXUDS2YQKCLsYvY5Y9S2MLrKd4mkc0qs8JD9rmNamYJzsFHGC2J0P12uR7ds7uCVmOye1ghPJV8YAK1p10Rgq90l50H7Y18I3rm2hnJOR0t4t3SkmP
KDq48KKbTSiWxW91DjSjGtD5w5GtsJ0azGPdDH73QXHXeAPghd3MmCLC-5WSAbJlMFuUANFnYw6qsOJ5tLgag1Y2wjxU6OvvpXQxzqAiidJLSMXSczinYETd
ERlNsDjyWUE38NU3RHbYSWbRLC-Pgi-OTq7chh5vIr-7WvRIt6hHk3VuC4bWyy0GEhCqvqV7ym_VUKI9cxmpjBcXewy6qKEuMRjXgDzTj32SB1ieGWqu1hPZ
IEhUCgAOMzao06haqLFbFGDWwwag4x-doDGmo2n22JQ_gq_-PiEFuHS
}

