sprite $Medicine_Cart [45x95/16z] {
xTS74kCW38LX44AMz7B_wwOIDc0puEtjcvxyxWs2m0RSABG8EGsmQHUpZjgSsVfuIuaEfJCn_R0u7SO3f-Ay7dDUZVcU3c9kbN8GvzxtZdafvYBpDDPKqjgE
OmAd0vmu9TNG4RUjKjMjSgFGYrInNvIgBkr5XuHLj1wJ623BvHtFItwL9ZGf8wklbQ6MJ6EnnBXpvKZgS0oOl6FZnu86DsyqEPVukHJ3fTvtFGNq8uuEjqzk
tJReIope_jlH6bFJ-lPaQD0xjYOkXyveI8aP_idIquQ6qojMhE1N75dcEBpYPO39Clnh_ijfBkFfWXZc4WhXEK5nMO4VwVnkgCpfLvsw5ESORxxWXvxdysjs
c_EoNgGmbyx5XMrpTkO0qVd_TF_n_lCJB9uHlWRHQBb8rFrWWD5XomPeioB5dNLPNKqtwF8wWkmnTkknOKpxMEf0TiVsSmpnUXGTKhY4bni
}

