sprite $Media_Server [73x55/16z] {
xPU7alCg38MHE084x_--Lv9ll2mcPSQPdVP_xfHF9pqcgkC-bOXqzFiCjJnTg-0EKhKFy_JAT0ykbia2PNu74RyaguiQloKHlwPzLvHlY_8XGdw3YV9B42B5
Eqo4LsJefoB6IoOH1_c-Y9B3MmrH8g9TH_0G3HK0EHc43G9wKYEVnUL890OuHBBZMHVeqJ691DRcUha2tdiu0icFg8Z31D0-58ZbGgR4ZmebdYCJ5Li1sxEN
A1TmQVEKMOIv13f2D16XoWF1XU947FY9x4M6CFs4ilC5ueWpLvj5Q-fS0jZ4XPHG4AKsebf-KGjyPwsSk2nOKmN3UcTgFqIENKqK-AL5gmlPHBN4Eg4kwZrc
CjSP9ZmLpK324ucw1w2qY18nEE6TY2d7cwX7ekEzdayYJ70H8KJpSvP8T1o9n3qp_4QKwIGvt8RJMxnVM4vAEqLj8KJW4pSHz7zHCvLf9oPHdHSNjQdDdylS
N18YemhQZ8k8jedQX89h3utHjVdI5X6BbSFSuSEGSXnRhDer7A4AaQyd5RLbLDMSyAkZgOkqrHON8PdeqpYl9VIOxw855mcXgZ4MkixuquUc0NQVDMWXQr_Y
hAA667JWCowGzLOGGP-92euuqlIay8MeqcqWLvkhUXKn7Pyu_KrR5gEx8K9rnfXGHoornT4jKyfkci138P6k8exFc6ufXCNoynd5yZoLPD1UrDXwkaaMkXSd
NTl8G0-qgws1dNTuMDEiHF4bKg-rnTEueL4oP5oe0cJEEZv4c1Cn-hXB7pN1zb-WnGFx8z4_4RuZKjJnTzHlUKY_ub7wsbtsVm
}

