sprite $mediasense [73x55/16z] {
rSu7akCm34JHHYEIlFzzLnGrSf1dapV-ifLGU4MH6kzNifp-PbEgqLkQlfDbwwF6w25uBua-jXhbtTWcLBy0gWNT4k5FTONmQo01y0Qazmxa9npTeQP7n9xe
ZzSU8C6AFmkPplOhoVFPlky_BtP0Pmge_KGNo3w7z3iWVu3SNYOqjy_o0phRePUPWEQVTO4SC7-Tu4coxu2CyfmA0B4x1-gk_1faWcixX3j8GNVIxg7mCu4f
0AgPSZ_3aGiWVXVdArLz5WTqvW82zEEDWDvDFEwYJCZNFFiEvJqqTyyKi0_q-6mUOHOXt27kJXiBEWi164hBBQC6mLWJNtU7PWWyHCLDGoFpS4P_X3mLCiS4
q-VxVSRrCSGcb1EgyGfYhktZIkYQPCJKrHWkOY7-0LM_GYdmFBODalFAdBdDCkbq8m_8qlnqhj0o29i09Cyc57JT2d6wMdhq6rJFK00UG6JM0-IHJ3MwqMMA
Ncdk7ks0pfBmTLC3isg7ph5xQfekA6dgRVJP-83ouwVGMkkoawMGSrZfOULa-W7bE7ewqNc0503x0-vFbEPM8R8WlK2jMcNEQoj2rq70sbvrXzPeoynRWXKq
bhdM4zJA9TfMjG2iMWiHtruD4ze7Uyvi9Mmfokxs18rz8ThA0StMgbfB1GYfTfQ-lRXFI8ShsoEK1E0PaR5TvejwX2i0ZmbT8sqadw1ER1ckCLk-WFfSyP72
FXuA0U1yphArAxHs5J4QE1xhII3QjGjqdi1HezF6SqsHlNy27SP4pdhDhJOkTQlpyQFMj-q9ZLzHWVrVWbfh7jlbROUGBUZRXqhCfCRRERPo_88KYF4hwlJn
Q-hZlwr-bIFrYnoH-ZNE5m
}

