sprite $MeetingPlace_Express [73x55/16z] {
jTU9ikis281X0GA4UF_thGbsggbHUZt9_R8dzZzQpWem_7i3eZE_v-FLKUxVO3rAqH64xw0S9Pz6y2so20tytdY522jGmmfTeVi56zGQ5eTVeG8sgXsXkmnP
hq90DQX2tNQX_Y7Kzw42Ggy1zaA6-EiGHyYD2mITAns82pcYEiIrJo5XPbclEQ9jIFXspQb9WHhK6ad1V1VYliCFGxJp1o4YUUiDQwtB6r4LOcouX41gi8Im
8I-XgNbcsuK8-oxKWEIWCqEgWkq0c4YqWwYAnXqX89sl8XJl96W755NpCzIXhL1VeIJ88FZlgwwARGNT_1gHu3sa9q7X29sAa4GcG-UOeByGho4bOkgwXfXw
o7dGc7wEQ0J1UE-DGSVG4JVbplaiNY2FDueLYaxAqD1-2nN-4-fgqvTG4luOIck8PMJd2XKOnkTGCbzC6nVHaUn3o4RIN9urT1a8CYn4o2eHIW8ulGg5s3dD
47uEARL6VWi9fzSNasn2AKEIHoRramrignYKWDH0SZWBd9iGI8ImbXzkGaQOydsDjP2TCQSRhJyi-ZjqYP41M_Wm8Wy2CPAZ6PVBkckabg5wiUV43CMWoEzc
CEji9y5ROdeWyPDqtvgPF0ZQVFC5oNhq_nCGhGY8Fp9eP_WZKwMcqnzHm1hemn3DUgJqEEIrno7yKSX0hA8m_1d1clXJi-P_tVXL1yQFEZ_xB_iV
}

