sprite $Meeting_and_Scheduling_Management_Server [73x55/16z] {
hPS9akmW241bKLpkVzylIBjqab-PcdcTXL3n5Q8z2u2qtoC0K5hzFQs0j5g4VuUKsio3y3imTLCNKGy1S5wSu1TBXXjWZYCJPJomiS4rNG2e19Shu37W99k8
DFnSjBoDFcxSnnj3XAGFcuXST0102nk9UaTxT15qBEMy56d2H_dKJ0yN4J-BoAQb1ZB0HAQdJSGcAdm0m8UP2VH469ZTHJmfTo9aWWL-H650pEmY-hy8yQX8
rSGyHVmeQYLUH2TWCXomOi4cYbRHAOg8fpWow8dq3L3y5ksO21Ra8iStVT20uiIcTXL5MgXad0E2Y4JG8-1Dr5IKBgAKKlHFqX79JliGTX5Z76adkUW0CPry
H0F2fAAHdjo9Y58adB2Bq07_fY66DwA5IgAArZT8NHfzYMgHRr4wCn15Jqdz8perPkmni2H7gbKa1qHougBl7gdeGtalyjO0Rlk8b-S78dO868Zq4NZLyrAK
zCm3HY6EA5cwtyZr8ygIDmZe1BiatUsZc3lTqwPe9Fo8V46o85on8ejxEZM_G6wOdkwuYjxZddQjYFc76exTu8UAl4aKoAAJuhbYvq7XG4KTJYsTp102hT56
PaJsXqH8oUFFj3W4IDuY5mc53k301sTBeZr4q9YBmQWGMOxAhCXVMw2_7mnM9rW8KXGAEv2MIF1Ef4alAOL1l15HdY9lKK0Uf34p5q4NHOjyRbNYG5-0U3RR
kiJbW5PziYggRSBMeKKPC50vIDjqo9rjXxsSHQssTAdSb3Ji0XfBEn3tNgcghAxnfOBSKosEujfBKcuRCSpH5Is4lOISdaLqJFhJx9xAOR36rWJq7z6-30N2
B6CkVtEqVpUYn0FODqO9JhQ5DiZBYVOc3-8IOTZned9mP8bmbhE1zK64Zo8VK_0gkf_Qi-XfQjTcOrxzH8EqsJZWvcHlzflbVyQBeXSRyWM-8VyU-IiFb3_n
5FYp_xB_0G
}

