sprite $Mesh_Access_Point [73x55/16z] {
xP31uhky2aJ910ZHzt_VomXU-_swjCl_MGI6cbDqZ3ZV4uEUuprdb2VUGHCzs_0EYpIboCPRx185tXE_5KsyPRReFINIrnvjqMj-BJ9zYzqY8ygNpNAtF0lb
14bs2GT4kr4hqRP2HMHMEqM66QH9P_TGuxn5_ANOVqMeThG8yuBjqDGDmIqYtw92abQsIAqPRFlgCnz_H7wB1aGPfg15Vekw1KhaFRN2MrIaI0LiXcYAd1SQ
yFEnuN7FAVA2elD3L3-Pm6Y4u49pb2P1kJWlv1PzRUHJrFEm5XNJ4xqIQgFc4HqK7UiHNOBHzVweNfZHOC_yURNLei9JvE0sSr6qib-5gLL5_K4b7sn8V8cM
ofnY5AqFaJ8IupDVeZZEBv6B25Q9Q2nSkkNyK-IBfEMFA4zSTxn4q0kselpYGwn5f4InJswKfcZHG4wlvQD5ZSVIwaPAAQeh40zwaX8LozF0C_hqXkDmKrLZ
5nmy5pOjBNe1FSLB4JTvBshFUz4-7acBtg_p9LesfptHTQh7ToxFTbNR_nKj1NI53qcmGiU0Xmf9iKtGVsV7W1q1fh5kqKwF3G44MGZxcIgLmgPWGlJEAZ0L
HSTeqzxRkKIj0x-AxRrOTMajiRaEy-H3-Lx66epp_wA5l9WO5xqA8gDUDT0nKgpxs9cTrpAkB10zRf6bbKzEFbchf8y6-Ztr52tMyrf5isG43IuSakC84N7U
uCqoQCN5A8n7pBxPmabVeeF3HaM6sf3xrMXqv3c3UzBaocBvlynpcPHlvUpXW5pCXQ4gKol210fngyW61Z5KD0oTCckXPlCglzesm8xZYeZJ0SqlQeFHy_yd
vZe3jTrMmDlpgDQAZnXcwtZY4Ii-evl7-NF-yO_ubMV4ZpoZJEyz_mC
}

