sprite $Monitor_2 [59x54/16z] {
tTO5eYmf38LXY45oil_r3ZsbN2r6dltjyfLRUPlWuwIywp-bJk_pPxILz_sfrElxFgRK_5u0yJuW_5wZ8IMGYRKo4LHeo31UosBOse1MouEgg1pLsXCjqckf
bRwh2l88mJKo02wLlfSdHOv00cJKGWyQ5352mXrfDP1UwbEg8cGGPeLNpwUK1ACWx_nwNgPf3DK4sqn5w6qwqs5wlgYyeMRlgCjC6oDD4jnsUlpFtq-ZtJyC
OfbEtYWcoe3GdALFD1G967FFYHfWDDVoDZJ5NW8vqmRqMNBSXoQusObok0TFLD6YtpvTpLHW1fkeGNlmbrHjrA62jlt9jY9u7ngRMGDoj3qVjE5LC7lmI77K
IT1uP7YLw2qoetKSbFMLC1d2tGEcMyBiy152rG0buG0p2tPAlASUhuolBFQlI17aO6iCa5_qGN_JPDstuHLgWBBMcVAZ58ZUsVRD_o6LVQniZJoe6SL1vKc6
TE46T17FHOeyxqjK3RTEgW_waDOUJy97DF99dr0izCDe0dc-oHMQlk-n6KA61PhWKehdVh7NSe56FGIDD_gSRYFR_gI3-aMZzkyeJ1sZFDuWMuq4cF6DJMHk
RqOOvGi1sOiXru9MpsY05LPRIQaQq2W05rfB70Wg0YHMosqTYmEv5k13_WK
}

