sprite $Monitor_1 [59x54/16z] {
tTRNOYiX38JXXH4WDFF-ptlMygQnJk7s_5S9rYVtSgoPNcV7hvaOz_WtEkkz-JSwZdl_AvtbtcjQn_nSVFFanFpSgAUqaCIz94OzQaZHiLT_e38aByTkrQKH
ckMeknrbAaIatBN6K9HIzoir93zsMT9ZNdI_toZ-IBlLjN5Vrb_HsMzpSTlMuWK5vssEjsrEkzD6OfaRMhSXrEzqYFqsjsupQjueGl9rZkksBj9MQem8V9tZ
vBBDETbNsZMSRPbhopP4DFe7BNsS1LkUegAFPmpaDbIxJfoEt0OyQUXHm29mrgahHwFZpFMCxDNPWMv93siPC1LdP6_F31RCesXNGCiJBqahhdfa0nzvP0tl
MV1ifR0CsRT7FJkIOYVhcMrJk-G-FU52xO_rJorqGzeEJR7INPWbBHxxUKaQsc--KqO4gGWgOp0F-JjrCnWTiCWB08H6_liR9TaQuRGkYTROMi29eKVa9SWR
bG9pWd9G8bm3dBne64QQQEYyqM5wf-fmW697I2Bo9un4E__mbHAUT2Jbw0sCwwv6ESNGjQClD0an0ZdIHrWdB8BNbTLSqe-Zp0yQnILsb-H0u_K8MmHWbeCS
_GaucbEFHZwu04Nc2Jy_hypqgaGC-T6flTYAAuOu2lfUA8CQDKItkfTDAkfX8N4pIV5uZcrIkt6UyXy
}

