sprite $Multilayer_Switch_with_Text [55x51/16z] {
bT89pkCW38RX3-yuzx_l0FupAGgpzDLMv3o2D80yh-zA9r1S-MrNa5_PNUKKoodrFbncDsgd0BHJfCDT6NHiCJhcanaTmuoEsM9ygYtM-DHYpeS85VsJKIFQ
Djktep7Vc5IrmPY928y0y6YkgDNMKgqBSZD6nS-IZvEToJPRIv7DoISBhQJLJAl5jb6xbnjJGWrVh1H8Zum1AhUnKWIm_XI3PRUV1AAyd8qKWAuVK_70OZzD
TlrcAcQsd8vHk7l4hUPOVxEhs5CvYhmBMcgh5tivooShzMQ-Pp9LHDoEpVSsPlSq1kBM6W_k71dx0pkJfezgpTmOdY6HjzCcZofc36ZSpB7E2ScCl5aeGERH
homMBlLjLZ41HmxjwSt7yhatJVfLzJ36qzf80BObCPZZ8-ut4-nijFQNE31e5kkXTSChpye5_CEe9XWrAtLbxzqPWCPiAk6OK12BPQmCGBrQiPasQ5yDOR1F
5dsMNbjjh3jRhmPWY9b0Sh4-6iz7RVMmlLZ7h5iI4XaJZJ8Bd5cmv6T2poPdLWfuN7t2aykN0iV35EKES3Q43ZQLz1oPsNgRsrdPLmujLLUreTM3vHH-PWPG
gOsLQu2UcG2bTbPkn4ULX16LsbdoDjhg3JCzCCMgdrXWrUp5l67bV_f7M7rTf7Gt0EQ-LjsL2T0J2rkYObHSoxB-CkSNhMD-aorcrxTn7V6xzW_mBlzypByT
qVyy-fkYkBul2EJvRKxu1G
}

