sprite $Multilayer_Switch_Subdued [55x51/16z] {
dTO7SXqX381XTHZW_kSD2EtZCQCaNl-fNl5jTm6m-ZQ3gOgzhPWhOSf2oc9Phfenl8lDQZN5bmnrCS6iM976_sFmaeNAcJYZtLv4dZClXhwd6DBDPavZMUpc
x2HZP_ZrOJe9fXJTCxh-dp3UFREl3-aUSHGiWd1dwQsG8xqOpecxYuMQ4yePpO6xPp4UHKmvYy9fgQsrMkHHKSx2KUrZrsshXCdLT5Z7gKmbTnaJvgbwgwtx
uKOvAcCiqLIL4N7nmjDzzfSmWjXgVTH9MYLieseVxRE27Aa5qtL5mBgITGoOVqrSHbzdQk8JVoIwb3DL-RxBTGAGjbppanpb-zbC5MnjE4tG5L3AaWMRtymJ
wSC8RZQhIe3Q4mRyC6NmS4Lj-1NrAY31qDjhn3PRJjOsKM-kK-vZGiQ-cNeSbtQORmjM9eFYZ9prlSBO3tKp5GfcVJH2BOMnZCMQRpKJLhlOAGxNZ8dzTR7U
pT4fPuBJ-Mtnkk2jSYO0O0v20P1cp7J_qlNtKi2b1Mg5m5t28k57cLbPrM9cZsFD6GChXhArWtrHuGWo5kDGmUmUv0nZUBFZA6NgCxI4nIXb0lyv6cZ667Po
s3t96G4WiVXCFr_C_IEL_M76P8b84NPqDYdhnR9aArHB2fP5SPslM9mcsKiMBzTxPXIdc38hPddA__d9y4sXVldJwny
}

