sprite $Multipoint_Meeting_Server [55x55/16z] {
vTI7akCW381XL521zt_VmrhZNGZn3Bv-zszDDDy8fm5OtStWK6MtQg5ST_Bc3cK4Ev4rLuk7sd5-CCNTz1cJUmPmnsWTfXOi1lSiHRYOQ6Uy-Ebi7dN6ophZ
AM8EPakL-GtBdULriGvuCRbb6Ckol4uic2phXroCxXYcZ_8Mo-cCjXXtXc-OBnbr1k-OhiBK4vrxoFmHiz9OtMLMQcopHL-PZJKLswodQbV210Z4d7LMDROL
EsC4KhiYCkAHX9eOfHPUZibCKKRa1nYOmd0bWXg_HrMFWjMJIOhuKnrHFeN6YsDWVdnfYlB73PJuQueQ_mYaX3OmTxVsZOS2zPOrvHRVGkRk7rU0fRjW5Z1E
IST_HZb8oup46qwHJTjysCRidocQbu55dUKKOVilpdKbkLQB6VZCObcaybMLKWjPhPHQKWVMOD5qXcJ5uwjLZunAvPc5B2Md7gcQX-Y9Q4p0wXnt1PBZ4plB
fGj1YkY5qSLA7DnCJo-Yt8S-CqohKNYHQwYtxEsGTrY9uVBY2Cwml3Be35z6LtM33VrULgMdzJ_8dYcmHmh2RQjl
}

