sprite $Multilayer_Switch_without_Text [55x51/16z] {
bTE9agKm28LX80iGt_zzXnnDkJJEBVzPkgta4tCN4XlRjuP9g6ryRJCeRLcrr9QbqmNkmbb4n5dIni2Jfe59cawcaaOpIUjW9Ol1k6IzCw4z-Sc4HMx3xkD4
U2qhMDt308wr-1tpC0jNmepHTU_62ksLyx9aAukjj_TOkrokznlkl0IpTiJxMi8gbhYbJC2u_cLG93ahiNAvAH5Tb30U7nbOFwengC3rgF7wHN3YMEr7OBwk
sjnrE3KtCpSz59OVJ7lyHOSJ6ojR2c7hmVJMT6sSDGwbj_p9K84wNL7qmlgwfurxzjmmBgnnonNSTOTVs3oH_PTPetbA2nHiSpN5ErhxhFaVvXrLl3U1ncJ3
vgYpP1fTAXuGhD87HYqGcE4PYVSI9eomgOS2StSyvl6I96VJcNKyOe23HNDWSvHCyzbGZ081GrgwesHQ53kjEX02G-RvE9ie6cFBs59_FfFda7Tcpsy0KHc_
61GL6wkj4LpIEaFpuL0Us_7jdelBgMzfIWsgujxEnBwThfFch1F9KYU3mqhBMILQwcIeOQMaQWX50lLWewobX37DMi8w8S-O4M9TTo4U6r8cf2-l29VMRKoZ
EYTqLLovji8lhub2N0zplj6mNRTVEKFXT5_gw_NvM5cF-Atr1kIztwzJtrwpznlsyQu4xajG93Q-5keV
}

