sprite $NAC_Appliance [73x55/16z] {
tTU7aYGX281XK53eVl_tFLJg7AQPV9Nklx1h-ihUl01o_fx0S8xVEyKSjUINr3hjFgfSy9SAgHwdGOnP0FXslA3o8LIkCnEIaWPGtaycL7C8IzQuAk3TMdKe
ow1aqXGFIzqvHAcKG6KHkBWRYIQab6KGtLNMHSPYnI7j9Vq4gdvsZse28G3QVCM_co_GN8hk7SG-ZKIuLw5SBbGUJR13es94dVVbcK4SAW0K9WW1VMP35iAi
y0C80JbM0IBK_EHeRxw3oEyQfnng3gqAMDGyWzfjDDT2lAUkK7q4yKleT8XWnisxGhN5ABqH6uBZN_Fkpw7Bkmh00Uh-O3XlHJdantAwEsHDejiQ0FUHGJtK
mCvrpuzGNydXa0bh6uDljvdQOzKFUhHXqGsDkh_IKwYL-Tmt3lYWwsdEX68vL624aseyHhoTAQdqBlFFVcav51m42_tBRLixPJWEYVJupp98Ths2HPqHLaXT
PkOOur1MHxeuuxL6jLPgNRPZYFKQsawIEdEy1-43HtKXZkdhHyFSCM1dK9P1joCMlSicRf44QjJ7lW1bnUjSeGR0xq0Ro246W9P1EPD3xf2-WiwySOoRFnT0
bGKXFOYJP45I06Kx3kK_LUIrzMnaG5zE4NM8ZbZbuqddR4A7Exz2D1sTOrlGho06QplJ-Wfgs_aDwi6PwLUGeZlXHXghzCOddXGaSm846FDnNjkFiWs7gZoB
CGoFCvQziVC4DOp_PqWUIIyWHeqEF99QVmffktF-sM_PVm
}

