sprite $NAM_Virtual_Service_Blade [73x55/16z] {
rPU7bYGh24098g3__x_l06whqrFdRGwtWxiAjw3eIOWwVnn5H9_ZnvcEEeUxsm_XFcPwX7uC2TCSBlYZI8gCFWUXGAJ_nHv522VuTI9-q7ozYfVe0xHJcLzQ
uaSUHEcXXwq7IjIOUR_epcbRXVNVzoUt57axIKzxXzFK7l0jEZoVXpFkApo8v8W-F5ot6ObRyMoI9NeHiIm98soevMbS9Mboaw9vY0Y0oaXmWPpoRUPtqV0k
8lbg0FYgR3LLOro5qbraZsVGb-WB1D1YRIko5rKUvx-s6rlVt281e5onyZPPuPaOjQ4yYTeAfZlhvTw95KHF8W98NzKZRJ-osaoyJ7o9fclN7ay4whgkfG87
h9shf8fTuH1hxYrH4gcj5f1Oa1S4hDenV2TjRzYOMoGKWZod7YBIXUG566fd4wNByhmgwZdHNiSS6xUeAkrtITbrL_MvAigeBAH4aYA-HVrDfC9vTP-5cqgf
BKuHG4njYqoWMHrqqusfPIEeireRrlF-cgcPLRo5o8eKxOE3I6a0Q3CPHb748blxEb7Y7O17YJhi90jhkqLzRG3eksVE1g0bQbT4ZFzDjFSlwdE8q4f4LqHE
9nQI1KDRbRvx0WQgyTFPMMQmkS91SvFqdxZFeXqYFyWKDpbGLqpzY_nLvXPLQtuyA3zb9xa7wZjcQxArcI86D3zG-6ZIy8WVp8qZo4pwXo21eAalJ12kniOy
aHX_OWIeszEXGEvgfhrHUcrhBWo1rbQKG2-J8cmGrogVMx8Ai5aCRn5gvI48H4uVQqhISb4ZdY-6P2lIzOl7tJgl7zbYFaBYNNhNLTKO4O4nbdaIWesCvEx6
yFxb3QjOcpT3sylLvYSevYsxeBOrfyjfYSPy8xy4Xxjfpr-jcdHTnNuUd93E6sC0rFcLw99mpcaScXRxDh-IQWnjpexPVpUFLYJtPSolHYDVqvd96sm-lmKZ
wEz39EvRyvMuNaCqLJKVynz5VvO7VVuC77_QNzd_0G
}

