sprite $Network_Cloud_dark [115x70/16z] {
vTc7bgKW381XJme9OTx_ULUY0xU38xBjjsptEu5jCovz0HBB7XF2Sd7EgMhqL5L42A_pW39dbhvAALbK4O9hm3nVvMgkCbuneSRYFQigF7XI5Ba3qzOzIcFN
LDFDmmCpvPX3NUeK1muA8bQU6-WXbc_LL73KekekcZ2zYdL3ameD4jCEqjiufdrnQPIOrWcOFXLibEdYQbgWHgnfY0cRc8ofdVXFZO8dHVF7z8Y-k2ab5JX1
ibXQMyKNn_qt_0oMLqJvp4R6z9N5thAPaWaj04WvXCCRkMPy8F5L4K_NH0xzZKzYMGnyr3JLQ6l9rZABnuOKFbPC3_c_RN1WIEM31JEBKNtG6nIxXxJ0XyqG
lhycqNRKpPuXBIcVAwWbFtfCoJ_P0fyrfPZG_ZDfPXhEnY7OcfljTRLaOKJ-9BFcN_YYGuOCeZ6QrrfQy7MLqvpTfjpUoZDQuMfHiB6L5d-crRLyJ1a-YBwL
OuQhlVrO0aYsNP11mzNYInHu1qsbNojS5teleeFR3uMEumXNKRpVn0esEgvLj0xABiOeNlXmEPT_RZcy-F4eF-vc4TUqDPnFvqS-zykpnhNVYqaTOjQgS9_5
_jJt4ngY3pSi5IX3Jk0saikGrsjbJDp86TnE4ZkfLIlUPQPe8IkdrntgvCp-8rAcYpoTP9fE8eZC5GKMbhaYBGl8tC3_lPmPBZcMUT7YmMJHJPujpjfFniSF
3wwkW1L5dZTX3Odvfuz4f3U_cfjlZW3oBnUHq9c8qDslfkyG4M3f3TtiE5qSz-gfSqPSHaKzfenz1-MBszx6iP6Z_6pny15BiA617mkX_caRZ_AZwlDTzigq
g5xOiG4lXkU-_lu5
}

