sprite $Network_Cloud_gold_ [115x70/16z] {
xTG7RWCn30LH_liVEbMOT8KBK9CwxZRXjxtQXSe8ZLIFL91Ca4IG3e8V_tH6tFyyBtu-CYosXWIHifeJ-wEYoB0eCgw8VNF-7_AG8bA8wlGY9qG3OfkaQwHZ
ziK-Rv7FKKjyZdP9qsHepXItAud7AvtShY63pAvhspKVF3z_3Lqr-NtT7kwLh0_FNtXjj_5ecGWFCTRNQ2zMY50RN0UDamYIBsB6354sevlv2sJs_VVVVt_Y
Kl0dBkkbcwMJjH95CaKoHJ91Sa4wSknNhulYIA98faYYI2P8faWcIAf7haTZt2q
}

