sprite $Network_Management_Appliance [55x55/16z] {
xTC7bcOH48RXKa7S_tx7XpCNnmJ_n0vlPpnNTIAAvRP8KFcs4g5I2ZUbb0lkYk9kabXTlGpgoZKM-BRm6lEDoMs_nFIsy3qcx6hCSiEOlkRanABk6T0SOsrd
jZUKOn7c3jMcpamTrKIdBrSNZupRMFOapUtChmcK-Jd5oC_IYHbK_J3LdQmihOpRWytHa_OHx7ki7pCY7ZcIFeC6tqkDXJcCuqCm3DggArhNXOZ32BULXM5R
wWV_7BB6ZCZvq3lSnXW6J5Q6uGUBPsRnm88Zig5AOt6gxTQFbSLHPTD6h0gih8o_mtnNUMD8g9_QcIUYK3z279WIyOaPrliFuyJQKy4uZBGnnXIfz0PBqqlV
3pIbARMVVovJQSrm84ML9zyU9e_AU5iPJd3OrXIZbxcTOHwuNUbCwci-J4dEOa8eCCqZdc_pr6CBaD4hGQMoiwD2pCAEaEPoPgjIePc7SYpdl2ZBEHfJosd8
vVi5QlanHHp_oHTgwe-epFSAHJVKlOEwTw6yZJwBhocABoc2krTV
}

