sprite $Network_Cloud_white [115x70/16z] {
vPa5OiGm30Gpg_-_kRJ5G-EMT8pZKM8-sW8abKE2OtFmGjDx6BkLToe6VfDDm2hZJW8sGM_-BT9oA1_06z2Ln1O7LehIA82AHKINFiWqiPcfBD57FKiqCqXq
p1xFWGQK4sQYn4XJQHt-6I09EijS6cwit9lwWS29O3z7LulFedOQcg4g5lPyv2JRQuubmqnPCiYaM3vOY-RL4ihajTt2HGgcreSogkbFevhEQt3ypUvPHWxu
yVSDKu7LKD4m5TZN-CdI0QPon1CI8QAPP8bc-YuM5hHaKXDB9ZKbZcXuUI6Bh7-0_3V8z1cBbA-N46zzycsiV9ULJ6gQbMMwUGqoCJ4tmiF4t3WMphJGt9OB
05pdVG1FgIL907ItrVwnn4bujKitY-FeNGB6__x1zdE_e2L96bxenkY1T54LNivtsHaW1hTcCgAkMlbjjb--cNZQC76wIon-tSPm-_Qt9APuZm
}

