sprite $Nexus_2k_10GE [55x55/16z] {
dPQ9TYmX20MzW23o___xqDFJc6IozAiitZgUohuCOF4K0p1YFYK6B2kt9tXsgngC9x1b5zC5ps1VcT5Jx5s6NqNVPUr7gOmFXFFotWBayR8b6zkPV02u9rE3
b3MwrfUCWNRVKal0ByEzpwpz3NpAU8Ey8BwW3pj9bLSs-e4qaaDgTsuibvwPvbDNQQ9hxoT2V-qjgcUc1mGjGBKx-DvZPQu7aDhIlihxJD1B6Ff5tcN2E381
rQO6kSrtPcPA2Te2j47jywQRsP7LJqMEMnhBXbT7agWbAmkt5_kB_181v1O5t_jBPf3QYdwAMZ4h-t8fiFSoF3vcGbOGdo9d5JiR5qOoRWnQeeVCk3DBLAY9
9J_9y1aNcJ60ji3YUz6gOlhGXDQTwAQVeYN-IdQs6GerlnZoJkfTLUP2ms-OlI3ngkgzrUMBGLfYq2igAZFpmln0ApgpNydeUPRHWwoQXzayczdrIvdumV8e
XgY7aypmBXv_fKjdYwwXh6BnLqp2fKlYapt-Z5ZC3cY4zZYP-vNFBUxR5h5nzZ3L4ODd78X4X06KWTC-PnxWkVfis3Gn7k5tPDmemY46pWEgeEajJusaGmHT
4rbBxqoGcJPVBzeiOkXqyFL1MXyANNGo4uyRlZ9hGrRTkqyqDBdkHQUfskmzJhZUMy-ZKxC9CXknqSoTnMEAVSwiMGYcjHwXAvE8-a8E1iHppa_P9CXAf15Z
POs8F1BLK1vTZJMwHc5BlBCkKHPJ3-qYVKOYUuY6Yx36Nt7pY4aqrvpn3FSeBFu7muZd3Fpd8_D_
}

