sprite $Nexus_1k [73x55/16z] {
rPTdmlGg24P1f6Zslzzhco1Ek-rhvvTFX2FnhODert_7i7lgV-UoxYcbs7-XzTThU3ZzDxYRceZnly9JH46FcDxmleI6oA88uBi83XFP5Eqq4T8Rl0GI1Lw8
mAlUWPz5VXhWju4QBqGbXu6-ZeJF9RbCaPDWW9HFpX889LF4ToPOf7SQBy7iy1BT9A_YDzmY87PEKPFJ78UTJ9H3IPxZy9D8U2C3KB2a3gRCNeQGE21BjCC0
v86Gcg4fcezbqKKI6ABhWsZl9b-_45qVHHJgAVrRKJxAYRw90YvAMIBfYqX5L1RQHTgpSXgFzTvHolC10dbFHvTeOue6H7h0uyaK1KhzA68zaFHQPCDpYbBY
BoAbbED0bqyKU2kY4DqpAQQ15ItdS-CMsLxTF7MCLEqrGceHOdjcpVD1f2J7WwJlFIxwFXBbjvvJf5b29-s9ISzZIhrsKR476V0mwTeibWyFGbuU5prGXAJ5
QMPYjRPGwSuTJO3bUYqo0f0IqKmJiH8HW7oAV8li8HLzh5H4pKEPr4e0-b9a2U0Udu7yR9z64MT9wpC4gi7a0tapGIv-WDnhxElLpW1oYDH63Mfe228_eDvz
2LBfxIvYb981sEyOqEwmYmJ89n00hfhkiMfbW8IGhCGhEaLjbeAu_N0H8058K3UaBeiO0UyYhRMkKcfMrTXtYb3gunm0ANNGSWBp-oH0NArLyAMeGSLJuZg2
248MALCpMd45W3UYD4UsVP_NrkYjUORPfGa6l8lypSQxjAGpb3d-IZNVdVvkXoYNEzBgz4DeXMbIlx8SHGnaboFhlNm-yqZnfzueJ2J7XwOzQ_mnhqGUpkOJ
2ud626wowrzYSlsHsF_bGVkVFF_Rf-o_
}

