sprite $Nexus_2k [55x55/16z] {
dPO7ZkD030I7cHp-_xydoh8fEU16Mxkskq4KbCCOddVnKTQyI_fkXTqXDgyi9xW3sURb389xK9HcU0NWVyM-QWER0L-AxXfT6T0P1tufhLs6dU6g7S5sZNUU
ep40dylTw6N36Fk0-Qp1M0El6lVIg1U0dNU7Y9-Qd47WBW2T6O2FqHSDi3CFEfUIMlEZzB2BD0JoHUjXW_Yv6gsfw1C1qbFXKnbT_A4LKdzrH4MFFw71pynr
u4LLMWjLKuQDiGC7rtmqQirCJLv777c7HW7y02lJ5iGs3kq53rOx41eahyRG-LC3QmYjmNE9Dmt96k3E2cBDRErZAA3dOaraQnz3Hck8hXkMcOUcJD1B4nge
dyNBce-bkSlbeFqkLDP6QTFTL9LhJ5eS1UMzM9Jmr8fmGx8zH1NWZ-8H-M3MPn-x6qZu4mDxbT17YPbdBI8yOX--4F8kJBNGbzLQOMNLk0JlSamEgTLOeALU
sXsfrNLfNPijBMhph0JxfxaHBtsB5qFPCWqqqrXcBZ99cMDI1BDIv2fYQQJrbyQvJ51a4A3d9Cjrb7EQQAJ8kXIHBAQgfZIdBreJaH6qs191B7gYpbYM4Pd9
p5M2F3RDWpnlm9QfA9bESzqotYm2adbhLt84Sr08-QHOjIOnMPPWnEYvYjiyJkKqovkKstZ-1H_-9-kFR-R_
}

