sprite $Nexus_5k_with_Integrated_VSM [55x55/16z] {
dTO7TgGm381XR7Nf_lTTMInw4uzJVnuPKpvgsdLf_3QzblBV5bhAv3TPkgKKnW-wdW58kd0hzJsx7WYscCmVTQr63ULRzdgsXbmCFczSx_sH3VYM7IuI0AGO
Ri4slkToixQT68o9fyQDNXdX7I6ihOHhgYzLVSvPdysKdWebmuwEDMkq1Lymhl3uZlYEFioQB9JlSBupu5FDxYZXTczd5fanTmIdKy1tB8EnxqNNW0EJZp7l
A-wxbCwQlSNGpUTb_83HyNL8vL-SxSJeKG_JchL7RnVPvz9KlfXcadE16ec-zZmIhJpkl3V353t42sdLgXddjOmZ4-pLvj7iGSbOEZraaJKJAbID_zCKwvsV
oUC3m-kz8RON7tAhIwn6DtL37ZkpX51AEZsWZLKBZjxvZ7PM2KmzcKORw_GRSsBAkzZDdegvqSNcoZdC64aYmeY88-CSM4H8BT_v193GQSu0u941iQujp2oH
IGuMKwRf3mCJO0L3p44KiuXp1WyBfd2QOt84IApmbGbBT8xD72GTf6ACobyLARquYqx1X9bLdoiWIwerTFASxw7aZ7rQ5W1UJHIgFLB9dFL0Z2E2tEit9bYV
pIRWdCK6883NRe7NDUS4_y_q_Yz3dE9nuS32d3E6UsJgzQ1MjTyzDDG8ZGuvd4bgK8b7Hnh2yUJIGu48dUl27VJjlJaH--czWGN3cYG4OmNYNiJtJvqFCn14
TyW12jHQ1E3Q0e3_b-i2f9Rl754YU6X4-lXTYlwBdUClwQL_Kd_yp_mV
}

