sprite $Nexus_3k [55x55/16z] {
dSyBbkeW381X8Eza__kzGMpK0pDZxwzzzpkXhMdSJTjKVhTqKvdSoT9DfT3l19ekt5BTSpQPZA_gev8xh1Na1uDlIjOImknFDbwbkk2VhBUj3Y0FXZ-NxE3-
PgyA8JwO4X9X_lR_DZWHqSK-mW5qAjb8CzjOejRER2HwfejLQoN5ZXNZrK9PVuLywfqbseEVcV4A3Wx_PZLmO4KyaoEJYd4aG_cCYUKZArRHs1YrKN1Z5V76
MaAfr0zCyvSnLT1c7MMbjfYUehQLK3FpMomTgwfdFpCULLzea2oriNEqq5fWCTTdWd1Ingq1wrF51pCLw6teAKvaDQgOcIb3ozwPLVDyNdfyi0jblOBrxajx
gdZsO9fegr-WqCpNRqqJx1iRkgEgleqUiBCyOzdHpYOSESAgtVY99UJnoJoBoedzdINCRFwam0THJ643F8pGBdRb7fx55Y611B4pvA_ONmcw0c5c3dPYRi_4
etAKSEgTFOZYn7Yig8D5PM2kp1eAVcJk2YFZtZhxjO8G4Cu4Khu15z4aCsFAahNs74WTe1DdECyuAeD1ZdqryfSgMmELbCU3qH15BJCZXxO7wJ9a5sPnel3N
2fa9ENPsVHzZpWImS927U5jaCBw2DFLn1fQg3x0ydQHoz-kCC9D-ZSgOdK695TY9uv2fm8pxDIeZ0F902iCyEp4UiDXWZoiJY_01Fayzpdd-mlUdQc-lQFnF
slI_L2jtI_q3
}

