sprite $Nexus_4k [55x55/16z] {
dTO5ckCm341X2oo8xd_VLUokmpH_IMtoFWrF0JI-KW2mcBuA0ut9NRzmzvWh8_Y2pAV8ZE0RQfdYAu23ViXA6Q6qZ5uf2R2DZzbwMmEKz2c3SW1F6HEL4_3B
-DhyXUZN9I9kcV4hqAESJZD2uaNjrvwr8oEhYunAeNe6aUkFxRB-bQFwe6VIzIZ1WkLCoxpF3EM87ZCX-9QfIh_-GkIXwdoatSbovpqRX34prYtPlx3F4kCX
uzp_aAKg-nTAsOIsP4SyK9a1ZofQPcVuz4VVKbQPnNbMon58g-9cc-00FSAg6NaM-qol5sErv1dijocHhVZ_YvH2qb-ARewzoQWKD1z6vPAHDx7BJAWaL1lM
VJV5EXjHWe7CTsBBZSeHs37QRLE6GuRNKUV9UWYYmtqqlf8L-ugzASvD_YE8Dyd4SbNgUM4i7ewKTpNltgfSIOCbX2I7jvJ2gH8pkt_O5gGnCO3CY-EzUOU9
MDY7PUwXf9AKiXml4rxWc34G0KkYUPBeh5p1VfnDi4fYL6Dxp2X-M5n5rBb6Ufj93aRaCP6-o73rXIH0yZR-k5pHQ4Gc8MCnac29jvY8FRY6vrJZBLVFEwIf
Zz_OEj3u2mMBxmp--Cxy7m
}

