sprite $Nexus_1010 [73x55/16z] {
xPTNehCu34RrgLhs_lSxaIbckEHlkIzJJWekyh7e0CJud02Get_EICJe6QQVO95zl3mz69_1_ZADde9FaIbg_3bjYeG_HKeqcdpEpEZRHAdo20CW0i3oCpGt
aOhU405T08k-HLHFqPrD0-OjiLdMjxmNSOsKYtSs_4mqqhvw80zj-XRBCKL_eyQmsWsLCjaR7aNbiGSKo_H6v7P1YCGUKTGCgWysFqJkRlFV3SHLl5DDIWJK
ZtKBiRtZ55rWWlaxX0xu5lH5P4JYRp4HDLEfjEp78Y7uBw1Ofeie_0GagnQNxrfwx9lI5z4tqOaHMJpY9YBgSQ146YSvRY8blF4mM0IGE122By_Cg9_H0fAl
3eymo1nbo-IWQYnoQfP8vyvO1fCe1EOivt2DQtZLMXzxHYqAgNPVYGZXR4VCc1RDPkDIINcAANfHyHhj8AJcyrr495wjfOEjeEgJFfQePYBIFRRDkGeKDC4n
Y-WUDAELoA-Y5anoIOU-8ajq8PMuNqJfH7xqjJmoac8MsTeEsqMJ8q7j56LB8xGyFordKeWghb9zl8gvVsjtCSKIPHfnouss_UPUgxf07PORmR8yes3ogyW9
iVSVD9DPySWqQDiy7BdJHv5O6OsA07dUMT9qi9e999Pc4eIyYbBMkZtIJ9Z5RvhQH5hB9N8YRVbhz3LI27aH5KR4tdx7Cdem8SOY9mOYY7b4v2EXebPpzQer
Lz3fMV8N8UVfyEW1qUt4WULuf2Rb2fBMisVnMhwetGDYKn5Wbud6esRbDZVNBULK8ixzg6jjRQiV4vLKhD2c8D8-Vf_KRSj7j71bMYd-DccW4rHwVqnl9iBC
efxZNyh_n7TvaD_YINpRM_PV
}

