sprite $Nexus_7k [55x79/16z] {
fTK7OkiW381XD92GTF_xFbl88oGTxlkxgE73cKvZVnvFPO_QtMQ4wL7TV6iWF4mccxKAtuAQ0PnDHjbl6CqcuunQ1M-TCppJP3tZLY7tbwuDiS-IcMITAeGD
oX4Z85Kiir5iYH7f6lLbLeSbqxUa4rBFNx9CZGrDDZub201zh5cIhvWmakIlEvdcE9kD_3eRdQYF-oZpfLeiVSR8OcVAn58DVs-qgW-hF4zX0ZN3tp7YjLyn
6Mlu7KF8q7ojmwpxXwpwUiRyV-E_gJzUkRRmQIqLoxDuTspnDEF64UuFBwvXQE4cz2Gr3usm3ez2yR3mWLy4-3coZOL--J1_uMWaeqyXN9VXDVsQGTj3-jJu
ac7Bu4UMzuLktH7F6qqPJrQV7BXF8N6rCpwYVOQW3jYT7TChkuxIdGtE6jKIe8NXiHNYdVKCiMUCZNX-SEKH1g2QEGPtHi3z626VZ1fUn_iRamuaFHD6O9cC
6dLP5aWoana3IxMlJhRx8u9Ues8LefmnO6i0s4NMNLVMhmaLXWQDv0f9NfaUCNIj9E_6vey8hl72555ALQVhmFeb4w1IL_U9oXTsR2gh8zGhkrZlnzsJHSdz
Zh7gC3_O4E2HvRwoE0QfMI1rBpOsrUXO32XBlP5KqEXakxhN5qRj7f-CsxSCspsmIEOsxXS0-70sf6fZwbviTsmpHTQ5ATAegpys3OzYkoisYCPOb2dmZYAS
DB9YDjGomc6cSc-O2OZ7bfldoOgTTKYkhyfSqE9gPGfIWxjo3sVoBzb0FeS9LJSpRnxnbup8hWI1B4rcgAyiV2iNWbhbBddnjZXxkNlt8OhF8boGDyKuuiY9
Fx9-tMjd7DOQUqUzRJiMjXmr8ekDKOGY-yk-A-jSWrgQhBQOEUeRSnmru9nDLl-BNpilJCdhL6HHZ6CvXBwmsicejZvPdR1RFfXZPKBkoiXvu6BL86HpGrkP
4MBkENFV6BbVa16HVMNXPXvdcX_nTQVE1H4BMtDkMw2njh8rtjI8noour4CM7bypZR_4QF4yRGtrB-eV
}

