sprite $Nexus_1k_VSM [73x55/16z] {
rTI9OkCg38LX7Gc4XDx_VMyKd0K7UsRgtEthtj8_9ojWSPqXE_swiEoukrtXxZtkdShNr2n5zughwWW9NoNta1s5m7l0GSX6Q0q4cJ61PUKqn4J4-pJXpqCW
8kpIvo4lwq59Nagc3qh5HsX1G0bIdfX6kooCK2qxzVbV9FiqOT6fMsZlLW8DA7N3j97wOHrA0Y0pW3pYkBd_Xez3Qo3UvubouDyT2jVV3AaGrIKTYtGfGrhr
NOPqvJIa6Pe9uJkXyqNXxJT3BHSj3pUFUsWfGssMYzgAzR5eZHSXr7KdpaAVYyh18i_ESQX8RRCgeilEuDRMxFDdoqypoprzX2xnUEXsgcajfMexx_HVXLfb
q0sujlCzvo7bR8XaZVKpq-DDTpjIGIZjlgo0K4yx6Ng-kTlRcuAuRR_pnWIT_kmnw_xIchyOZywG9JP_QVqmP0NgBvNG_4q3LN_epk878MKYdGOLdvJdf1xH
cQ0nUSwXr-kDvO1vqFORKnqFypm-ZthEULFTTRlyQQEwPG2qWVOvP4BxK2Ns7IOD1xrZZwV-kcQ4ZIv3GYsSXz4JZxr-7wNPlF7TLUizZp1PH1-SYQ2nqYl8
OiYJW4MFDmRuwpIFEKic5Yz2DIQ599wwQ1oQ1pI2pOEe7Pqz9zDzuamIF-DCRCyzdDcVbr3C8zmAilDZBaI4yQ0f7bTO0OY0Od5Lz_5Q-BzZt-h0ljG1x3kT
lm
}

