sprite $Nexus_5k [55x55/16z] {
dTO7bjmW381XYeIQxt_U2BCYuyLv0_ctkNrFxFIKs4xZr9MUvguhePF4NLSC-QJAxambrBQJpgXibSkC3bXA4xQRrQrIwh3slhB7j1y8bMu6_owjvGfdBDnt
rc-8yVKnR326pt3yMijZ4a0mV0G5y2rdSMPbVLdlh0H2v5zih6HbqShQGBtyDy1P-ytQdQCrQ6_TJCOsGZvZz5CCB313Ugipkrd0uWpe6Vx6CgVDiAmi5LoO
1OkmBQml_7EDmTOQ8k3FJpo2GzdD-2rCImxPStN4Ki5RZTvPAxCSY8OQYrJ-4iv9B6hHP0JrJOcpsiPca63YAAN2mZE9hmQD9KRDL4IurUGL-b2ps1vAuoUG
bsVrmmLwf0nfBVEAdam8yi8Alw3bVnimDvgjQ6KEiVW8MTA9LXRmoVH1576H8w6u_2aOcfeMK1C4iTqGi98XMgi8jCq8J0314wrYsm6POiveVUH-uZCOaOsh
RYCL8w3cKNMvop03PEmC-bRRP8pSoism40FRTe1AhP4Ysa4DpBY2N0gqhxIAgrpSoS5DYQXO6P5hKzmV1m2e1cZQjxQPaDYbfUhbcxhDhklotoonwV41jXcd
SCUViVz7_G4
}

