sprite $Nurse [46x53/16z] {
nTG7UY8n343XKK5MkVzzLmRFUl1wnFQyzEJ_v1BW-2508cOYXADiM1uHVV98YH01NmjWZLF0THMiCIPUU8KlrPoO45PEnUYbOdWVlNOx77Yl6UvkRnCp_XND
6rpeJNz5mvs6c_lUHWkhju9x3TlXjqy9h4UlKRthcjSumseRzL7fvruZdc7QdmiMMOH86U9doABcxX7voLfv9TmyPjupeHkh4RRgh6qyjhJoq7TjPdr7k0xs
i0SHy-GTwvExlO-N22NgUaxlkElkZT-nqD3VUUBK2nyOSUZa4wTUENiql6XHF_6fvzxHmX2kEhbRMxJhkG-6r2mYGujgMtJ6YT53eMjnrrDBssZ5CVgdT1-k
OOdvjTbqXTQ3FDe183xIGXj9nEDdjRD6K6fMDNTJbKetZy3Z9q_f6X7mqzgcPbKfTJOrPL-iST1f4-k9LxtyfYhwUvtDlW4
}

