sprite $Nurse_Call_Pillow_Spkr [36x60/16z] {
dTK7hiCW381X6s_i-v_tqGH5KHRI-xlR3zLqKkGrWKjtae4NatjLlxFSesSJoiJQlumYgoarVpUAbbKrBhrEXcplDqQWrMPIAKz6ywYKnxbfPFNczMYIjSe1
i5UoVXW5WFWoNDa9-JVAYobhlJ9ZcpvkPaQyRQiwSUQpgMWSuz8RvuiP1MEZrZG_J6MOUSylCzGeNqrTUZ1ngzCqukuHxftX4iOmHyu0lNqRayCWgKhxD1IX
6Y5tezCCqWF1UfUxqTsWzscYNOrCGs6c268MSZEs6x7JgXT3tX01457VJKGuWeuBkHhskIyxPiPNqw976oO8NWqq2xTmWWyp514XV9dPVusjZUp6OkI8yn8U
3FOQPSFSBoz6fydHkCpHrQYiZSdwkPpNCpijzuwE_pLmDkGm3BTBT3PYuomVEXcJfK6djN5ScZ7EqZWl3Jbkykk_KdMVodoMFgDZugbFMs2uP0gNn6ztuDMW
AvoRxyaLdHTAC3o4wYQ4l-Gq-bM9nvOBmj4V
}

