sprite $Operations_Manager [73x55/16z] {
nTS7TkCW483XwPbo__ik8B98jXH5MpzNWldVy7eGF-htVI1YLFw-2lne7LVv7Ugjr3j6-7l8Mgao67yNHmyvtK6a6pv2J4Hy-MmGRdx1CtG7WM_yuP3SXf2_
9ZDq1r5khD0MFiK4G7owC_mCXOe8GSFd8MZeonsDBTG80A3e6S6-TRK3OsU5b4PSpp00dtR66Nq92T3L0IMywXF8BcHRgJrf3NMBndr5EvkXJiSRi-TFOVqN
Y-bkqqtKFgtGKkbJbhykeyAdAhDZg0uXBuP9oirBzyj8WidUGfdMgPw712OU8LoX_R7y32c3t8JaD2H0BUKzL2tK3nDt-ks9KhYXlcEZK-dMbpZ8bnFbFaJO
G4DUevJk9dXwDJzEvFjG-NOr5E-P4MgCrRlhaBo5EcNphFuOeILMY5ydYfDGCpjl8JbEf6lPG_GMcfMNa5bbJ5dXVbpcMjOMYbvvlveYvz8tSYSySZ7KsNcP
YCqOoFoxZ83TUKwqGWg8gFw48Y9O3Ij406Z-H5OG0EKAXNieD1R--UZFdMXy_Z6sPmiuzaExK8GBiuX5u_Dra4tiPJMkAgoxqArCjSf3PhaFvNfKzcVaLgqB
vvMgNCfuBAiNB-LfnsX1Cqv68hBwMWwnbC6UEWT2jqhtnG5XZqDc2BCUCJZ0Z82DrIC2HsmC6wadak3CyxivNFDwmE2Q_O-98epm75duWv1uNd6E-ZwZQrPF
f5_9-ii-_bG7e_w4m3_sN_OF
}

