sprite $Phone_Polycom [65x72/16z] {
dPU7Sjmm34IF0b4Mg___teYdACR4wczCtpIyMNRgSqW3D_1vmyGVfZS29M5kvadA6u4pGqpLajGNzGt_1Fbg48H5y6OGl0XUzG7CVuAal-b15N1wquCC_KxZ
cpuqC1UGG0w8vwieAwGy7y8AwO-7iF1y67r7eCysOluFqLu5g16U1dWVmVS5rES1i50ZF0e0D-szgvgZHBYx1c1T7Qj8ks6DCDqEu6B9UIOv_gU9tLwE8m1C
mPa_pAcAUyknWOJQAA_Cj8vR4PHCDUxWEWnwOmfDkOlPZQbqCYIvJ_VQYUCE-CnTvkYuE5acaD5vY7gIQETBm4Q0emXwlXYKJFGy530xXa7EDb4eJz0O0ao7
IoZJZIUObnMzlmdTPXuokvLjkNyJsAaWxF2Mc7X7u9i0q-u0vCKOp6Qv6Th1CHXwFeZbfjgjJ_JaCJtA4NjmbMeShqJq_KEwrgSh3p4hWf-f45O1EeuYf21t
3AM-H3WFK2TJG6O5wlFXSV3RiDMN6oXaRnndI6J-De1SYopt3BNUIqgBpR0AJCoy6fnLmPbHwpDC3Aj1oOIAgtX965flbfbflUQ7glUlaMmWH7tyrJ66Tuty
5ZF3kY4BxYfcqeFqZp9zzA16tEvKjGLTRzcAYOq4fgHy6cONxnBv2uGl1F8NyKsW8BuBELqC-GmNSKlgUfIOvo_8oauyavZHzfv4FACglW7M23krbtdAJQjd
SOz4zKHeu03msXkunzQAG2TnS53EnKbLP6grDvcnHDlQ_s_kLQBdp_nGyQtbIltmQAA77ngnW4pK4O-5lFd4YQcrfXaYlhNKrjeKTvvfJiQqe1bjxV_uJPqM
WlHR3sKClgcNXl6R62GnFVZSgeBRx_MwiciN7drujR-6EeX_wzldjc4ei3MCyjlr0z_RJFvvW835mGN8vn5DmGBqyvoVJUVoEUOF
}

