sprite $Primary_Codec [73x55/16z] {
xPE74kig34HP5IFm___lauqcG71cqjxj9vKTwypY0jZ-EOR3KpzdjzDZctw4kUdmPC9dK7RJNWlZKxWS8gFFiU-Ac3w5hPsZ2O93xI_navHJ9BCekIYHX_Aq
I48qmOb506wTYN2y3ob8MYZ293Eho4d4ntGw39n02OUZ-HA8uLPSYlHE183EOua4uWhr1Gcxv12SLfdG44q8M4ILe7gAr4KkeDPBr1U-r9bhaQWk8aQheWuy
ULx4r4Ign4S644B4IQv5cmx4OaL40uRUiONeDGIoP6-9LDUikcWl-KLJNfEpKSsVKtyrKHb5gdbcMnBLRKcQP-yYJfmd12b17WTzoceNALAIsPDEv3xW-wEm
kSPLRZ8NEoGDpSwMWYq7Y42pezAWCobUoAaRqWYP8oaGSyQ0igzediXDfAieKr_byyKfm2h2jf-Y60Crr9n1rE2faL83oU7OMYt557qJyroaHRgvc0LLsybs
IOYAbv8oq4zs13a5waS7TLUlqpHDv9XgER7sZafiP-J8hL29oCVpMQStki0ene9GK-vrOZvu9Cf83d8FQ0owOMsq5dBebl2mjJfvbaRvkPFTBTNgfOYegw9G
hoItu3PScEfb9KhGqZ2a07OVb9ZAQDAEvPCD_QfiwKOByX14dKEQswmrDT80jDHQjGTRTVP1fEk3ZhgA4WwzJdFEK55yQKWN8a8ZJkxkoBr8Hr7ip44ZpbKD
A9x09qInEQh1Fa5HvmbHbABz4l4wJuXu3-eczL8qf8eRSR9x8El4O-h06hp9F-nR7jYNF81zn_CV
}

