sprite $Printer [74x63/16z] {
xT09SYqX28LXQH0Kzh_UE_DUakxYQadc_0luYaE9mdeObTcmmb7Rj8HSor50qn1No92GaoJY98auII9EakWHbcN9RqcIjdqp4jArcmImmPlkKlNbKQ1sYUDr
R9SKOebiL3AA9HcNvFaubs2VIy_deRsGDjprKZACnuslY-VfZAJXk74fdaTp4aNZXZyUpuFNKe5TRoG8nWslY-V9h2J1k54fdeVsMe9jbqiUnkDSsaBfU1xW
DJMl4mPHDq_n6hX3QeiftUuHwroNudwRASQu75yeScYL8bLCITK4KsgsDaww7o9hKZUpdY6nNUC4gTcrbdbJ_fyMOc5SbhmlBx4krbogRJ7-5H__a_waXYbr
5SMKL51RpabOo7e2P5HA8TKkItLLAjTGr9PImGjp1W
}

