sprite $Public_WAN [115x70/16z] {
rTc9RkiW48NXJ7FEp9dtV-4hQcpHuXQd0Kltpxv-0dVnyhYK6UZApoI7sMDf1gf8KfGaPHPs7KYb5CJp27GfvMPBGC-K7rpBXj9X2q05AzA5WjfS4Cf0YtoK
lg6qkKDaWzbHuo9IDarKnk5Prw6wX3aYKjn5Ew-YLD8cYZtOZnHJJAImpsavTMvziffHpIdYkDryJxHE79fAl2LAxCInQM-8dWu0ZJWoWIUblvl8wCJHC05u
qip04inUdTOYFZyA-Zm_zSC4b59cIieN_xcnJkjUiRjB5m1AuSwIXvIwYbggYgDw4qsy_c_6q_z6ra-rQ0fh1jc7cYjnRKdoNR9ECo-P9d62M4oog4eR_qwI
F27HdY-Q9PTiEA-5x7j-EO_RIKPoFA_4b5WRJArbp23Pvd8RBifPMas9uQASfes7QPGgEKUhAKKxyyoL2deX-Na2HtV0NVFVJg5CjzDjZt3VHldZkRrjh2rk
b_RSehGl87I017yExUlUH1yKIg4HVGFz56bl6wrlZD8QqQiupeUDpUkYlzjkyeheKwh_p4oANqMVM2Yj3F9dqQSNwRODClnSYmZ_Qr7EPyD4AYBSltEnggHd
5F86hIP9bVIghKwP6rcrkyXX_p-fsqbvtYocCtKp2TFDfEpXgJl5il9kTvBQDb5uerbNeytlCfir4TrZIkdj-jPwzEkgh56hKJNhiIsgTTxPRY23AmjRvHVN
eahxfzlK7SdfZpBjduwNH0T0khQFw_DKaxFnJbqp06pDiKXhFqtIMG9WjdF3e0pdTN56ffHpNAGmz-ZJ85VA7lE2KZu0apR_GA8JNTt-pzbeyCHpPJsOk0HD
XHUsxeIiUvMvxl2m6NKS6PQM7nZk_p392Nl7-mS
}

