sprite $Router_with_Voice [55x55/16z] {
bTQ9TkCW38LX5g4hfFT_tq4aHlYOrjD_fXln5tH85wT3XI2gPgOge9B-fyAYviIRdmYNLmGrqmucghKICReleBmX5QQIgMQlKCx4ehz2zeUf-EN0P90oiJyT
dr4HKsdb4tSQxwjm-KIY9gSDoRUgvHjr1stYMVLHwAHwgn64nZlKgFLmkw9AgygzLUgyhH19k51-Q57he45fhydT5PymfxGxI1FGFP-p11DJ7ifT-qRewBY-
87zPKcsi9aknAHgbk-FUEqzIXvXHQr3Z656O-UiQCxVApEZWKKqhVqZMc305xwxbpEvuLYxrMLJ3lbau6ZFnAlOhpB7TtEnRYrS44TtNrF0zV3mSFLLgcFMv
7PiALkkOy9o0CPDvc6AAY7EQvRigTLjI4vznPwvcT-MZLY2c9BD-K8a58uw9gGKpmc1o1QeN91bTIaQ0V1iCCba4yBJLFy-Xl62YmNRCB2CAjJCrFJFfdqKQ
gijpjw5C-uy9It-aveLxBzGP0h-ZwyCT8cSSqRfyRRX9F_dfX24FCrAnBNMhhaRaBATSQ5Xr4mbkRDAFgdvfByaRji6sGBRLV6_vA3MFqXNR5fNzF7EMK3CS
bPOajkfZ6WxboLSrsvDucdXgLp50h4ISqZPb2xKgXpNrnJYYkdxTHfIU3d7LDb0MkmtEwvHYin7YH9wk9xRpwPRjoyUO2hDmiTc8znF9nEXsw-uuNObvb6k8
ivFrIiPGgcSH3dF4YDHUa-AA0lsdqr1_Sg7Exbr5HLwKb1_ly7vE-TVxoNFlDw9_Hd6l7BtSA__nplmV
}

