sprite $Router_with_Firewall [55x55/16z] {
dPQ9ZkiW34KXtl7__-zZInnQ7fNcQ47nvE0BJ5lIXWj5It7tKbJmIWV2OMr6S-QeVFsKfBWN4oO402GMQmMvVad562070ApbA7BnelWuOM8JUIzTwgu4UwZz
STSGsuJmVzYyuCuoWXCKtj9BMOveU66P0gZzOFMkbZ2db95CwGCsfWvYotc5fcvShUhjDSHsb0c8pVMns8iGfExffuP4aETIYBWuloCIZTJG4q5e4A6eeazC
ySADuMLYofdu9hnHB2vtC-MtXpLJQ2muDU16QpURwOJpaqS3Ncl5PQxiuV5eKnCRz7Oycfbsw0wqLXgvQhDTxQzL4r5JQTnJPvwLOG4ChLMgfZrZT8l5yQXC
YmKIwEpMKg9FpS9ga5fOegf8eJdAeY7S8ffPM8FGH8VMNXh8SA5M9C_T-TAqUB4lgijjf6xP9zKfRWSeWMtmujKyUApsHIdUsNW7fhGLMSxIFQmYvnpU9byR
GmmhfUufiUxY5HrZgDEQ1vvJ1YJHhWGgYpPcwXPO0r8d0oql2leBQhsdDQR7T4F-0g_tVkQig-MyjSgLD9wifk6m6hfQKULNuZI14W7MofFXYWA5zG2RMl_g
adXbCpD5WZNLR1U1igvvA7OfcaKx6zRgMTiD2o-su8h72LYiGzp3YsOLVYyZ0-bj1U75KSwpmyNOUlgSPCISMG-Uz8W1JkNe0VlcD_ytOHsyWtNspbRSkSxe
bRPmERNYutrop--Bw54wtvM3mrtv3pVpVm
}

