sprite $Router [55x55/16z] {
bTO9akKW281XGGI4-zztejHhjB9D_fdUKdvAUasv24dLpDtDL0dB_uIi8Ox2AkCh6iQwSADQApMMRaFY6p9bGeHVYCHgZv3DJHgU8p4tlZlAJLl5ovgQNnv8
OyDwtnY5hbHlzQdMqwsAAZtMDDsY0EYRmp4Xb09FPhnqDqocRl6T0DGk8we8K1kRwvzYDsa4yznsn3iP8cwbDJ7d756P-UUOkLN-gmOvWiRC6cF6YCAhQm2y
kFmc7_t6H3FbMODmM98jBaPGCyp35ZTUDSu8WX6Fn5pZi2w_3XUHdAv1arby4TXDpslgUIVWkA3c73Dc3B46TuKrByqfqSmMXRbrgY6er6I6vFFMTFwNeIBM
F7oUGqqa5dLpqeEfgiH_gWZ1I8z2LT6ZWyGwFPW6oqHusgggaYeBPibMpAn73L9jp2vOF_xthk6gz2lcVhXpscVAqa-PZopTMwb2dg387R8uwH8AeDoXM9ud
sg9AcKvPDCsoM3spGKCTqM1G06dOOJ9LNzsqeQgEJR2C06gJZT7AcevBE5MiekNtr1AXBOSXwAwSBvLXMQRiK90tvGgXcg_fjesKA9KRx5V-PbYcR9kAwiKr
6nFflYGsshQ2tRbkgmo3WVesE2kcotMQdv6pwy3kkzDzA2dHDgQ9UxfrgC9v6_6zr7rhTpnDZabJs8ca0uqHjw4inRK3cIDcbEB13KK1FZWBzTM5-kXIxQ6-
tjpj4zvzne_FazUzFuX-Hlcil1k-GT-VpFy1
}

