sprite $RPS [55x55/16z] {
lT27cYid38PX5P1WVF_t6m6_YuAtuEISpqtxsE-Y6UPsEwtnKDTfuKBrxYVr7YxEQiedgOUBmvJFqibSJlFFc4scf_sMYOY-v9a9pJYFc7bdPJvLY4M4YJ0o
hP54bSFXXvFTlDmJqlKX69NZWzT8yO7UCoL-ZW9Mb3DhzPwGhW_1E7JLiMIfZqhrK8d9khPI5IENEjoGzHwOtLEQIKcZML4PSpNKNbYjfcCp9J5Ru_hTV1z7
wixmFqjyydZNEKv0ihucJgmRgamwlvV54545pyplwReOeUB1tDt6GucBMM5IN-rCXRWKaXYh8zmU3eLwPcQ34ciGysTMIwdcxnao6T1yQsUvGj7Ni8K2smwC
nBozLukrhNKWIVMs5IenBpegCwK5ox_X5U9AfvdG7YVOXzYMhBmnd9WN1EltXolXRhosVe2ZxbqzQdZ3fbnRpxKE1HiiXKt5y6T222o7JTNxFQ2TvNnjMbf2
6zjgXas1Vi40iMaBz3lMtAtgOiIMN9ONR3DLOKg9loFPksQ4JMy_raq9gI6FHNyXgy3rM-hNozOZY6Ln9mzhLTATF5ds_1AnhE0IJsk51PTulApwASAorZ-2
LuVxwxNF5BUF5CCTgdy
}

