sprite $Secondary_Codec [73x55/16z] {
xPU9ikGW24M5Aohn__zta52Qs6zFrpwdCfRUbjEGsObQVqwZuJcUqvjvL9iyewbswqShqpEuwj5D17eANDJuESr5uASWH1EB_eQBT6h8m9SGuqFKHJbEYO4l
JPz-d4EKaGqG8ri88ZfNZfNddjXNUEwtC2f39Ddn-vOJWsaykAz4tlJOH_V8vXz8Y4w6ckr28kO4maZ6QaSIsvtxRDe4KFQ3PSOc0la2Wf4_4s4yYBjCujn5
tYUJVok9txPZjXKiSkuJ4AiObB2B7BjALY9iAZ4J8LR0GiyPlkQCc64J_H7ckwZ87JllGVouNm7FOuZ-YEbYvwAkvJ7HqTj4jJobXkYarDyJDNfSH2Bx9P7o
PJ2Bh9yfAaYeDpAbHFbQD8BjabMDkK8Kbx1TSV8I-_dr5edsu_2V_bQyYhE3qMsJ59Hc9tiAHI1sgeBii2TcwePAt0dG35nFrHvv_NZ2zLDHvNcfEQkKwek8
YcbyDFOZJgGPNuYQ8JZn5g0ncceJIt8BjEcgWnzLymhi7AYSBxkxwJ2H5gIiWPLfIK7Hvj5wsRheaX2QK-HDYLvec0q5UG_Koajnn-neiflGje3h3A8--5HK
VHIgAs0FojHClkw8Ov8PnApSOgfNfgZeGb8GuNhxihevsiUZCUhs_GRsW6Un0h4FrZGaiMsK0chgh20QEWg5TD9ghSKOTr7d8BVPwWfgj1E_NMgpvOmeBQ8f
MO6TZwFNIn3jN23THGODlTpgZBA2RCSOVHE1JZo3PtaJNSs8oGPq0esVjcEW68CT_IUY68wzqfP-0z7E3qJH5FSFoTREBqJM5A9WG_j4Q18lUmzcnTSSEZbU
Wp_od_Ok3xKtUTxsl-n_
}

