sprite $Secure_Endpoints_PC [56x52/16z] {
pTK7ZiGm28LXuCM866lkVzifI2bhEPcm_LT9uukjQY9rRwcyAX6PDvyjqVm4Hkfku5IOtRKsOvd6bN7WkLLt1CE79iIxWty1xctcruHSxYLv3ZTc_6m8DpTK
z6eWSUPUAYZdN83Wd76yZXDbt3RDn1ct3PyvZBSvtkXqw234kEIwc7YvbULsQIfZrmyJzsnpqzNrGcrk7zEWPQRaNQYq2tNHYMoteQuvj2QhAsDNjbQdjvk-
SMNaS6kITP4f9PnqBh-UldNxXBOoZd_P2Gz2xppEXxFALFe0Tpy-Zyf1O6jLtKtu9EbZcBkA-LDgeW14ejMJLQL8aj5V1Ki4MfBgYKmM1q-5_-aC-xHt1lsK
Kv9FxTC8UHUmPfrKJrI5bb0J344U
}

