sprite $Security_Manager [73x55/16z] {
rTS7SkCm341HeWF2_U-xb8PoA9FCM9l-rDjFt6q0puzps3lRnwNldJ3XZn2BBOyEmiVWNgeXWe-Y8-Ju7fZ3Apz2z5wdB62FMcWD2oxs0tLQY6c5iT0SN4BS
Gcirn5C0t3b26NmbzaRt3Pc5a7kHOyYKvNfhnVud95fAOIuzqTT2mYoFmOmhApsq_OnA7XEYT9lIGXTsA0NmL4Foh8PwBJIg8UfkXkApybf8dsyQ3NWIqhgc
nz0oOuW7qb5jeO7j8NWCAF2ia7PQoAOXbXF2U0PUGjP24wM7RcRApBelROTadLiXnW9aXp6qlHvI512KUIXo6RhUHpLagApq5kAXimeLE9KZn2HCTY8UEhEG
rr2Ned1t4sQRXJoRy4K8JHeJLQsjMSYtR3OtRwEVAu4rn5Hwriuu5iHjzUYSeL4O5AfJXyCxBUIHpIBa4NMqZeTFGf7pK6ylXQ55uvDGv4NuIXYODsCejhoA
jHgAAUA8p3iXjIdap7kXEGIz5tARSuzx8SCLpVpWVUG7ahiXZywM9vQSsnOXz34oXkR9ljcUa34WoLi25q3p7b-9J_gFKE-6F9gFtaTRJl6FXS0NVq3p7W6Q
GOgyAMp6ym_mp-g0VrBdqtvb_mC
}

