sprite $Secure_Router_subdued [55x55/16z] {
jTO7pgmw38PX-olP_vAlGWvnCc7ARUzVGJoAXo8HJoK0zW1a_5PseZlo9_c7aEZDZHyGaLbh9_W5veNox8BvHc539yJpcQ25V1jDvAaeCqTF64cB-QJmEQhS
eYBmkMCzoCpunM5L72eIV0p8x3FHB9VqVNhp95tKpU0QiszmSrXKp4ZIOeqeRYwJLTPG93N7fCrHzB8VoDqLeyrbCL7TrJoQNvYdUrsEikwcWyvzr9NLMT8-
ZybJtMoSJAYfOXPRL6BPrVfoyChcQTkLX9hRGisug-2k970oCy6sCDOTuKNjkH5Gyvh4owPjvL1-gMbZc-r_kQYTSM5dBBKnKksZUrA3bVkfDja9fRUes04L
gRUeCmosIyqpI1scCmnMkRafUd2pkmTrcs9ihocxodwaxpixgLOHII-RMbKFSSTb8cQWc3EqgyO7DHuS5Oj8RggfrCxcb7LCgVfmtcUCg0_BKhCyzmbzHvtB
F5L378vZ7xqF51gZWBecu7wMn8XrESUViZlGWfk2TKsMnUhJAPQ1nBw7pThkW5fidaoE3L1kZPqPnvrZPjpXSXYYLsntwYDM60zh7SG4IIHLhYkjAf9gQuox
TJqsCUDmEqldO5MfnVc5jHVcKbM2tbWeDcQYr1AeZN5Z8kAv9BsmlEoDc9_V9o_fkslZnnTHjyeIWV_ZNVdtD_E_
}

