sprite $Security_Management_color [55x51/16z] {
pT5LekGW48NXKrw4_UztIBZ4Q7-Qlrs-O43MRqkiQlcsvfegwT-KfRccWkcRs9khIp9z5-VAWh_DL-Q_iH0H9dmMiOWCnlWy7am58Bd7HCGyVGk8HcCrb46g
Thu9eKTo_MNxRsT64Bl4E2ArSmAoZUN4k0yZeZmvNLdzOtfJfAR4nFt3Hqm1ChScZRlZimDPRimPvdj6gtBbzJsRE-FoCyWVCa3TNSHRApE0tpC6UKi7wz_C
h5mPWTsDYRW5Qbe1Uy2YiHWr9X624NaOJhy_PzeP5Nd8EChCuXYjRYnMvZ5oS5E3PVoL0efKj8o0_e5Yb8qjdIN3Syy0xsnLgo1mxZda8Gi2TuRE3B0yWjIP
zU4qV1IEqs2bFcL1pUN82EI7EZEvZmQmnNe55m0-q5Blh9nKZvYPW7MiCj2PBHlxgoin7bYpVLbQjNUmqbaUAakw2Olw9WuqiTvGrvPX9ZQfsRnccfEPMCzW
PJZz-__InPJ3ZYjGhCEsijIN9I7ho02MJsB0paCpFekzdblADS5VDft5gtHdzTh_m4hqU329hV9QCHv7BvtZMVwAnM-iAZrEb_goPLdAV9jGrbzAv4yAo5_K
Fm
}

