sprite $Secure_Catalyst_Switch_subdued [55x51/16z] {
hTQ9SkGm20HGe0NA_t_nIbtfyh1XZnmzbspqoiBACUxrzjcK7xNhizb5bOWf7bEmhdkhWjjdugZJLwMFiHiVavUjJpFyA9EIcvbkt9qJ6YkkC_vKLsSdekxU
3suQouUruXdsoioYryXwAHe3c73MGeTjt4efngY13qnjOsHnAdADyUnVMDmPAf_HYs9rP0ZDOOaFdM5rOencvTux5z-bb86fgNNc0ucelHVLm5OFugh4FeHl
WTNJ65JDVOBxNfVjtoUaM9v7EF8EhXBRXz7n0O-LL6GtS3CamyiKLbLbL5sM36wNUHIPbFRbJWnkC4zohKmONOajjvSa6TqxozTof5ZOnE8j6bCWbZ366J5_
c3FwSrTart6PI4QzMPfwImPQejW9FZBlh1OlrLckUDa0X8Bt3U1sP3NMKxkdY5ec5cXgkTHVcPlXLPd9DNPTyS6teongAnNskCQKX5JoyBqbEUJCbY7ZKMVq
wc2O6KvLIknnDZ1LfSHwPMPkwlvXlJInD0O3Wp4ZMoRNMQ-8jJlYWSnheB_AF4g4-n_OedYQORoKOniRawPsXeWDWRhv74lN4Z_1T2S_pmfQuiHgrn-IoBz_
C_n4fBxuxVKN
}

