sprite $Secure_Endpoints_Laptop [65x54/16z] {
lTO7akGW38LX7h98echkVzl5ImqjUy5hTVec1_sjZhRhA4kr4Obm0uj8IHPPgYgWZJDkymqeYR1QW42qdV45GgePheireetJNHk748X4Ha38jtb_tnO28-i0
pUS1p0lS0kc_WVxtQOEk0deUVp-P0dfUVxK7nXmSJ04rfbBcW9x2wm6y523lF9tcPu4Jv-ZN7ZZXrm9R22y5ECm3Qc1cZ7Du8T37vu5je7cWlyI4LK1H0Je4
U6SAf9_q232R0wW_zOa0wmtY_G0FZm1Ll1Q0l1eebi36_zwDS2_S2yeN0luGmCns3kH7e0RGjiAA2lHZepuwB-TcXUFHcQGMmfI7ty5h-lnWh20vMYHzXj9G
5AlCS0f0R404k0EAkHYCozStWYaW4dM1nhYXm2eGzq0ss0CPUW4fYUyBHVGAoD8K2pcimF84jGAaoLRgZeZIn62KfQ5-2oxazAl8GcppY38Nt43B0btSWkGU
qde5vENVC90iKPIrKgI_NOXoeTRzarpZBA-8z0S
}

