sprite $Security_Management_subdued [55x51/16z] {
nTO74gCu44RX_tLG-VudtfMmwA784nyP-dEgP6YVjpMW_Kn3fRyfE_cq5kXD-F_gqnAzY-miU9l_AjFJDanwus8mG-9f4ZPO6iAsWPROFRbWgE81AmK6Yzyw
oNAodUe7OBsen9SvCgzCmjp6XZiIcwVu8PFwfU5ZDvpTCrkcwCAnvTtl6T9ulB2wSyleI08G_UASnRV18j2QX_VTp5SM_7WRsSBu-36BOXapH2J58at5qaMs
mRApjS6iWsHbaJCNxOYPv0j3WmKYRzcOCit6kMTrmj8a2v-5TxhMJbaYMSvSafSwPoP9-8Begj0vCtq3ng7K6QltOc8hTC5iZhe1veLEMQbPeJrhYI97FjJU
d34lPZjomfh9SZgRu2INJPPIB7CPS_x41Oh9caayIxAsikReMNXErilSXaOdl-jaksnbRTS_P-bBJ8QFyf8bEewyOgwp_0-mj7SVik1nRLkfT_5pwYV_lVu7
}

