sprite $Secure_MARS [73x55/16z] {
vTPNWlCg38PXVMg8UF_xFGW8CNCyrRdxtnJtP-JfG1pt2wJpkDyHwTHQuqwrTNJ767TYhVLnDCXmDnkGu6uI2ONmtPxGPp5QX1RBbtqD0VHgKLz1UibG2m0p
evFumj4ELLKPJyXhDPKFBekANZ_hW6OWIagd8yAWBCcnIw-xW8Oao6KoAuYcz3LaEfD9ORpjDJdVBhC9hGObm1YFDunJKhjiXmP5CEKnp-1MOY1y1Rdjb4aE
XVxXXKwffdQHJsXB2K22H9gRe1MC2UONNK52C4a27NB3FjAF8P0OmLBG9_sCy-ZdKF5JHcHA132lkrYtXuRoXLCcTCxwsGHgsTh9G8TC2LvcBkk44sJIq_vY
SSK9ofcjFTICu2OpWWur7Yz8QSH51-2oe9LtIEaLUtUEqqGOvIpgdZi-WOhH2Zfkx76qwfe-Ky05R20wGIezJcYTQX1Vdw248gTxFfnGX3B0ecIHEqQknA-J
lRrAD6TE5ESAo8sWvWwBdeDcQAIiC_ipdJNH1Z5f0Kg4qO1iENc4BBRgqMfMliUM4efwH31vmaeh56kltPbAEX-W0WXACQE4YX1j0-d6r4JMH3Msr1mYrFBg
e2y6gbqPre3E3-CIwjeXsvq-q3gpZREQ4vsA9eX28oNGANXpEEfg3BBQeS94o74q37HEIXxpklg0x90XhnXZHT4NnHwEv69ZFfj8YQ0nRn0MuSe0HClwBf1O
p1UG4BoE78cM6Bc0YD6bzRdv0WgDqpgU_uG0_UQgTKaNz8Mq5IQW4SJ7c5z9Ytly7upYPkQbpjyuvKBwYip7isErIJVwToGxtYCXZhT8oxahrUDVAjxb8Dxa
0F4Uvpy
}

