sprite $Secure_Server [32x55/16z] {
xPK5bWGX34IJAP8gxd_WSUCjaBNdyzlxusfGNo9OatX3xpm3I74XpuoXxW4wszL_FETU4_eJvPuu5AYWCvDtnYByglxQUgdmBQBrfLTQQyQT1omtwH_Ci2rV
nBP-HVcP4LpxX9y1vvxfXamu5Xu6KeBbmlkr2dJClJjtFjmZulhCYOUz4M_-faUFh-DxzFsEui7euu4LyC4Odm-wo6d-s_fXKdz_8vVpd_ym__iBHO4NgA1h
Elth-VzFlje_KEm_s_sBi1C
}

