sprite $Secure_Switch_subdued [55x51/16z] {
dTO7aiGW34HHgLjGll-9nzZWBiOH_WJ7LsBpckLbj6ohccbJAVYzI8KiEOVRI1whMdBo3vNRZr9XyP79HMEuVg4-DYV8ZU4kLxRdACKBirC-njGLCtzZ3Z7T
vfyNcRYttUMaWlAAM18ZO2PsQhjQKCyk5eG_vc0jDGOxvpshI4og2xnEZFHn5cjjeEE8mJYUvR0znDRsWOZhOCveYPLmpNJjcWNnoCnPLMM2Z50yVPzXKpjJ
iJwIWfro5bLPf7e_UHo5M5U8rGA6WMarklMCVbGL2kePzlFNGQCw5lx_7HNTu3QgPxHJw9X6YONR6uEGfk6PvPoakaNwBSlgZsaWKhHaBbdEIGEvtrmUwfgr
oa3gCCZqnEJeOaGGwOafVJ1HIE0RK-Isx3JAOeBLdxo4I2CCri8munJ3mXdc2sQOXKqn6sP4YzSipsLpQlA_rny
}

