sprite $Secure_Catalyst_Switch_color_ [55x51/16z] {
bTG7akGW38LX2H0Allzz5_7eu5gDg_hVdU0MdtCDDOlhjyBQKbVyscMfN6LKzL4bwd6bceshY8YhcdZiCotRh1vfCgrdbDMZkLclOigudFtD6g5M3NMpWHgt
rWVgJ8ZVdxGr7-ZEzZ86xRtXM23CEVncrujrGdqW8gedXmaQP_QrEUwZimbcScBCAhP7F0JTMICCxmmgQo9tDlF_x6kotSmj8Q8zcC9fcFeKBBKhsJoD1New
oItXrozjNt5E4PZFa-JdnwaXFIh7ScVwtNRDF495FToWz3i7kzU99IB6K1cfcRhg8qCZbOxFDtrYKqyMAz7rpPE5wMaMJ5YEybWDUpC_JdX0nOTr8i5uh_UX
xcxT_7qu4yghD4-Kp7G_qJ5toGOJPyGZ6GPZFvkbS3JJJb_bHUqFc5Oz6NqrbWCRLB5szOgHn64cUCEH7SRUNgnnXaKpLRALTdhV4Z-CX0vppMpcfWE1UHvm
-ix048xcMIWETGhVQLyCHKX_9O7vMc-u6n-6p975FKkqYhWgTh8kDoMVwwdPKKJohOZW7XWK3VCl1bV0LGfPtxPAv6hxfNqxJLka951uvvWO2-4cQSqcKOFw
Pd0vaPeD8gWRWyjwpLhE6fRUMVGzYaevKoO5cxJpYXbchFynPOoqOdEHFl2N8bJp25DrRxbANrGgfjC-Pz49TLmFh1Qgkb2SvYzDokQF2gVPVqMVEraN3wVv
S8hsz-X9jGVteAXP_DfI_m
}

