sprite $Secure_Switch_color [55x51/16z] {
lTG7sbif38LX0Mh0_lSxvz4rSi7jUf9yxiHlpj-9VCnp3IUeESusFPJhcHpEWQsMZn6LLLMuEHpgd7CmZ7rH8RZrGa-mvPArLpqmLEFy0okqLHgoOCpSrgtn
pIkmlSQSJ8vRAuMlhxZINhcmQRAgE9MRdh0gADPSZhYiuuoFShYmB3Oz_-jaUurG4vHiJKKbgm-ioCg3gU9qh-fD3LEw2jR1oYScG9b33J2L-fvboMOtf7mC
bfQ9PMhSzFggBuQEmMRFOofYgsIHb7UCA0T7iaZhMxO6Ux1XrqJi9jb-6PgPGurWVisEk-E8QQieI3JStIv09Pw43ROxcvUrwvHGy-ppMdTSkrO2mvDr8DiV
XTP3n5t7Et2JutmLF9FxgM0efb3LpFfDabDpB1PJM-sUNQUIMQNtR6XCFRBsZWtCuBOnG2aROm2G1JOM_tmPR9RvIFFSHLqB68ziVjbW8fdvTbVzabgHkH8n
RVtBGSyjnfJ9F9bQVDZZNx0nH4VllVaf9xHgPnWJgd5taW7mUOQi_CIOVcBqXetvBEELFcS-Vyd9Vr94Fiu6zHy
}

