sprite $Secure_Router_color [55x55/16z] {
dTO9ak0g281XH124-z_tDIGsLcTxDNzjevDFwJrm4vAeUMGgXF1_md4GYmuwy1E9kTkKmTHx9nuoOqFm7UNXXAr2okjVu30tORn6OcxZ7g6wAUDzhEQADuhY
gevFzRYGxjJa_XRFgoDtfKxlgJjTxgBMFXYhs-um9cm0dswwOJ5r6xbinBSH8JP07jCLLiDDcE31fSY8MSn7ZQZCfqEEUgbUGyLIVySKDna_BJUuDHuhngKm
DiLSZfMR9fFb6W3BOZBwOhcdvhWkE-EQHoewzqWoSpa_-N9nL8h_77Ly4OQRNf_1gsfofFd9L3VPQlNCfh1l9vbhpBWpXBDTXI3e8ZKbkSyR1Qox-ecuc9Eu
JLq9uO8KwwNo_qJFfhbeiafafCNuToiL5LChjkCnrcsbDcP-o_JSurHN5jbyJ4KlUw7AVLTgkGiKUKAbhb1QarTa1NS5a4vPT3Fri7fbFoq5GC4QDAImOIeL
trtQGw768GXPGvQT2UsCusvDrSqZWXNx5g7Lmh1fgKnkbI5ehIP06wKYlLEnE_oiZYxbrcgd6W1O6xof5TxiMMoAhpfaww0wgbnDXViXKTDS3UAPZx2sSZM1
r6Uad95CeUaAxFUVNToNQqSuTjXDtCljGy7OFmmabka-9EudFzlSW9LwH2dCisHsi7AwlfBRc6RrqEWz_zgmxavon8fIL7pphQWOYc2FRXYtOf7Lj_Rblc9D
_h2ww-gA0TMGfIwX_c7uXoa-lk6TILlzCXjlxvDdTbO7uTVRwpKhzFwkNDs_A__Zc_b_
}

