sprite $Server [32x55/16z] {
vPLL0eCn28FPBqbw_mFFVOFCzNl5QO7er5BOpSNY4XtGrdJIE0TpZjMMSZQMSXt9PUHyilpryNN2KhH6C7G66Pe0hZXAuGdzauoy0v39GI60O6e_btTTeF8V
qPNv0MLzil_Zx_ul4t7wlzi-WY4CD3Gn6R0NzX_NpVyr_PaO_FoJ-O9__lznzwE-F-gYOtc_PW
}

