sprite $Set_Top [73x55/16z] {
xTS5akCm443HQgRxttUbrZ17ylByn6o_8YE0rtaEqydpogSJhdAIUcHDnn3EGXlIW0XEeuOSp_E6wDYXE-YuFnPYEeqdLCx7DPGXnux47IJptuDiJU-XZlUI
Ra4geaAm5ys3zGuQ2G3k122gsb0rn41x0JTKzn1jGtGFvLLGDOJR4Bw0aFR22LasP1DItqi7P54BCbECdikqg9iALFDy3gMQHaZMn_dz47VGSF8P55fIfVLn
2bu6MW6y86jdGMuBol7p-ZYZg22l95rGL2qftQoXKZLbgviAYcOQSZVqEHSL4NLJJjb8G-QEn7jHGrtwwE0IgOiWVWO5RqFw2CM0T1ko9z3806adX7W2-VWH
xCNrMCnC64YOUKtV-p6BC8ZEUXele1bHJnGzFYZlBuvYgjLBoFecHQ0VAJD3DZV2g9TbPeoS4P7qGwIREv94lLyVy1A8p7fPPjtITzzzvrSvu1Svbtrb_m
}

