sprite $Shield [72x57/16z] {
tTS7igCm381X2nkh-VxdNImOLjGe0rl_z0HzezTVKcPz7EU9aHTYOvZmIKQe26LuL4OHLU4C3ylS7OHDgPzsL_iWmIOqP_11EWQ74cncQiW1v5sbEwxPoRup
HzgkcY3xtdBGdEABEiNtLpfKVCC3PrnEKsFSiO7HEQChx8o-Tvtg2pf3zL5tkFho_-EWB-gWRtNgSeuxwq2_y4lxo9a3-mQMNINbFQEwTKegiei7sBTnM0pQ
xrFQBe5qA7j6zUYKRnqIdVSH93lDDs5d6M1HqPu88T5wYJfaBOmOHAvl72HQcIUECNg-3t_XCAkhExoUeavPbx6JEUoOy3viZ4_w-59y7z5zOlFBEUpeYUFw
Nntvrl69nVt4JnpFFN5yOmBK5noQXZBf1mTGFoKL4XIvSs0K3SHbagfSEL1OGpN58QK1zTJ9fE6QOFyqyT61IV_2cQGH-kTXwq0LfmGfBdrGVpfGn2yJppvD
f0ApmlTAksx-7a18xjD-skpenQarbJA_2KFfZwvFojfkKyhs-RvFERFUINrRvFOXrVpM-_SV
}

