sprite $Smart_Pump [42x96/16z] {
xTL7cWCX34HX5MWaGTt_lCuPC-Zppk6jEloT0y5iUMaH1zpYKYDxZ8c8UYbcSab9awSvHE2upDUPF28hQobMK_iigjPKmrNnluo_IxwG3-VxJRBxfLZ8Qryd
BNRrsAUBDnb0eGa0cSiBxfSrAzayAILQLbf7KbPgKg9xKeft96Mb9YMY8IT5gMjvsMbEYjAIKfmrAT4QSbAKlfGNQaafJarA17KjeMRcf9i5sSpgJ1O-59yW
U_GZYeNiLUgU1iGN4eAzT96_nT6zEdVrMcCXsVFN_cto9w5sRFKLpyQZd_p9dqIvfgINItYGmLd-iaIP1Narg2Ark7GoCC8WMnalI0UfnqiQf0tIk2l6HVNv
Fcqu8PCn8nroR0i
}

