sprite $SSL_Terminator [73x55/16z] {
xT67Skmm28LXYa0WlV_xNgHbhiisnyhq_Ec5Ryvu4QslPpYSjbv8qt5RoQSKZWlXIYGUKa22gyc4d70ryW4PhMSJObgD4rflGixh-OGAHuJt8evAGX71tIYk
4vBu3f3l155SIq8Y32GtYZC25jaWWY8t2gK0xI44kTCu0pn0A9SgU8GmFZP8WwMB403BrZWZ4D64L83rKW41YixoZ47q9IJbGmGZVeBQW9fgWQAQCNoF9FUL
ePKz91UX31EI4yGWTnObn6eFg2QK5Nd_nX1XqLcU0LjBg39elPICEVc_UHPGC3-7KBIU86cvoCPlh6xPkmyJrlWkimsAHI6P3MXNpOzp4zlACvIn9ZusQAjg
NhmleUO1lLjaodW5Ag2jEqWW2PKZ90WN8UiJobVDFI0tyyURCi0NAFzJm1_Geu0a87SRxsFE2Eb3wgEckMWWUsXK6Iwaq-aJCj1jaVw7b2v2OqA5EZxfjaX1
F3E16NwgjZZCCGgsBQfGFCjHdnxsc1Fbun7m3J9apt8KchzfZCaQbjuBjWro9D-dz0PgoUGbKUzChMUjDJuTcdv6ibZJaFik0MkPjt6q1u98v9o2p-UKvVFF
ScJM0tYVWohOuP38RsI8XEqqycxQZrMvLutRl_wottBGVid1b9QTVm
}

