sprite $Storage [73x55/16z] {
xTFXSkCW30HWImAGuFtVzrWCCtXCsoJodxlhjctmZlL5Vo3IweyIdE9FLJYMO_0aPciI72PV65A316V77v5qIDaVxP2u7HcGEqz3mUs43bbmEy4w54CChjyG
1-JElmybjvC6XAprcbkzVHjGjTOBRl61u4RB67gv7XlbIAYOXLi83o7bbCAtDJBgc0V41mbsp3dtBwI3SBxK4JNZkAidDBVakJFbbdlDg6bJbm5H388MOGcH
06tg4xhLOe0ge7nDdtYzbkwK9w1wRYJ-ZJga3TApK_mi4ugg1P-wGYZ6wqO2Pa9BC862hpLySDVQYisDoWx2nxw6lpfrRbGS41n0jKjtIFUGJcXri54Oa7q6
WO4023aXMuC9imRfhkPUjxyonW6L0Uqcx5i83EQl6nqnwnnIpP4Ofrjz24wCskeOBfQE2HakDB6SOJmaJAHlQf60Y10Tf1CoJS8qmnBps29UwxbTHh-yFBUR
k-CogAhDxEko3E5fYRsUKhzFAULd0yYhAI3BJO3Xosz-ynjzoY5zo27IPvm_
}

