sprite $Surgeon [46x53/16z] {
pTHd6lGg28RXm8iYiF_z7kVIJ25nalFrv_UTOjqEGSt3tHJRPL2FdZ-wzBNRNVVgLwmnyvdI1KvyYUjqDllwCzoT5W5u12cgPdokKOGf1IbOQ80F0UUQLfhE
D6CH_mgjJQl8YucKgdMbsvXjLQsrgggPk-jQvvLSQvewSGLjPwtqOkNrJ5S-roIUzFf7UbmywoQyhSBWBws2RHr4_QKjunoZg4rQ1RnzZm2HqfEq-rQU8Jrm
ikledfml1vZf6gBEGLvF2TJowbZbbUqewvxo-PQoMbhIvhrA2SF2guXClklMxE4D-Kvh0ao-QsjT3owVM86X1v-uwyG7PjvrVV21f_xu6NWqVkdEFIP-QP-t
9raOw5rtxgP9k-x_8VIXEpSzQ9UEoQDHrgedscYyUhlMy-KMJZUrRl3GxQOshX7bhdQn2DpMwk5yMrk4qs_I_azfFk2Njgp3ZlcYyF3hRFOV
}

