sprite $Surveillance_Camera [98x76/16z] {
tTO7ekiu28LX3aP2oFlVxyWnZZE-3INXjV_Ls_G5d4P44ErhGbq5D8BqDQqk8DZujrLPtfwKRJKA7NyjdDHIrtKmZHEhwwWkYSacQAPGVf4WYTL_HMWbhtoX
w4seYVqYmVvweQ-cYRLV8woMBdHhsK8VHbAs2sua2jsDHC4pInISiJTtcI43SU5QXf26z5D8K5oGrOaKPG1AkcxrZ6u7WoZrtRs2HX2zmA_KprH0PpZIuplD
JA_LxTV7cfaTFuPxz4MoxfbPgrzKQdb8P2DyUAKVGty40eOCGkz32FsS1WG7xa8vXkW82E9NmO70478EeHG8VMP9JXGNX2BfBcXyXD6-fWwA984bEN1Tar8e
zC-NLEIXn_FlQ-f2iI1NGOGneYECcDtPnMPMGD4mX8URpdxsjPjo44DOADno2iAWxmAB74AP4Nn9uiS733LJ2bTsGVXn07ZU2OnSc9r1U8JZTBxc2dZhgHc4
NG3uYt3AJymWnoaSQqw0cGdF1FRxqeHGEHnSM2O4ZGlOVW4o152y8RJmwOnHCLFGt9qfThxd5_fTbngCQtwXvow4VdEp6HT5p2_3t9fmNGVZqhDByZMLSyl-
-ylEv-x9UnD2-GYW-I4gWedv2DDNGX2Acuym5-9xgjDtfFEbL2D4CNyiFBCdgpyJuZjw9dKY3I04YEB0AqIJRny83ZpTZIZynVdI77YbObyPB6fl07nJrghy
3s4kpKQwqEjXKTjgMeHlYTIsdrz0Rmb5RQ_Tij4xp_Sv73bINK3l3Kiv5DKoSVn_
}

