sprite $Tablet [73x63/16z] {
xT87WkKW281X1H74-zztiKnXkcNx_E-b9rzg677zAE5tel0Ygfi9WOEuRYTu_ufQh1_rvMTamKU5lpGW5mAj1-QGLXTZNKyfK5KVeMvKIGqIIaz1J8kH6DGS
XlWiYCi1crIrO0G7hLDO6YJWYx2UT0XVGDZ7BeU_teGJSXbaGV01FXPVR_e0Mcn0wHXA7Ief9GHC8uF6vCkr8yiZ5AB_825yEGUb4E0SeWx50uWcH6HGG9lO
3wF1j0BH0vG71DGpo5g04b6UKCuDYfHR6BEr0kNy1D5OywT0R7F1mcE8UK3SmcWmhq2SsKFm05cu0Z5hWzH3QHKYSpmKTw7oDeIBK3QdQZM9hGE8ZT4EoI5K
JHcGo8J48XHh0H8ZRa7cF43nrXKr26GN6ccHyW2LNKWxL0Q4fKLzidT54qgt8Be5yGL838fo2O9o25KTK3g6h6AGg9v36WFEkOngfNr8vcpkuZO4kMv2KQgJ
geUqV3cjBWUjzVT2tv1SWWJr2gGOK2v0Wk47
}

