sprite $telepresence_kiosk [56x75/16z] {
xTS7qlCe381X0G8XoVS_xuABW0dOdxDJ_lQcboTAjms0MVHLaX4AC_L2uiw4NoKLPbMcu5yKY5KB4_BkLPv4Iup-PSZ_puLtpTpDgmhMvQpWO5r0wt2nERZ9
urMSEZThwgpY7F4iSk2ZDN6upSDFb-mo0WJHRRAJqBaqSH1mLW087ywgpc6qnWTCLxGxeTuvtYPf6foSxjnHSQZjpjeWEmZNtSoTfS49XH2bTsIDRfYd4KhX
Wl9Jbs4ljNcuTh6vUBYW4vSFbs-SxvsnqUNUqSxiebHtt97bSbRdvFXjSFVwCkLIOQCZSsrWtCwakeEPuzaynUgyTFECzOxhBdvy3d6OnpipLwkiStgzdzBc
NSgSrPpumpdkdAnSQix1KRRd6KMUv_7boERTk6HVBA4pFXqyE4WoYV7HWNE-x2o_x-7HpPkvskWmXJ8tnZB69rmwY-n7nwx-PAb-VegdKr6vzZiyTYBQVZpY
W3xTmAu7KNCkPGJmH1u0St8Vyqvd5mcccRFT1O_zanjPk_XkdlNenWh_uJnxGL_E-wtSF_VFvJkNravmpJph3QIqojYqkiYSx4ktZFColcCErj6IRTz-3XB3
CcJzcyfVcAqmbBVADiI_OW2OvMMviFy
}

