sprite $Telepresence_Endpoint [55x55/16z] {
xT57jYCX341H4HMe_Q-tPJaX6fkYEep-Ep2yH8ZKTgDuKxAREbNCk1EpEbMKmau9rIapjUECOTmDhx5gBErsaQ6nd7FQcW-scsUhZqXJbc1LwXcLUs79GYvM
p_AQmOILWSM29Gwir7ABb3Mgri2o7CSXUMJMPnPLQH8_CguQrkfOFUwXO_N1L0cZvHaz67k65ZLjdt77q36S7J8iMMocMe8-N34exQOAz8LExJ9I9JgOB9pz
MukU4QcwnuI4obR_PioKY37BCtumzemLMCQiC3paxwSCz21oPqpiMNgnt3DkxvXL3ImVpxunStDMlZ7-RqncJ9xb1UEUGNW6AnPXLHG3NjObgssIbD3bJsiL
QTEuAuE5_AwTg8B5xNJZRkSe1l05FCCIZCKpBCDOFiEuP5_Xzi_wYQwfI9SKcDjMlm
}

