sprite $Telepresence_Exchange [73x55/16z] {
hTS7cgCm341XoUhs_U-xiiLuoP2GQIy111_xKxOZ-lXzZkNqNpOb7psCwJUnHH_fTCNR003Vf7q-Lj0Rvpr4CILlDo6iiDtd8tFwDKG7T1D2HRTz7SAlGC7q
l3QNWXhTnb4GCrqNGgXrXfG3Na_QouQk7J-G2we3_A8xg06M1olQqXqaV0cHM0gSBLKu9U5BmY87T8cGQs24QkwNzAGDlOvXGwlsNDA2L3HdbVeSEojD2656
klQdjC_Svsz8kI7fggQTq0g1ze6KBkqxmdNDJ23ZauEpniJwKKdF8O8CLNLF-_QEIFLMAiXUGB8TR4J4sqTw0GaSZsPSa-cCscF7SKkfjdlnNf0oGbFBb70w
QnHgnoU_bQYjr1vRpkXcsb1ijIUbPx7Qas8KvDO0KDtS5O_9w7biRlbLgNBqTFe1rJloZ8_fDUGpHQZ4tMCo1H5aQExUzlJgqNmcSCGvIq-ZeFBLtTQ4wfcf
oWRgDuqMSu8QSyEbNA6QAXFUzt5EuLJx0XJkPhQspo4o8xn0iQ4mkKd_GpA6wtz8Lnwn9sqtSLqmGn-dUdpaiVERweespnuNwFkDQ_63-lWEvETkcIgKk6eQ
fzRXXjXoGtJBL27YLGCzGvAh1j1oumVaD6ERMF2QTSDTD2g2iwHwGD98gUub0AarJ7mCFsRQakheMOG9ymaIToT4PW3cEZk0vrgcv20vTmBTa7Mj8hYl8XTb
pAJtX8J7XcO2ig3CQbFGyAg7Z9qp0ipBIQu_GO7j0sBm4_JH8tJypZ7LCxHgs1qQCxVY3YYuYZDafBo-GYBq2IBi0TZMouxJ7VNgyOviXAuZCZe_GXqnPvcJ
0fsWg1uX2UFvTNR_13bGlQDwoWrrgU818k4slv9hUe0wWI-eRgxVlsopt9tVplt_er6uQmDPQCvEvLsX-pj2c3LTw0gvxqk_WBIl5nGnrwFoMUovTZR4AfNo
6H9NTYKtCYteNS__gEbwojyPFlucH_yZvy_-b_qF
}

