sprite $Telepresence_Endpoint_twin_display [73x55/16z] {
xTU7ZgKw383XkCYERTx_UMymPUXmbxDz_scMGZvHfXq0ZVSf05Zu-y90mqsPtiHg7irnWRU9UuGRmTl8UgZY-sf2X6-Z4NfVGaRliuIOtiOZzBfV6I8u3RcF
yBGlI9YXd4UzKyu3PXaXuJ86K7OZiWYMYrYs45KtWN7Lt7WGHVACuGQA6IBlMfgpH1k3HwZNKU42YYLKkxwWDgBdRB20x2a4tcNIhyM4da8iGW-WRd5s3S8z
P5t7C-G9gVAqDDqOZ9mTZY0WmZLK4_89ujmz7AzfIab8rv14r1MavhsJK5R7gscXpoQgwXfgAol8V3eZsJ_--Ihl8V4HgbMk7ZzglOOqrX2UFBKb103t44St
duPsNoZMMaS8pGnl8Uc67FAeJ3TGT447KBQ7iC04rGtanv0FaDaAYlyFnKF81WWBnGH1VuWKoAUzXMB8sowB8Lr0RcOHOUQvPzZ91n3WMBzvEUUZAa17uHgg
KCvZCwDo7jWNP78kKJKpXNE8VG5PrIaULdNACkMvD56cr6E6Lab2OiUvE-Lvna4BX7dwGz16tIdMDq3MYbtUPovb5TRrgOGpj4e6hHedRI0mduhCeQoIECc5
b-b-7LkGxoso-EPyLNo-V_sh-qGH6l4P1om-aS77NcN_1m
}

