sprite $touchscreen [61x48/16z] {
tTQ7heOm28RX0X-OLE__UWyOCUvvzlllyTWsarAaTa-gKjos_gwzMnZfrwt6TxDWqlWJ5PftZebSDzKj2LRfPfOfktPlXFDqMg_9ujpC08Hl9C65spYnXANe
cYLYrw0wOBuNYPac5hwRBZ5DOjxxG3kuZCN_5n-oNuVv4kPJp0lC_n3tJVyXCi6Bdw8N66gFCSmcUD0q9Y9C6Iz-KblWwq7j6KxxUDjht2TbJ00g6Sr-mfTZ
BXb_9TPeYbKdM1Md6C-mBZ6-5-iFuD30z1_0PJmat2Si_QSCZcLCT_2itSbW3vzhlOGLEpOv0hVCkAMZ72iwsrbwEmkU0qtjAfFSM3itpIuRzrpeF9v6nMtN
I7Ljk9i5anBwnTZRrFP1ZTiF
}

