sprite $Transcoder [73x55/16z] {
vTU7afjA48NX3jDfvltVzo9wHceAT97BsVivKMVDJt1SH1_Vpp4x_Vli9HyzJFXxY4KVFaOt_5xMnoOOlnV7rkbEty_7nfak802UnrnFU8RE41wGRjVqDaIG
y7QjeMXNDvHkrzGYGoUlKsxNb27vxf3Cq0d1rAJ0qxgy3J4al5n9teJqtItX_PfqXdRC-jBcfJND7pbNVM7E3xr2GlKdhDSnsq9oMXC1oI7KyF1nXeIgica0
V5XJJjYU8Sk7HqfD5M4IMOTKLssKCD-0PKWGAZA5XHKt6Igh4LGeCmG7P5AZ6m5iTbW93bg6J8-FLav1Ur1MCsibT7mqzJustSpsbsrBgw7_NHdsc-rZXKpf
DiIN8LAp63Eq4_dsEygJOgJkPfRVafTJhjSSKtOoj2pAIxExrMEKq7U8SGwf-PC9itfwkvgMJWaHwRE9i64lpgiHnYXw92S0yV2D8Up4bzCQBW3K3o6T4038
OYEGqADeTJKglmzyF0H2rNo_jsJnKbSNgB1VXD0YZY6tKyZmAaIO0DQpSGqPIUouNCev3nFdk_A9033FCKWSuOB0kh7Gv_eupn20egUnYuc0xV1UqVQZ9EkO
Ofx6GECW9fPORDrG60CWRtIjCXPjuw17ydYYyguLvRZwwynnqXzYKKYKj_VezJuC4ezRAyamMRx9j5QCyQ6ECEdbQkD30KihgyCYuqC62z-i7uUehFhZG_Jt
XfmNgVcoVYt-epheFwZpmpxB_Wy
}

