sprite $UCS_C_Series_Server [72x28/16z] {
xT17egD038HXgvHApVtlEmBd77gMxxU1Mdq4uLYc6sncLCPKMMEmBOLC1LtVQIIcYytHwMuTJ3WBpQo5FcE7q_wgR6VGtKK4vYhcjax_ibowrO4wH4sQWkCt
foAYXMYYVnRU-yjuT08QuG1ycwVuhhnnpWzXY5D9l2wuCMDpij5qU1p0zCX3bDtBd9bPpMnE21HYiQQz1KVchLC7fIicrEpac46JNVAzCrevDCXCdZuBd94y
zDPPkhDJ34HbUB3MnM9Nh5AyB2wTgYAyMf0sofJrhd5ekN5S-u326YBY7R8yhAeGgNs00KtNBubJ0u3NQ6VGW1ldz0RlOrIVNQBFrNkkYkMcl_YV6277TAJy
0m
}

