sprite $UCS_Express [55x55/16z] {
ZPO9bkCm20KbnARF_UyxkCspfObwgLxXKO6Gn5OxG6mEH0JWnjJ-0gaZ4bn40bVwLJ94O9eAZy4iQlDA6FqcmPMfln2huqTH4J0fPpN54D2pH1xXGcV48_pK
a15GfkyOYW2Vh2cTHiBZYCpoTiiprmT_on1Fxz2hfVUDSks9__VeifZQboSRp4JzBife1kZLFA2PV3tYH-kj61afmXzB0oP9UTTVVjjLqPqoXBuZkggAQdcK
ENqehyjLeVwCQG7JebAhDagx8qFOscpt-jui6HLNksfMcDOAPBLw9jdUThLyUncjj3kyBPNUr8hxHT20lzQxjzKo4teq_rgc1-o5gOQarTf1U2EKzg1okVtw
xsYb1kB0j0rtJqEhMrV_Nvi8jjJyMpYj3r9JFsiop2_CZvhZgCcr4xUKpXgEchQ4NJknNEhyq2BD-U3peZOuhLsagpONwggxUAgFbPNUMw6RXRXvH6xwM0bz
MkKWeYQjEdwjoRSbgrJb4VKDr5HbrRW9UJa8HDrEug94twrh9-KXYHUtMAWoGJ5xwwC-oXlAiI3LpIh6Q0OvUBp6e5QK5seH1oyBVObwlRowFEEJvwtf4lNE
QXEnKjvMgDkZ88qpwJ7s9sFn1sInmchel_8sExR3JXHlitCxeR50E3HBT4z7i67E0fDc1BOr5hv8RAdDKBuHn9WnXqVXvMnZMcy2P25G18OZQmNBY0LNhcuK
VORRZKTG9Z9DNXKVtgGAPvZSAAAItShwz22jYJlDM21pQstCiavUEEd7IX2pAqvMpPu0NzhqkWB6lQ2eCzS1HTpma9VwI49_FeGcc1lnfuFe1sVfV5OkpcVb
iydwdCoLZyu_
}

