sprite $UCS_5108_Blade_Chassis [73x55/16z] {
pTS7RcmX38NXWUE2OV_xVORn5UAryKt_5K-gFrbABqN7-zDIYet-_eOLTKUPtXEhIzEHMjvN5PT6DpnVsu-tWqseeHuz4fLwrZQ4YdXyP3eO8A2Z78Ip1HdT
XmhEx88grdY4cWc4lRQXMcejPJu3fGFsMbiG4q0qYKgtYZLKkYugpnEhGqofc7YlNH33WOerp5Go4JFjDGueJgJfC3qIBMYl1KG5Jxtc8MRUQnSaBCBFcOyv
A5PY0ZfY92AMeu3UqO-6XibPJGGvqZulwYeUnVjKKfyrqVZewYCM4052902fgfGSf8w01SB01R4ZdZ2hnaKf24Ae8EKBKiYyIF1yToBI6Ri1RY8z86681nQz
QYzcjZOyjhY8AmgBS47bba-1zTa32DT50l68HTkDHEYyo1Igc3CTHIBIvZ6RGBh828XP221XjottMLCpKsh2O36sqOTBHY1bLY9g3fKyv0YPChM0L9enkQ6t
Bkfcmo47-eHwjoD5fkRBgsMCkEXsyMdQJylgRsRYadtHRMLl7vYTyV-JLH_Hlo_IrAT_GwUtUYyKb_KvNhi1zMir56ji9kAZVHZgwx084-iYlOjTa3Z4Qerq
-ObYhHcBgQ-5fERZn-YurLeRmrgyRW9jJAeabZLYJSyrQw6lYpNJMjEzDkjEDg5vrFnJq9AVjTv8J4bDs2v9UZVjNQsFD1HhFjh2ESf3BxDQNeS4bFmw-hpq
evnY7-9O-R3_idy1
}

