sprite $Ultrasound_Device [44x95/16z] {
xTD7WjuW38PX_Me8lllVDx4y3KOuKrVnipIl6uN-SlIuD61qCXYlPEPGIj5O2wQMtDquWb9NKU4BwcglxMlQcfkfcdbh_CpALliRoa-qR3tUyCjMsaIkMcqJ
lVXUCP-O5EqpMqXIBrgrHOwOb-qxnqDzRbKsrFnTcwhMDoqNYkVcJtD1wvOV1RQgrGSL7bP-BpEjcALeayXyZjHidOTWqNVCpBESpb30UKTE3Kw9WT4l3O3f
n1x_u3p_yTuKIemDfExqZ85rUFKInt0xUQLv6s1AYX4xFVfXm2brZ6SOsCa76p0cAFdoOwbP2YoE7vjRT3ez1cP62eoPIN8iEWK-JDdZWvH-Ytq2VjBjThlT
kdr0Hshq0O4K_061_y5DFe5-5oj_TCW0-7wJ6xqI79GAXWFJ2ySXzcV7rfkzRDTNSbzUj7nUdwu4kb19Eu8f_G4
}

