sprite $Unified_Personal_Communicator [65x68/16z] {
lTPHbjem38LXwUegDjR-zzl4O18FcE1mJh-tTaO_YkOXo2VWiYo4N0MwBolxRVvwWVHMmBK5Y3kx6cXZMEpY2SZb-X4SXnkOoomjJhRvXSLa4YFZkO6bI38f
HoGyLZ2FADDF45l1I1fIh4ocU6nASdhAiKaoHQsYcP5MdKrmLbzC9QPbEyn75ESCpn55vS7M71HZ1bWFweV3fhW1VCVl2FEdfQ9wb3tWIj8meY8uCAuLOd-6
5009Q0NzIpPwPBwuthh0nyzVAJfS0_dRm3w_izV0O5YX-_pEljr0xl1ZGAy7zDSD80__8z01hCBZ1lO7JmC2grG4ziANyu3eOPKUVHa73glNmc3yNO2REWXL
gOolt9VtWSga6HNg-3X0o17g_sYzm-FZpm8hm-Rv-TXZxkU1naIqUohG_JpWXm1u3C3zDE17D7-WL9mCx4pkU1RmlyYs0RQ8yeiD-68BuBu6JWBlEDir828s
6QYyKH6zj4531Rj0_s9n7M-mwmBMlTeAC1WVpRUNw_vw5yM4_lKkATQ4Jxb55FtfAqx9AaTczE_HJAMZAPSPYT9XYPWOZrMM0stpCmcN_clUd7u5Yza_OuaL
fScnAhS9qLt1uoBk5unoctIuGegLpwfFOVSB3jnoKs8Wjmk-u_A4OS4-N12oop6GHCVhGHl6IB4SOwM9iLpYDuNvf_5i_m
}

