sprite $Unified_Contact_Center_Enterprise_and_Hosted [73x55/16z] {
hTU9bgiW3CRnZmIomFk_xzMGGwjbwjt-iwgSds7MjXGT_vwMKdpqVszuqSCnQV-Is26TZb9v3oX_6EaXZUvCxvqG_Lc5_OICBk68_ZGBY6_ERuu4Md52hwWW
8dwCtbPj86Jq3EMgBRGSbDUvQ0-bb93NsmgwRNKVlTsm-eGkCS3vMIfVe5oRKDj2lBw1vv1fqYkEgzDf2LrYeCQ7NDTc2VFxEb1U_G9HCErIR9NMqVfyGV81
XKFjtkLqVRkF97I9WHYR9MhtY-j2NTScD3wXNBuff2htjXDLe2ndAnNvgCT4UeS0aX-ZpLqq9kfwAQ2cFzQ08dgh_m2HHjAQQ2RhW86wWyO6Ye4aVsxcsVc3
9NCakZdUHqAtqSCfuDPugXm_n3G5Gf6xqxSGp-Lj7bA-ExtOLE8h2sS7rVZ06Z542NC40UUAgvEGgRvUhGBDr3ZUgvcAoZdGUHIP06oQwsEUt9fTOa3CbA3h
b83jhO1MSvZn2TM0x0kaRv3dllgF44DIQQeWcpN9YPQpc0-e0Iq-rDmgr4hHd8KdrD89O4tavwdrAa1rSor5_UYSnYlOtDqOpSyZYEUsLW4TcUVh8O3EZmsb
nO-bk1k1vu-bnS5vpjEvGQjO5xC80GKaCHVFFouwxmH9PWzb3QYJrDR4VARIHFCw8C4yG5fGrFVbnD3n04KrHzfNyTkGpI_2FiM2dYN1VdEzToUWbOGsLEGh
1aW_a6FXwLHFw4lE5kIK-gkyRWHmxu-G4Jn7P03j_fChvNJ68wG59nJr2e2alp5A06eVJr1lEBBhjxbKDU_TBV_wonXFK6USQG5AlcJb25FryGmvBMWVoMlR
RED9idighTOgwWlXJBzkpiT3Wepx-56g0JtK457_kgWyGJaudXPg7yzI_XtvzwpidB-XLJRdShF_cfV_zYpx5m
}

