sprite $Unity [55x55/16z] {
nTK7mgGm28PX88I0tl---udJChQDM_xNRdoc5oAVHtDQr3GQ75H46oa23igLHoeE1mOrvf8r6QtTOvQiT0b9kMZBe2ZTDTEF2eEndjSs30hn81DQAzVCjQl8
kT7wOBLBIEf5DvadioumsqzAjMnXy-ypacDMg1moadh1jCXN2aQyE9zHR5WpPTeaXP2-MEi2Co5YKLrlNn_LaWgNn2uJ9iRmaW6MzmZNXdQPFfv1AZCbqYVZ
zRRyWB4fbjpdbhkPjRS2youmnOejzxarnl57KDFoATamRhbwxqlhrDg6YNVCiEhKX6c7QSyQaxqGG7RD_CrY5Jlt5ah5uyqy6bZa4DIx-Cp3Y5U6esH6O04q
lUvfIkRhb6FhZTVrKbbO8MhHtLLtRzuYKnA7vMe06aPWYNQP5uqCHBrIbZUm_yyvhHSBWMMM7ryLATMDIVYOOPZK7rKYLdj-0LmEcH4gXHzHnijIOzfbALs8
IC7wYWK6ZnYA0XRVpUYCmIdflEcAeLflC1Ht6Fgxp6eC6vKr7tFEjAJpO7P7eKeaCOzN66gyWFhP_9uYlwM8_8xw1G
}

