sprite $UPS [55x55/16z] {
nTQ7ifmm38NXe-O2x_--aP4zYzA8IVkvdl4EVA3R5wZdRXL0Eu_TpeRggjUTkZjNlGdj9DMTCrTxhWzMURVwZfMBoMw_p9XPFiMGAgfZ2P6E1EHxZ8Z7QvhR
I7Io5MviN4S4yDYo20EYqG-OWcAjEx1w3CxCr4p70T9h3xgMfy15nvOuhh9WpQ9rQMQ-9P0u_9IPOJ7sHUm1OiF1vHCpiAzHZEUGAVPHkrWPJLOyPsNT8iwK
udAUzIxMIwG2AekDDUDvEK4pczay8T1wOm8fTN1OYVh5wae1LXiF7QpEZ21c9k1IhpBpbE2H-IbojXp3MyeRx0mM5ND9MdpdwmDLRRtEBDsRfDIVT2IMHlqn
RFtChFd7E0h3OwljXyfPyt9LQS6lwzt9dLMz9S3tuVZQ-_5XCTlNaTvXTn0vMqSpoWGKJuppdm47xhUghjbkkOhYKOlstbiiBoObQptNbZfY7SxkpKcvz9IZ
t8VbIQLczCGSfaa3FJDlJPhGC-jjJjeMUcRNBn3ZYYovB8yUk9aA4r9SpwUEgXdDIS_7UX7Ck8pctzFdkd4uxUTMQrYoJRY6fNAScpMZz9NS75RxkLql39Z3
xPfIV8hxmuhMyqszbFuA7jtTVwc-KsWlLCFBT-PV
}

