sprite $User [65x77/16z] {
rTPLOkGm381XuTYIxt_V3Io45DDIlwUI_XZQpi0D4cyGXY3_Gj2Fja5475p5SGW72jlJ0OOBjCuVyQBp_12l1HfVm8BMPjS9NFKi0Ja0ZUYF1V3h1_xQBK0m
Jp1v3GYjC5h0t1AWHxI1Ti7y-2xmB_nN3byN2E4VGI9P4U78i2OptvabxOkGcb-P4ZJ2PTpI9_b1JjajjILa6rVLJpRVM4wgcinDiU7nw-C-kvJo8ltuDBjN
5u5fdG-P6ytCfrmhhEj_vwy5SRTSBII40DaIg79N22Hl2nY52sYaqGcsYPQ0viqak89cgMi7vSxe2W6iUNpnj2kBvbsvIhr82JWJ_o2FL8MvU0amYV0xKQKS
B-3off7mXaH5NmCrF1kWlxc2E90UvVP0z4-A6qm7P2uWgZC14Qq5v8qkQW6jZ8y7LAS2gis1csru9g0J0Ldq1eAz3mT4fITGc1lcbUE08bV7LSY307fHUiG7
nBday5rByLpb9HC4I3udNdRvSoG8hNBP4NIQ3yZJ5gXZlZnnd0XqxeIyt1rl_ni
}

