sprite $Video_Analytics [73x59/16z] {
xTU75fim38LX7Ls9OV7-pzieSMC76OnBT_jdClnbd2M8PhkVKd7kDPFQzoaxwKv5I-kzKd6-XzI7bB5y3qY9YBy7nFHe_WuG75g-0pGpaNwNFtkPb_LxGB4-
bCOAKDaSB3MXP9kjo_LMsymYv4u2nt0KO_6r4Neua3fjDtrDUDaiGhOfYmXQDRwOk0Ip5243HC3xgCHrq6dYzGZ28HCbcIPqeUX42HqeElN63MZ73aF5AHr1
oVeGHpb2re4eGDo4qWM84I323d8dGbKlwBCdb9Cdb9qU12_kouv3oReGpY3HwGLP6v9pI38auen3sm5Kvn3BPtcNJYEGC159iE5C5uhB8gtJA2JqACYgEWmX
IzKcwxT0J1xgBRaAQHLJZXdvlUX5IAj0-rXq52eE-Er0zJ9KulTY0PWPejg1ydYSeU240XIg84Hd72eILCuXRaARidn84D5JI66jTaC4q1iYr8U8PjLO0x-Z
qsm7-Q0rNsv9Tjmsaltn_K-_b_FThlk9zBjy7_e2
}

