sprite $Video_Gateway [73x55/16z] {
fPO7bkiW34LHeUz_lp-6vqZcCCoSxvkEyDLpZObAVq-XozFUqylmP9KtQFwOBa-YjwIFgRSgz1QfbwZmW48WFe4vzjKjKDgrnUKkyAzy5muJdaZfGoI21e3b
2vC7CKG88f81H1WtJ6GL3zkm4xMg4ZOYFOd2KwIrVwYgp_aa-cLi5UCkMo8Tt2AeJE15f3SZEcFu0ZKJeQQ_Y-uV5iY98cRHGGJ4b1UiamWHK8t01dZEjY5y
CDPi_e8e_MHIR5sIkA1XWaA2w4P9Od942XDD2um2OVugkjOZENJrM0UWJjHIybjGacECS09h0vlTXYXhy71C1bdyhOXt8YlcdCOZvnY2ufTxU56-s8eaPIC9
fZwGS4Fvea2KNM9IPr5XPj6uk7mY1888w3EEiXr7Hr7jYoXIp4_F3SU329xU2ie5J_COh1yIYYMd6tWWCdAvISB044NTKvk9TkZYOBc8Eyz9b5NsQ5eylPz4
INv6YwFreoZBYUHoruUeVWjvnlsZg5QY_11DyhYiVigrwF7UeqvQRnI23mKFXOjXodho834kEvIVeY9XakRFd9ApgSOyZx_H9ppGPY9Nr7fJRfMcJ5mg-Aj8
gb5cZ5B5DMYzAfXdM-z7aITUXJmihHkD40UqTZKdsqQ6tmyCYnTP79EbCE1I6rRXUevF2OFO5reoisEiyUPkURH0xIyq3XTfKob5Gb2SMKQkVOUYRUkWFOjv
rMkmXCiUU4GgKa-YJ64lijr_zmi7KLF_Lrwx8uRWrgqm3XmW45aSJ-eE2JSL_HQyoEedKUafx4L6PdyR_IYnMmBHYRyGKLxtcTlOUr7Pp6kjzON2lukmFMi_
qk9M9840oarNqPbYuK7_Bme2lANOghpr_0C
}

