sprite $Video_Call_Server [55x55/16z] {
xPQ9UcCX24OLH22-__iEKBtQsdmPx-pBwVPNE63N92LffqXowt5A4xTK-GHLyymIp2UWc6UQMqTUQ0ody3sjXeQd_5oDGoiEbixML3woQBCAwJsBDjf24oA2
XDJPDAAo53qE3T9ppVVdfOYNbgsQmS5T0wi24OBZdK3Y6kUbPzF6yTh4dsZuMejjGd1TijJwgLQNIoA5fjKtb1hi6g9hiuYrTiq_BVn4eqg0lSQOoJveQ6mK
uiwcCLj_CDfyMmjjKl9xY3VcjWDkQg9jQCAylbzVUPPaMgR94MgEUsUQt-zOKnUEjscRg7nyAG0auf4ZncciMZL3T7cFoIWpaWPXJHuw7QSc9_ECCgHTcr0A
wem-eGMlDLxYs3JigJ5AroGd0yGF8-Am17ZJ4l2wZg-OnmeR8eicJhLwzyhrxNj4x2kgdmeR-ZOayBdqjZUD7H8HubUNqWMDASuOJ5iKdv2VQyNdugmjiR5x
EQZDK7Peb1lq4NOnMBIcu3-Ae5reIhMj6auDUmlkJtrq_4mUJpGlbKrxw4YuQQLz1Ig1hl5tupzopqfooxhvpFmB
}

