sprite $Virtual_Desktop_Service [73x55/16z] {
pTQ9SYCx28NXmn48gVlzt_SQILItdRYytfdvivFYAx97fEsVroISxVFsDfncdzKkKZXE-IpwHTgtNeIV9QK7r3WJmOk9SDNE4Dv8hg2IZXn1dWdWg2me8i1I
CeBbSSVEWBgMw0mHU2YTTxHFA8gXPkCYVTYnar1qXhGWd8VTGAQHeBm15OriGL50PffHCrExyxXsJEqCsHWIDudQtHAoNw4ouc840TrDe3TG3YbsIGa8AM7P
2r2zWLGWcc1v1geBYc9OAy5nYN06nFHEQoSAQEzUQ_KOUgMe4g8P0TRhlFePyZ6R5tbKO-YaEw6UAG3pSsQgLlsq4sq1RJaqzq8tI3qW8SgPeU2I5CkT0zed
v1C22U6H5D1FhfJvHH3BdQWFvmgIurCKKVG4ALZpCbZk3EV7HNGxds1IK7mrtcDQDBOfDQ5sSNw1N50F235UKTmB8hfNbBKJpXvjpIEk3qq5r8o0-Amvr1L8
gSY4MYZpeXO5r9g2Z6NE2W5j8pV2Ap9hXXfGV9v3MP3xWkYj6Q3UeagWBYYs5HcRGLtWYGp8ZLPbGh6a0DLCELQM6L0v81V0YDgND233o7fJgP5Y9IbrBu3h
3mZinqNTLUAYshk2rysbtbjl1ZDasetM2JjVr7ltrZWWjgjCJ8PqgP7El3Gc-qQqFKeeIgXVPU9L0EsHmLpoin2N1BJrEv3VNEIzIbmKQKeMp82Csbh_1OBS
vF5nzrbJAuWOpe0kYN3x0NczoVjLXfabP4Mx1HJr4U7zKOsOILzGV8xyPMXpP3MXoukwe9XisoCe_dNT3LavGNv0S-WXhlfwMEqp8kDslcZFSlYWJO2idovw
6Uedg7q4uSZlGVi7qBzpqNu7yeUGF7EHWlee7XLLBP3j9zI9rwjZqsyETtkrjlyFjMyvqhxaYBJlEFy1
}

