sprite $VPN_Concentrator [73x55/16z] {
xTS5SlOu381XaKM-_trtbVXBLKoQTFX_og1t34L4dyyvLYUVcrwTy25F38-SjHuZU8OiSyuCngSuAkJqd6yXfgTu2mLJFTp5JConXOIP2UuYPfOL4c4Wle60
25ZaBKGebp19LsE8FGGabr3xn3L6S8I62CWr303SGklPMA4X8EFbD0GaewonUhP2EWJ7WU7SNbfZo4ChD4ELSUWBmGKqLDVOG5PTAr91_ML8opw6eiUAUaZm
1x11qO-XsK9NI7LOzUkGgUAu7EgVMgyFKBKLCaMnImHOxQ0aPe9gHyY4x18TrjKOiPddArGRlM60h0MLhFR0Mm1GgfDRoAqUz1upZto57gdEBfztSeMUTfPy
t5aolCJl7prYDXd5xGQFo0yXnHk84CdUXGp7dUKugbBqa52yfnudQa_ASxBs48teZD7FCtl4EDz2ZXRDG40_pyoWs9yj4KPjpXd-vwUTQkISIVuMKchBWGtI
3zOQd2f9raDzEUTMoBYUiys3KMRk8NeKSfelgGY5BcrjzgsjKpj4xGuZT_EhXwyFUzrZemYOyro-l_wrpoxuGcYD6Sz6PRxdyzGQ4vrDaCKDZcOKipEwPVqO
wJBkoNdPF_vN7VG_wlpPVzd_0G
}

