sprite $WAAS [73x55/16z] {
xT87ikCW381X5OGakFzz5smvCKwroKvzVthnDpH4g_CPTgVCLwqxxZQNUvEw8uGpKUfIWmHdamKomjd8LcYwW9Xcuu1wnDSR8KIwZ0MKk0SjlbWAQ0a1C5ri
XVm60QMBnO5CFMQ-B4b0MrsIAnqXII5DG7DIG5bkvIQnd2u7jAzBEKi-LK2QxsaM16REfzA0nfe4f4tNx-jGTJt409YRboQXJ00WAeqJ_IuhDQ2nB2bhXXPb
FPRtRw9IXn6DPLXAEaQaQndJu7o2nlab1DBeDbwlQyLKMCrqkt5IDLNOeg1CgSFXI8pNlAuZAaKPK7OXK7VX7gkPgI0yHDdhbZCyX6fw-6m2py85MeUaJKgx
NeqeFHkHrbl5JDXsSJBRGoIsfjG_xTT8V4DMQ4nj3w7OFK4WMzDcMjqNqB60aje-9ROrHV7w2L9HrrYSOsfRzL1n6svA2B10cCrVtSfW13Hct8ZcePY_A9XZ
FgO8mCqxmKGFJahYVeQ97XntEwT4fOpEIsHKNdEjLqvfo9cSGBfPIpG09vtftCAPJH33cOm1qY-SWW3aTJxdf5R_Qt_Phnoq7paOqhJp3m
}

