sprite $WebEx [38x38/16z] {
fTHLeiGW38LX87AI_I_u2Xc1DAFzdxyAsfOwCSoWgaAZrNM6kRjf95GQyndqri4HFB95gOmTMH03-3-HudM1342e1TAEp13griu20QkA9XiJTQm8d9bCnO5A
9TTlTjkKyf7bLuNAZ5h7QoMDR4DGISrXicTLCC8xIcn7jL9_MzbRQksCihSKV6Er4auA1L8YUqEDdZw90abh-PDwZAwxyAcwxcX_fkXsElonaktCFbAZ5Qpu
tiP2LYWpDoHKtaoURgPtRxdtRyptRjzV
}

