sprite $Wireless_Access_Point [57x55/16z] {
xT274Xin20HG40XO-F__ZP1BUXnTUjcvOTRbdGezWZ9w5Iiy-o-4bl8IogTUBk2Na5D-3qW7yFHoqZvsLIalNNqiKLNs0bfLuNU5_o7BoeRovMpOXJUpx5Gd
FviF_cDCZChp5DWgWR2J191bkPmDFeauK5c9a74M0RAXoMdy6w7hQJmRvdKuJnDtQAUvm_Xv45aR-cashCIfY_kAE6QTlM9uVErpNwqsZ6Vy4xMxFnhGyFPK
GpUFc8F5LbtTkjw_Tk6X4JOTq34KDrO5k32pAQtmqYoxaYclRjnTbsQJheA5RYiEyT3-QZAHXW-YCTTWsvtd0YFI-cMJQ6vO1I73qZG2wsi7hAVtkz7V6899
gx2daIsNZOKqquacuDnJQ63FkFKifP7bHD4SznNBY2o4ID6StTQ8tWAfw-heTvDX3QzKoGU4KCU6p27SLKHqY597TKmPilkkKGzOK6RnmbHB7ykXAz86yqIQ
Aj1BUxfEr0DsW4UhVAS3g6UFjxtXIVurc5UXNOJ6kEJ0n7Pbdqnl
}

