sprite $Wireless_Connectivity_grey [17x148/16z] {
ZLG9acKX29Cbx_v7dj842uTPsbxXOmW4NFjOuljitHFVFdaz-Ua4RSYKH_78CE8OxaVsVQc0A70G4KAtVGTo2D-Pqrh4mO2942eBWWJuHqImitRciXcZA1Su
MZ6oi-xj69m_HXSE0gzMcNd1ZPb0f6eLfYDliSahhdu7Ac_iGX9YtwbNgwnNzrO2RpOY2PcCrMTOgujg-pzX5TLy7Ib74oeMb4yCRNbbFGIp4OV0oYD5vPao
tEEqmonGjwuC8HdmoZ2xheZcY9lUMQWL8KUJ8JoaVZ6jOtE2fhtAXj2bWsaz512zXQykp6bDbtAKBhhITB7l1QsqYFDVzW41RNcQBk8clYr4CRBJKp6rBtSw
Opbjqb3NLmTl2xH23aM8T64KAixDs2QOXJo0PpzaN1jZNrw7x7HdWq9rYrYGJBIkGzZYZk4OLmReI3k9JUflSRPc-RT1zCHeuMZoa648DQGSOezn60CpHceC
tHpBfEaQt37QO_Z7Ulp5uU--507LgT6oyng0xdsGMP7p7NEHxwBNoRAHK0pjx2-_qLrzo1_jIxvIXeejpij0Xb96mvrAgi_wYpkg4xPET3kJ7W8WZDoD0KKD
FzeNl491anPLJDHu8FWuTvwOkfGCtZsTV9V1J0tfCZX-VxOC_zwN-MoLSaioQ64qot7Ljyg7JjMoJn1TeQRtazodNm
}

