sprite $Wireless_Connectivity_blue [17x148/16z] {
XLK9kkOW21CHYFU_y8o4zl7LMNmhAK8Wq7-SCoqsP3n73FltyVdOldcmQ4UPs3iHIpDCPspCCGJdgSa9ZUrZhFFS6CrEAj-R6UcY8qw00kG07u_99ENYvv60
d6I8CVhQHIJsTYbcFBIF3me8hU2nMtcP3EuWebbj_Z4KWNNiSpHlhk6dH2B8JB5N0Qoh0PB0yASIiIGtb0nb1VCcTPYZsBTYIAFfqdhz0jfq2dCm96Ef9FUG
WQowoS1SBtSRJRYHXQ8BTJoYDTEE_8fDIARpyaCSU7N1otIMBeqxPQ5_by5aMX2HOUKeLDIIRfCXBXdeqMJWB3RbXe35LH6Qyn9Bbp_g9_AXYjkkOsrVW03p
MPe-vQJnPr_U5YPST_FXoXkOJHVhW6yRsfJAojiIKfVXZovdwBmF2FUbBKFNk6rGSw4FRPWwNfzWAPFfrc6cp-fNrwFhihb0pQLxU0BAcC_CeyPXp1ea8wy8
T6Quc3x7kbt4NvrSrRD1MZeLCIMPrROXAdQDSCW5N5VM9-YLbiGRiPlwLTnL_jMWkuMzoN-LGRfGbvINsCchZyCrCDT8NKDtZUKrkDTeNyD_hSS5f0pQDYeR
6dHHR3qeqwGT_4F8KS7MzHwZJtklYlz8zzZX-44iDHKA1Jr4hAtUcHZqPSGbr0MqAmhk2x8sAMKy7y0j6dlzVduOWUfBhmJ9i6ou8SjbW319JJ7fu5BSQryW
BzNQb_5P8EWhLB0Wg5GnDWIaj4IiwyBFYsYwD1bQSNXb09emdf-C5a_zYj9B4ugs3VB_rvQrrrPJJg882bjJ-o8aJE-J3u4YHcVqXI6h748hizmyO_y2
}

