sprite $Wireless_Bridge [73x55/16z] {
xPVPbjmW34G57Et__x-X39mOpzxkxBalK2xrHVCuH9htKIBopBXDEca-1tZSFeE_Gq0LQN8Nou0eRely43rXfGo8tEFsGWwHoSsLBDKYCwtPBPEcCKHXZU-O
D9tR8NA-Op9usBFZtEbP7rd7qxW3KJY3oBG7rWdb9KgVL_-YIYqJ--mRIQIAvUV_GCExSHQbonHnhoF3xSDTOC6O7o9XcI8GgNCeC6JwjYGo0_qX4d0LJJGI
XBkPQKUqOsRkep417ulGguwVRK2jbYwV5SNgnoe1hwxwCT5MVKgaaVQ6QAjsKUmYlKphHoAzDZf58DDq4QVxfLAnZ9U30L7CwvkYFUuYtqGlD_8tDr9_JUHt
HVj66BFJjEqYUo6oww1D4SYq1NgRx1M0w3guY-Qt_JxZpnLbW7dC-mfRjPVxFVyE_cEgzZrvJt5gmsRUXZTCn3AzKOSpbPj4Qkcfuhk8UgxSOsFBE8QRRvfA
LAZX0CnKAbKTgPYWBRgozgwGj1bF9Yz5tALFKs4-L96AiybumiFgob2ltRaGSKxmKN52eSTH8iVfwPMe8devBaP4WZXEc-s1TkiKjNxONBUDN-X9P6DAJbD2
cfFrpGgDZtMzHJO5CWHrFbjylGeHT1DiRrQfTp4CnRpH40YY6WxI8IHsfVKwT0kZGM6gggL0MOZwAShKe0HSYNkURJ-hIe5j0U_XiTHZEQy4D1hawSF4uLnw
3Y7GGWjHiznmOHQummoHQ-NZOevQcH5NrbQR18OzVrlqMHxoV0PEJ_il-ni
}

