sprite $Wireless_Router [55x64/16z] {
rTNfbgGW38PX324aN-x_VWSKKr1gU-RFB6-lUdpOUgaqCfVqbhYbw6ymSNvbV1sQBRq7_Y-PW5yLGxwL--o8MNhCD2ltBsSUjuZ5u6SmOOgXtHuOQoE0QHMH
geP-gVmpOzt7Bvcs8yh7tChFZ3ggJCrGRnkVk7P83ynme9iw1EwPGmkryXqi2hzdgFcdAcuP9F-Su9iHcYBYpDm_eZn_pM8EcfbsrJItoiJA-bNWEYbnLDfd
BGynPzfoQKv2yNw6wSarGLjgvL8gd3_dOL8MnoNANHorAp6tQOdIogcNHGgHH8LEjHKHgUSo2J2HsL5_ukf8UWPGJ3QxlghEmWsMHQRfu2OIRiGJEsQBeSnj
76EDJfVZJgXDwfxkXwcEEZKUebLjDDs2Qo9WPZc6NfHKIZaOGEomHOraLRLIqNfaS9R6z4m-FzkYhLDfgrOTDIQwiwYASEuFvtuHQXHC4Mp1lC_MrqoYLsQt
JFkjmr7L6mPtm1xJKkqIu2qixZq4kphLPpNO3Qn4-epGqVWwotxokzEgg_7nRjvfhFPKBUwilmeKqPXcPE8Zn7frLwG6CqgzZLXqVs2y2yU5EwJFROSoz3YT
5VWd9dW48WlbUtAhGCayiYrHNPJhdN9BIJogQHJAiSNhzfIaDAsod0hpSiAjDpKkyqN5KE5YvVmzCjcwdbAtrN7gwMUZLwVzD5QdCNsSo7Lp0lV5nSzIvcrG
BjNWIukJzGNVUGjnJNUdiPNFeX3YoKcSMsplDIM9ZONpzn1d_rlpnLoFxbr5fA-RIxS9_3b8UehqTQhxM70x4wUNY1MhKOwPNgIeeGjJkJU_
}

