sprite $Wireless_LAN_Controller [73x55/16z] {
pTA1Skeu38LX7ScoBFlzttVjav2R3atOdR0pzsyBmXKV001jFAzXEVrvKwAJxKb9QJhfYYTfoIbDo76Vu5DEAFKJz57IN53Jso0pw7sDa7rmFaksGpT1zjJk
8fHsdGhxAEK7I257-0oLDPRtFuOJKwxsoWvTPgMeCDjl_jeBydBJ0TtbEtINxP3VzPT28-jZgEOWTDSBgdTz6UfVWFfoUjIt_XmLi1AdVxqLVImftdBtke_L
sVbcl9MN402rij_zC8efW5-WFYwWW33TXCtJu-pTwLUG2VDDq5WLOVQBizLR_AmM2BCNMiuwIerpEVf4DgZzAQf1jX0jebNCgRuc1ginDnilSZ12F2GNhjXs
8UA4LMRAntAUhw3EasXzd2161iSZcXZFYh0NQiSp9aNdWFA0i35p8olua1N2K1iFwroEZKAqNCu9EZ8-q9huwcT55I9GzNMJX_CtN4KiwPoXjlzaM5txdBVh
cGbV9GLUSALQ7Cm1tRUW_2KwJo4o3w1hXlrNYCnpg9Dv1b6vgS_-1TJFoht7Sg8_t1PnYtnsn_fvL5QldTJe7FV2FSUWtjpZZgYcfJU8Y6LHzTGvQgQfHIzp
HeJ2igwLSkqKU9X2O11e1BPH9-CmaNKCRuPr9bAld8eOewiWXukqUR2M0sA3Snd9kK-dZpB7YrGgjtoiUqpK1NqCso3EPOUu65TG4ULpSUuQ7vd74qqGyZNp
OZJq2uVBAgA8B10n5S3JeGA5G2rVxneqGtrS5loyUbLO-kipqkYsvjPjkVj72ZgNzQXjNVMbkdFc8zJeu_JDulW_rRxbe7t90Tftd7y
}

