sprite $Wireless_Location_Appliance [55x55/16z] {
rSu7SZGf38PXvK_0_U-xmjDbuvt6K_ZFR-Vmb23ASLhIfOvTgTvmKklbIgNoIOe-gcPybhR98ATXif2xc4WgafjYCkXTawaMq-Vsh03JFEkMsLt2Ic92TXE-
OcLUCBzbHbBCRNvVJnVpkuJTbPZDdtl1N8Xzn_AMgTJ9Nh2pyet59hSwuhaNJCZZjZVMDig9z9XLoluLmoRZm6tjmTm1k0KG5Yl3MjZCFvWA44p-lm4cdncn
Y1Y0_c1EKOmL4CL-6ZcgInK3UvgOp1kyvqnwWPLbgOk9GiqPpe64QLHEbKNbR40M4n6DIusUMK8Sx2P8A15Nj6QPMSpCslXWmGLJJERdTPfUq_368WijB8Kb
qvWZPyYPbq9MYCm7w-CJQqRMMX2ZPQl7n-PoFJnUWjJTuvsr4XgjmRojJRQKDblOqfxrSNN0LlIQOOlsB9XiY_QiAQ7rCfisgYV6Y_fLg-tH-Ct1FSw7chYB
dheaZD4u3baZxuNRE2nO3EEy5igIfmZp97AynbvdFsLT51dYux3cgXRZNow_foY_fMYwS_KV
}

