sprite $Workgroup_Switch_color [55x51/16z] {
dTDPciGW24LX44M5_U-tnGoaIpF-FfhptHe1YkWxKg1LAczfwLNXDufrBSu1tmZSEfL2-0ZWYefbEJo2qBhGiMLCZo0q6AZfMQPp0HritNs6CC1FcNMvP_7S
T2tUPywh9IlfN7IuHYcbQHPZch4isDKy8wIJRByeFUE350289r88YLT3HWWd6I-HPzLl20nnIhoSqPX5X0vTv9dQizmnmIZccMCMyLEMEJpCgdfs6AIuup4g
hMgPrh9R1bFvBvUZsfA-LfmD3XdJ8HIBnDAVPuOi0V8s9MeySv5_r_fVSvtQClcVrNwQkftAq0HUfdoj7fMwo757O32A3jaWmI1aTISPmmZvIuQntcTXHOJ-
6eTiJXhD_eaSYQbMvzh9ylWc-zHC9HATo3urmGYaCuMkfW1EChcSQaALdGwcKmRTC3oT6eJRIWY-P3Rt8VCtXxpBjuqFahvMwLDcWyypEGxouwpe5mNAfmgW
o5kj-WC
}

