sprite $Workgroup_Switch_subdued [55x51/16z] {
dTO7ZWCn28LXu07A_K-y3jOIZ_38vT-Qykcb9qJ-ESsfgOi-eKnna0LqLwQJM9lwk3Mr_kuYVjY-J7chxYASChfajCLeB9q6a_TerXrZMJAU8EdCP2jEbGoF
Bq7-dmZ1k9-rCpnYOingJD2pmYHFBOm5Rqo8tbWUMnbJibfX2cXCbKGnViNtFzCefYgRDJAX6pQVaxbADWwoP9YhPEEWc6dF9gYfpePY4FOCelRB2ml8bH5Z
G9L5KXcHQAfafSg84MZ5j3nNPOU1IgmZyoNBSCN4bapvLxcCbTLSS-h1MjPi-zOus_UhVMUQKoFBZDbyakRKZ869VSfogZ8JeXTcvcyCz8tjL-M5nTGpNZDG
ZMt5ZA-O6wxORn2P-ef5ABV3akNW2SjmnzompVmkEfTDqEMdrpy
}

