sprite $Workstation [42x34/16z] {
pSm5aWKn28HX2fe8VV_pFfTnihx_Q9Al40G72WX8jomuYQ3fOjkmoi2WAv2DBCKQ2ODf4WhyAbEeDYnrVEQ_a7buI6JEovX4AQby3dpBW-ukb-uBwV3bxS_t
GYvwkaG-rQ74jQVRbCjocSpqXSIcD2Ux3b1eZyPcccQDLHlPqyYc8efPmNiLqrJMrOTKoMeFYNs2TYiUCjgrBQ_SAlGhKcfim2glpW
}

