sprite $Workstation_on_Wheels [49x82/16z] {
xTPdmkCW38HX8I7Pchd_URVXhq92jBqz_r9UTmFoYOEFI9F1oCDjnqz2Hv1qjNVwJ8CXdpKSshlTrzrTCw_0hPjkcBiThmBTChTu2Upt2xgLWwroq8k1Uode
NWgwUoNexelWDlTAu9SvyBLV6RpXtNiX64Lr3tFo-XKzrRQRVpK8I3BKThhfmHY1WMVuJYHJPT1yIAYyqhRaDOtQ3Wp4EmGdBfS6pdzV96Wo104KTg7ayk-p
7Bj8uevv5qOW7d20J15fII0paS3bY27d7TdgZ4-v6FXUYc8AKcLmS699OYeku2oJDTdC2qobh6bD2zPuLeF04aaicRGL8w5jHTQKH9E2FpNu7_mF_WVbKQCy
BjL7lcgWLjFagwdUZ5LbqfA4oOeccLFY_0Gg2ybFSlajJMODOrlLuFq9shMwMGX-4lAUWwco562yREeZ
}

