sprite $Xray [54x58/16z] {
dTPXSeGW30LWGf9v2Nl_-rR5fuXrfpQ_QE43aeL14RJFgsWG4NpQo_Y0w2LxxChyeZuFmwDMvACVLGRSj2gMffPIgkN2hQgv8tzL2QjIjgZHV6j8jBJIGmnv
Kw5dRpH8v-jQmsoOLCWcwhuJBrHzvwwz7rTbfOXw9BVRLzOSKZRXD8VIOXjXG3RLnWWNYOi2Ueq3xhxmh5G9TqIVCd1TgtUh23UsRT6E5AKQnQZIAukewsAs
guG9EpmdnP-b6eBbOLu9hrtMk2eVwdugur-ilSqr5DPzLepmMgOQkWTdHLnLWDEbJsiDPIpYw-BC2p8LS5Anbr4ngkWr58_VLBgCHrjv3azdyN3cnR3FiIqh
oLrqXqcbShPHiMHq4bS5chiQdL-Lyyh13ETLMLMO-PvViQiA3oOkE4zKxXTMenSCesAW7Yb3ZWr67K_khDAb8uxriyaZU5Dfb-8sQBJnPz6O5L4z1o8vEJir
xyg9M7cD38-HMSugXEZuKweKN5R3h41q3kBYvt_yhYIcIsFA3NBJDgkedEWnK36f-Rr9joKyBYpc6iuHmaVb7i-gUMTufrh0pJnVhhNTjWVq9IynjufNAlLV
rKYOgg6zh4P6HBQ_gUHGo1AAFwaqaUfnF7QwpmH4FYlmus7rgqf-E8ZYKPsV9D72brWiG-99wTehV4x3oXZ-JNbY6rrTk8h8LyLhZbeep14HxBYhlNAMvxka
I4xt9I-SEu4C3pE4xPlYKo8uxcLD8YxrV1a5N4kJQAn50wR50W22hJx_rih_VsGJoS9U1aH-
}

