sprite $Xray_Workstation [107x41/16z] {
tTO7WeCu38LXwJqfRlU_xyOWCvWuiBtzwOrlP4_JLFAwcYbxgi_9bjTQrjLgkJZNMIxQ7I-_feJ-tkgyP17J6-D8t-5usPsbZvLQzUTAAoh2GkCoTzP2Oa-b
fnYv9HDXAm3lidT4QYx2H6ATM_bEsKPv8yrM0kt8NuwIJvHEVL08wK9LcE4X-elfHAbCNQXu1pwe0YEUOb3F2pXIF5AgWEvNDvHEfuCwmhp_VgLYORHVnt8l
g1vq2gHD54JGlO3yzK5jpWuE-8CoBh9-j5AE5_idTUDevYjA1taGgXzK3tFkWueeMxGEBQanoBWAvudYcOgW2dRdIkrja0BKJa4tbrlsG_bsYZmQb2zQKg8O
IyqU49JxGNcFNnRG8oD1sfeQGHKxfOenadzGK_C2khb3jlX97HP4534LL4G3yjUyL-RNWeeNgTB39nLHEsIsKHQtlXTKvaeAgXa3CqBVqKSil50m0ymsYg0n
tZscGZL65WsOtd9rM-UbwA2EL3edsk5mJbD9gidNfPhKqr5kBQTJAa5vHDrMp63zMa_x6fJO-UYjdM3AERP6EHUKH-FWeF5Y1NKzd4dq_DfCCGuD4UoqpbFD
-JrL4_KxXUCdCExWwrJmqcuerFQk95oeeq2XIe-MKwddrYkGRs6ynN5G5OSp8cPgdaejnPTCkGsfj5vsZGKd1sN-fVWtfZlSFr-JgJpty-vj_pBM_ob5OzDQ
4j7uPFPdvx865D7SYlCfIwr2nFRrWFo6OcUjtqbrhaLrAbCsAjqvZpzbEeKQ4lISz2m-yhkfEHsKojIVIwsc-aiebCLU5VyhgDHMbR-2yYML_mfAqohy1THJ
lvt2aRVc-4rTFwBtKcr_NdPFjVy5zGi
}

